### ISSUE TITLE
New repo?

### ISSUE THREAD

**Issue by gannetson** [tomturner/django-tenants#1]
Hi Tom, 
I see you set up a new repo for this again. Weren't you happy with us hosting it?
It's all fine with me, but we really want to contribute to this as well. 
Should we fire pull request against this or did you plan to use the django-multi-tenancy repo later?
Cheers,
Loek

**Comment by tomturner** [comment]
@gannetson I have created this version so it will work Django 1.8 and above. I know you haven't got your project on Django 1.8 yet. I am happy for you to be have admin rights to this project if you want or feel free to send pull requests. I would like to keep it on my Github account at the moment. I have the multi url working now however i did use the new array field in Django,

**Comment by gannetson** [comment]
Ok then we'll fork off this ;-)

**Comment by tomturner** [comment]
Ok no problem Let me know if you do want to help

**Comment by gannetson** [comment]
I defintely want to help!

2015-06-12 12:39 GMT+02:00 tomturner <notifications@github.com>:

**Comment by tomturner** [comment]
That's great. Are you sure admin rights?

**Comment by gannetson** [comment]
Yeah cool.

2015-06-12 13:32 GMT+02:00 tomturner <notifications@github.com>:

**Comment by tomturner** [comment]
I have given you admin rights anyway

**Comment by tomturner** [comment]
happy to have a chat about where to go it. I don't know what the best way of doing this is.
