### ISSUE TITLE
doc typo at FastTenantTestCase

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#103]
In this link: https://django-tenant-schemas.readthedocs.io/en/latest/test.html

Scroll down to **Running Test Faster** and change ``from tenant_schemas.test.cases import FastTenantTestCase`` to ``from django_tenants.test.cases import FastTenantTestCase``.

**Comment by tomturner** [comment]
You are looking at the the wrong readthedocs try https://django-tenants.readthedocs.io/en/latest/test.html
