### ISSUE TITLE
Version 1.2.0 different from original source

### ISSUE THREAD

**Issue by mateuspadua** [tomturner/django-tenants#109]
Hello @tomturner, how are you? I was going to test the version 1.2.0 and i realized that is missing folders **staticfiles** and **files**. Can you see, please? Thanks

**Comment by tomturner** [comment]
@mateuspadua I don't believe it is other wise travis wouldn't work

**Comment by mateuspadua** [comment]
Please, do this test, install django-tenants with pip and go to your env and search by django-tenants and you will see that the folders staticfiles and files are not there. Thanks :)
