### ISSUE TITLE
Slow migrations: Rendering model states...

### ISSUE THREAD

**Issue by flxfxp** [tomturner/django-tenants#113]
Hey there,

I seem to be hanging for a long time on "Rendering model states..."
This seems similar to https://github.com/bernardopires/django-tenant-schemas/pull/422
Also found: https://code.djangoproject.com/ticket/24743

Are these related?

Thanks,
Dennis

**Comment by tomturner** [comment]
@flxfxp What version of Django are you using?

**Comment by flxfxp** [comment]
1.8.17


On January 4, 2017 at 8:47:48 PM, Tom Turner (notifications@github.com)
wrote:

@flxfxp <https://github.com/flxfxp> What version of Django are you using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tomturner/django-tenants/issues/113#issuecomment-270467969>,
or mute the thread

**Comment by tomturner** [comment]
Is it faster if you update

**Comment by AlexvEck** [comment]
@flxfxp Migrations in Django 1.8 are notorious. Is is possible for you to upgrade to 1.10 or use a monkey patch to backport the new migration executor?

```
# monkey patch Django's migration executor
# https://github.com/django/django/commit/5aa55038ca9ac44b440b56d1fc4e79c876e51393
from django.db.migrations import executor, migration
# import MigrationExecutor from somewhere in your project as PatchedMigrationExecutor
from monkey_patch_migration import MigrationExecutor as PatchedMigrationExecutor

# you need this line if you're < django 1.9 because attribute initial does not exist there.
migration.Migration.initial = None

executor.MigrationExecutor = PatchedMigrationExecutor
```

This should give you a speedboost for sure.

**Comment by flxfxp** [comment]
Thanks a lot gentlemen, I really appreciate the suggestions. I'll look into backporting the migrations and let you know how it went 👍

**Comment by KFoxder** [comment]
@flxfxp Interested to hear how this goes. Thinking of doing this as well. If you don't mind letting me know would be greatly appreciated 😃

**Comment by flxfxp** [comment]
Seeing that this is quite the change migrations, I'm holding off for now...but I will definitely let this thread know how it went once I've gone through with the changes. Please do the same if you happen to deploy before I do :)

**Comment by auvipy** [comment]
It will be good to move to django 1.11 sooner then later [it's beta1 now]

**Comment by tomturner** [comment]
I will try Django 1.11 with django-tenants as soon as it final. Beta releases have bugs!

**Comment by MiltonLn** [comment]
On a project i worked past year we started with Django 1.8 and the migrations were too slow, i mean with aprox 500 tenants it took hours migrating, then, we decided to switch to Django 1.9 and it increased the speed a lot (hours to minutes migrating), so, i guess switching now to Django 1.11 will increase it even more

**Comment by tomturner** [comment]
RC1 should be out on the 20 march

**Comment by chrisspen** [comment]
@AlexanderVanEck, That modification had no effect for me. I put that at the top of my models.py, but my migrations still take hours to run. Is it supposed to go somewhere else?

**Comment by AlexanderVanEck** [comment]
Hi! It's supposed to go in an __init__.py, possibly in your root dir.
Django has some instructions on how to monkey patch if you search for it.
:) (I'm on my phone right now so unfortunately can't link the docs).

**Comment by chrisspen** [comment]
@AlexanderVanEck I tried relocating it to my root __init__.py, where Celery also recommends putting it's hacks, but it also doesn't appear to have any effect.

**Comment by manelclos** [comment]
Using Django 1.8 in a project. I copied the code in the PR and now it takes a few seconds to render model states where it was taking minutes before. Awesome. Thanks a lot!
