### ISSUE TITLE
Is possible to have a super_tenant?

### ISSUE THREAD

**Issue by MiltonLn** [tomturner/django-tenants#12]
Hi, my name is Milton Lenis from Colombia, i'm member of CEDESOFT Team and we are working so hard with this tool.

We need to have a kind of "super_tenant" that can run queries (with django models) on all the other tenants, like a big reporter. We are thinking right now on strategies to do it, but i wonder if there is a solution directly with django-tenants.

Thank you for your support, cheers from Colombia.

**Comment by flxfxp** [comment]
Right now I think the only way is to parse through all the tenants. I have a function to look through all tenants for users with a specific email that looks like this:

```
    customer_instances = []
    # go through al instances and look for user
    instances = Customer.objects.all()
    for instance in instances:
        # Log into client schema
        connection.set_tenant(instance)
        ContentType.objects.clear_cache()
        # Lookup Users
        from django.contrib.auth import get_user_model
        User = get_user_model()
        try:
            user = User.objects.get(email=customer_email)
            customer_instances.append({"name": instance.name, "url": instance.schema_name})
        except ObjectDoesNotExist:
            pass

    # once parsed, send out an email, denoting if the user has instances or not
    sendFindEmail(customer_email, customer_instances, "attendy.dev")
```

**Comment by MiltonLn** [comment]
Thank you @flxfxp !! 
I have a question for you buddy.
what this sentence does?
ContentType.objects.clear_cache()

**Comment by MiltonLn** [comment]
And what is "ContentType"?

**Comment by flxfxp** [comment]
contenttypes  is an application that can track all of the models installed in your Django-powered project, providing a high-level, generic interface for working with your models.

It comes from django.contrib.contenttypes.models, e.g. `from django.contrib.contenttypes.models import ContentType`

More info:
* https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/
* http://stackoverflow.com/questions/20895429/how-exactly-do-django-content-types-work

If you don't need it, remove it.

**Comment by tomturner** [comment]
@MiltonLn Have you finished with this ticket?

**Comment by MiltonLn** [comment]
I don't know if there are other ways to achieve it. If there are no other options i'm done with this :)

**Comment by tomturner** [comment]
I would do it in a similar way to @flxfxp

**Comment by mikeshultz** [comment]
contenttypes is kind of core to Django, I would not remove it unless you are absolutely sure you don't need it.

**Comment by MiltonLn** [comment]
Ok i think it's done, thank you for your support guys, for me you can close this if you want :)

**Comment by bartmika** [comment]
This is a useful ticket. Thanks to @flxfxp for your answer. This code is a great thing to have in the docs as I was looking how to do trans-tenant iteration.

**Comment by MiltonLn** [comment]
@bartmika you must to have on count that this strategy is very slow with projects around the 300 tenants, that was my case.

**Comment by flxfxp** [comment]
No worries @bartmika. @MiltonLn, that's why I only this for for time-insensitive tasks via a celery worker, such as looking up which instances a user is part of. Let me know if you ever find a better solution :)

**Comment by kosz85** [comment]
If you want faster solution, I would play with postgresql table views on your place. You can construct any view that aggregate any data from all your schemas (or selected ones), and then build django Model accordingly and query this view.

**Comment by MiltonLn** [comment]
Sure, i have used a postgresql materialized view in the public schema that loops on the tenants ( for reporte purpose) and it works fine, a little annoying the manual update Of the records but it works fine. @flxfxp, please can you describe the work that you are doing with celery? It sounds interesting

**Comment by MiltonLn** [comment]
I must add that i'm working my materialized view with a Django's Model with Managed=False

**Comment by bartmika** [comment]
Thank you @MiltonLn @flxfxp @kosz85! I appreciate all your comments.
