### ISSUE TITLE
Just two questions:

### ISSUE THREAD

**Issue by MiltonLn** [tomturner/django-tenants#121]
1. Why `TenantTestCase` Inherits from `TransactionTestCase` and not from `TestCase` directly? i have understood that `TestCase` is faster than `TransactionTestCase`

2. On `TenantTestCase` we can use the `setup_tenant` and `setup_domain` methods to add custom fields to a tenant, but this can't be done on `FastTenantTestCase` so `FastTenantTestCase` can't be used right now with 'custom fielded' tenants. There is a reason for that? this can be easily achieved, let me know if there is not a special reason and i'll send a PR.

Thanks.

**Comment by MiltonLn** [comment]
Another question:
Is necessary to have `cls.sync_shared()` called on this line? (https://github.com/tomturner/django-tenants/blob/master/django_tenants/test/cases.py#L66) this calls the command `migrate_schemas` for every `FastTenantCase`class instantiation, i guess that is slower than call it right after the line: https://github.com/tomturner/django-tenants/blob/master/django_tenants/test/cases.py#L74 which i have tested and works fine, this gives a tiny speed boost but it's something.

**Comment by tomturner** [comment]
@MiltonLn I didn't write this part of the program. I only use the TenantTestCase not FastTenantTestCase at the moment. I think I back ported FastTenantTestCase from Django tenant schemas.  I been meaning to use FastTenantTestCase to speed my testing up regrading cls.sync_shared() what we could do is put it as a setting.

**Comment by MiltonLn** [comment]
@tomturner thanks for your answer, are you using just `TenantTestCase`?
what is your experience in terms of performance? i am worried about it because i have a Continuous Integration process and i don't want it takes so long doing tests, how many tests do you have and how much time they take to run?

About `FastTenantTestCase` i am using this on my project and my testing have increased the speed a lot, not as fast as testing without multitenant but considerably better.

So, do you want me to send a PR to enable the use of `FastTenantTestCase`or do you prefer to discuss the idea here first? 

Thanks!

**Comment by MiltonLn** [comment]
Look at this scenario.

I have 52 test inheriting from `TestCase` and `FastTenantTestCase` alternately...

If i run tests with `FastTenantTestCase` inheriting like now, from `TransactionTestCase` it shows this:

![image](https://cloud.githubusercontent.com/assets/7388681/24735715/d7a1c560-1a49-11e7-8167-9e305b17d1a8.png)

Now if i switch `FastTenantTestCase` to inherit from `TestCase` these are the results:

![image](https://cloud.githubusercontent.com/assets/7388681/24735788/3d1fa88a-1a4a-11e7-9166-8b44aba1c175.png)

i think is a huuuuuge speed boost!

Can anybody else do this test?

@tomturner what do you think? i think we must to implement this.

**Comment by tomturner** [comment]
@MiltonLn  Is this better?

**Comment by MiltonLn** [comment]
@tomturner Definetively, pls Let me finish some experiments and i will happily send a pull request with the testing enhancements

**Comment by tomturner** [comment]
@MiltonLn Ok that sounds good

**Comment by MiltonLn** [comment]
Everything working just fine, no additional work needed.

**Comment by tomturner** [comment]
Thats good news I needed this for my project

**Comment by MiltonLn** [comment]
Great, when will this be uploaded to pypi?
