### ISSUE TITLE
Bootstrap code for a new Tenant

### ISSUE THREAD

**Issue by perrohunter** [tomturner/django-tenants#124]
Hi, I'm trying to add some bootstrap logic whenever a new tenant is added, I was thinking in overriding the `save` method of `TenantMixin` however the schema for the new tenant is not set yet at that moment.

What would be the ideal or proper way to run some initialization code for a new tenant? (populate some data in the tables for example)

**Comment by MiltonLn** [comment]
Some logic like what? Adding a superuser? adding auth groups? sending an email?

**Comment by MiltonLn** [comment]
You can follow a simple way:

For example, if you are creating your tenant with a form you can go this:
```python
tenant = form.save(commit=False)
# Add some data to the tenant 
tenant.data1 = "value"
tenant.data2 = "value"
# Save the tenant
tenant.save()
# Create the domain
Domain.objects.create(domain="tenant.example.com", tenant=tenant)

# Here your tenant is already created and migrated, you can go this way:
with tenant:
    # Inside here you can execute all kind of methods that touch your database and all will be saved to the tenant schema
    create_auth_groups()
    create_custom_users()
```

Hope this helps.

**Comment by MiltonLn** [comment]
If this is the answer you are looking for, please close the issue.

**Comment by perrohunter** [comment]
it did! thanks!
