### ISSUE TITLE
How have default tenant for main site?

### ISSUE THREAD

**Issue by mamcx** [tomturner/django-tenants#127]
I have a customer that wanna resell his app. For 'main.com' I wish to use his own tenant and only use 'tenant1.main.com' for his customers. This only need a way to say 'main.com' = 'master.main.com'

**Comment by tomturner** [comment]
@mamcx don't quite understand the question as this is what this project allows you to do

**Comment by mamcx** [comment]
Yeah, but I need to make a subdomain for the main customer.

**Comment by krdeepak** [comment]
schema name is separate from domain name (which can be without subdomain or use multiple domains). Check 2nd page of tutorial.
