### ISSUE TITLE
Django tenants test case for public schema

### ISSUE THREAD

**Issue by ambengeri** [tomturner/django-tenants#129]
Setup test cases for my Django Tenants based system. Working perfectly with tenant test cases. 404 status code is returned when hit on URL which is allowed only in PUBLIC schema. I tried with TenantTestCase, and django TestCase, Django Rest Framework APIClient as well. All returning same status code.According to previous issues, I had read that if we want to carry out tests on PUBLIC schema, then just use other test client and not TenantTestCase. It is not able to find the URL.

      class AccountsTest(TestCase):

             def test_register_user_api(self):
             response = self.client.get(reverse('app_name:register'))
             self.assertEqual(response.status_code, 200)

**Comment by MiltonLn** [comment]
Hello @ambengeri i have ran with the same problem.

I don't remember the full technical explanation but it seems that the `reverse` method always runs with the `settings.ROOT_URLCONF` which represents the tenants urls in django-tenants, it doesn't matter if you use `TenantTestCase`, `TestCase` or whatever.

My final solution was to build two methods, and i built two of them to give some clarity to my code. They are as follows:

```
def public_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    You must to use this for public urls
    """
    return reverse(viewname, urlconf=settings.PUBLIC_SCHEMA_URLCONF, args=args, kwargs=kwargs, current_app=current_app)


def tenant_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    You must to use this for tenant urls
    """
    return reverse(viewname, urlconf=settings.ROOT_URLCONF, args=args, kwargs=kwargs, current_app=current_app)
```

So with that methods you can avoid your present problem.
I think most of people using django-tenants haven't noticed this because they test their views accessing directly to `view.as_view()`directly rather than reversing the urls, but i like to reverse urls to test if they are built correctly.

Hope this helps and if so, please close the issue.

**Comment by ambengeri** [comment]
`
            Traceback (most recent call last):
             File "../test/utils.py", line 205, in inner
             return func(*args, **kwargs)
             File "../tests.py", line 140, in test_register_user_api
             response = self.client.get(self.public_reverse('app_name:register-user'))
             File "../tests.py", line 129, in public_reverse
    current_app=current_app)
  File "../django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "../django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'test_register_user_api (app_name.tests.BaseSetup)' with arguments '('a', 'p', 'p', '_', 'n', 'a', 'm', 'e', ':' 'r', 'e', 'g', 'i', 's', 't', 'e', 'r')' and keyword arguments '{}' not found. 0 pattern(s) tried: []
`
This is the output when I pass reverse url. It is splitting my view name into separate characters. This is my code:
`   


    def test_register_user_api(self):
            response = self.client.get(self.public_reverse('app_name:register'))
            self.assertEqual(response.status_code, 200)
`

**Comment by MiltonLn** [comment]
@ambengeri you must not create the custom reverse methods inside the Test Class because this is passing self as first argument, and that's the viewname.

Try putting it as an utility method outside a class.

**Comment by ambengeri** [comment]
Yes. I think this may have solved the issue. 

I guess you need to put this in documentation.

Thanks. Closing the issue.

**Comment by ambengeri** [comment]
This is my testcase:

    @override_settings(task_eager_propagates=True, task_always_eager=True, broker_url='memory://', backend='memory')
    def test_user_verfication_api(self):
             register_user = self.c.post(public_reverse(('app_name:register-user')),data=
                                        {'email': 'xxx@xxx.com', 'mobile_number': '1234'}) #this post is working fine and on successful post, I create a row in Confirm table, and store a random variable in that.
             confirm_obj = Confirm.objects.get(email='xxx@xxx.com', mobile_number='1234')
             user_ver_request = self.c.post(public_reverse('app_name:user-verification'),{'password': 'dummy', 'first_name': 'x', 'last_name': 'x','email': 'xxx@xxx.com', 'mobile_number': '1234','random':''+str(confirm_obj.random)}) #user-verification is an API which will accept a POST only when the schema is Public.
             self.assertEqual(user_ver_request.status_code, 201)

This is what I get:
    SchemaError: Schema must be public for UserProfileManager user creation

**Comment by MiltonLn** [comment]
Are you inheriting from `TestCase`? if so, why are you doing `connection.set_schema_to_public()` if it's supossed that `TestCase` runs on public tenant. On the other hand you can try doing this:

```
with TenantModel(schema_name='public'):
    user_ver_request = self.c.post(public_reverse('app_name:user-verification'),{'password': 'dummy', 'first_name': 'x', 'last_name': 'x','email': 'xxx@xxx.com', 'mobile_number': '1234','random':''+str(confirm_obj.random)})

**Comment by ambengeri** [comment]
Now, I inherited  _TestCase_. Code looks like this:

    class PublicSetup(TestCase):
             def test_user_verfication_api(self):
                   register_user = self.client.post(public_reverse(('app_name:register-user')),data=
                                        {'email': 'xxx@xxx.com', 'mobile_number': '1234'})
                   confirm_obj = Confirm.objects.get(email='xxx@xxx.com', mobile_number='1234')
                   user_ver_request = self.client.post(public_reverse('app_name:user-verification'),{'password': 'dummy', 'first_name': 'x', 'last_name': 'x','email': 'xxx@xxx.com', 'mobile_number': '1234','random':''+str(confirm_obj.random)}) #user-verification is an API which will accept a POST only when the schema is Public.
         self.assertEqual(user_ver_request.status_code, 201)

and the error is:
     [public:]WARNING 2017-06-10 05:27:41,930 Not Found: /api/app_name/register_user/

**Comment by MiltonLn** [comment]
Hello, 

Can you show me your public and tenant URLConfs?

**Comment by ambengeri** [comment]
Hi,

    ROOT_URLCONF = 'project_name.urls'
    PUBLIC_SCHEMA_URLCONF = 'project_name.urls_public'

This is urls_public.py:
                      from django.conf.urls import url,include
                      urlpatterns = [
	                 url(r'^api/app_name/', include('app_name.urls')),   
                       ]

This is urls.py:
     urlpatterns = [
              url(r'^api/app_name/', include('app_name.urls')),
               url(r'^api/app_name1/',include('app_name1.urls')),
     ]

This is app_name.urls:
      urlpatterns = [
               url(r'^register_user/$', registeruser_list, name='register-user'),
      ]

**Comment by ambengeri** [comment]
I am observing a fact that, the schema is not shifting to public so that I can make a POST request on a URL which will only create a row if the schema is public. Anyway to get around this? `TenantTestCase` client I am using, and using the `public_reverse` method as well.

**Comment by ambengeri** [comment]
Hi,
```
TenantModel = get_tenant_model()
org = TenantModel.objects.get(schema_name='public')
print(org.schema_name) #this is returning public
```
After this I am posting data on a URL which will create a User only if schema is Public. But I am getting this error:
```
SchemaError: Schema must be public for UserProfileManager user creation
```

**Comment by MiltonLn** [comment]
Hello @ambengeri, my last solution is this:

Try creating a custom `TestCase` for public tenant, and use `public_reverse` inside that.

code is as follows:

```
class PublicTenantTestCase(TenantTestCase):
    @staticmethod
    def get_test_tenant_domain():
        return 'test.com'

    @staticmethod
    def get_test_schema_name():
        return 'public'
```
now use this in your tests that involve rendering urls from public urlconf instead of using `TestCase`

**Comment by ambengeri** [comment]
Hi @MiltonLn ,

This too aint working. It is not shifting to Public schema and hence it is not allowing to post.
Can few other people come in and look at this? @tomturner

**Comment by tomturner** [comment]
@ambengeri Have a look at the latest commit i have done

**Comment by ambengeri** [comment]
@tomturner It is working. Thanks.

**Comment by rehbarkhan** [comment]
I tried the above method, but still getting 404 

view_service_layer.py
```python
from django.conf import settings
from django.shortcuts import render
from django.urls import reverse


def render_view(request):
    if settings.DEBUG:
        return render(request, 'vue.html')
    else:
        return render(request, 'ui/dist/index.html')
    

def public_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    You must to use this for public urls
    """
    return reverse(viewname, urlconf=settings.PUBLIC_SCHEMA_URLCONF, args=args, kwargs=kwargs, current_app=current_app)


def tenant_reverse(viewname, args=None, kwargs=None, current_app=None):
    """
    You must to use this for tenant urls
    """
    return reverse(viewname, urlconf=settings.ROOT_URLCONF, args=args, kwargs=kwargs, current_app=current_app)
```

 test case
```python
from rest_framework.test import APIClient
from django.test import TestCase
from django.contrib.auth.models import User
from .view_service_layer import public_reverse
# Create your tests here.


class TestClient(TestCase):
        
    def setUp(self):
        User.objects.create_user(username='test', password='test')
        self.client = APIClient()
    
    def test_get_clistlist_without_authentication(self):
        """
        Try to fetch client list without authetnication
        """
        url = public_reverse('main_app:Client-list')
        res = self.client.get(url)
        self.assertEqual(res.status_code, 401)
```

public url conf
```python
from django.urls import path, re_path, include
from rest_framework.routers import DefaultRouter
from .api import views
from django.apps import apps

app_name = 'main_app'


routers = DefaultRouter()

for model in apps.get_app_config('main_app').get_models():
    model_name = str(model._meta.object_name)
    routers.register(
        r'{}'.format(model_name),
        getattr(views, model_name),
        basename=model_name
    )

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('account/signin/', views.SignIn.as_view(), name='sigin'),
    path('api/', include(routers.urls)),
    re_path(r'app/', views.App.as_view(), name='app')
]
```

still I am getting 404 , I should be getting 401
```
~/src $ django-admin test --keepdb --settings=config.settings
Found 1 test(s).
Using existing test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory '/home/app/src/templates/ui/dist/assets' in the STATICFILES_DIRS setting does not exist.

System check identified 1 issue (0 silenced).
[WARNING] 2026-02-28 11:03:30,666 django.request - Not Found: /api/Client/
F
======================================================================
FAIL: test_get_clistlist_without_authentication (main_app.tests.TestClient.test_get_clistlist_without_authentication)
Try to fetch client list without authetnication
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/src/main_app/tests.py", line 20, in test_get_clistlist_without_authentication
    self.assertEqual(res.status_code, 401)
AssertionError: 404 != 401

----------------------------------------------------------------------
Ran 1 test in 0.175s

FAILED (failures=1)
Preserving test database for alias 'default'...
~/src $ 
```
