### ISSUE TITLE
can't import get_template_from_string

### ISSUE THREAD

**Issue by juanefren** [tomturner/django-tenants#13]
Hi, I am trying to make my project work with django_tenants but running any request I get:
ImportError at / cannot import name get_template_from_string
django_tenants/template_loaders.py line 10

Searched about this and found that get_template_from_string was removed in django 1.8
https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#get-template-from-string

Any ideas about this problem?

**Comment by tomturner** [comment]
Thanks for that. I have done a fix however it hasn't been tested yet.

**Comment by juanefren** [comment]
Thanks for the fix now I get:
AttributeError at /
'Client' object has no attribute 'domain_urls'

Here is the complete traceback:
http://pastebin.com/qKFeRmY6

**Comment by tomturner** [comment]
@juanefren Sorry about that. I have put a small fix in however I still haven't check it. I will check it tomorrow.

Tom

**Comment by juanefren** [comment]
It appears it is working properly now, thank you!
