### ISSUE TITLE
Very slow query execution in shell (after tenant.activate) or on the webiste.

### ISSUE THREAD

**Issue by krdeepak** [tomturner/django-tenants#133]
I have a simple query to get data to be used in dashboard. It has few heavy queries but run in 2-3 seconds in normal mode. 
After I moved to multi-tenant it is taking 30 seconds or more for the same query. I activate the tenant (using tenant.activate) in django shell and then run the function.

Am I missing something? This makes the app unusable.

**Comment by MiltonLn** [comment]
Please can you try doing

```
with tenant:
    # run queries
```

Instead of `tenant.activate`? please tell me if that fixes your problem

**Comment by krdeepak** [comment]
No, still the same problem. The multitenant app takes 10x to 30x more time than normal django app.

**Comment by krdeepak** [comment]
This was due to AWS RDS performance issue, not due to tenant specific queries.
