### ISSUE TITLE
Client model does not exist in the project

### ISSUE THREAD

**Issue by pvagare** [tomturner/django-tenants#136]
class BaseSetup(TenantTestCase):

    def setup_tenant(self, tenant):
        """
        Add any additional setting to the tenant before it get saved. This is required if you have
        required fields.
        """
        # deleting the best power of life that you would
        tenant.company_name = "Test Company"

    def setup_domain(self, tenant):
        """
        Add any additional setting to the domain before it get saved. This is required if you have
        required fields.
        """
        domain.ssl = True

    def setUp(self):
        super(BaseSetup, self).setUp()
        self.c = TenantClient(self.tenant)

    def test_user_profile_view(self):
        response = self.c.get(reverse('userprofile'))
        self.assertEqual(response.status_code, 200)

    @staticmethod
    def get_test_tenant_domain():
        return 'a.test.com'

    @staticmethod
    def get_test_schema_name():
        return 'a'`
`
I have written above code for test case for testing the user profile, but i get the following error even though I have client model class into the core application,

 "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'core' doesn't have a 'client' model.

Please let me know answer of above question.

Thank you in advance ! :)

**Comment by tomturner** [comment]
Are you using the latest from GIT or pypi?

**Comment by pvagare** [comment]
I am using pypi.

**Comment by tomturner** [comment]
Try using the latest in git
