### ISSUE TITLE
django_tenants.files appears to be missing from PyPI

### ISSUE THREAD

**Issue by jordanmt** [tomturner/django-tenants#145]
While configuring tenant-specific media files, I ran into 500 errors while trying to upload files, that I first thought were related to my development server setup.

But my logs were complaining about being unable to find django_tenants.files.storages.TenantFileSystemStorage, i.e.:
 `ImportError: No module named 'django_tenants.files'`

Which led me to realize that django_tenants.files was not in my django-tenants package (installed via pipenv to my virtualenv). I was able to manually add the directory and file to site-packages/django_tenants, and resolve the error. It seems that the file is simply missing from the 1.3.3 release.

**Comment by tomturner** [comment]
Fixed in 1.3.4 and 2.0.0
