### ISSUE TITLE
delete tenants with queryset method doesn't delete their schemas

### ISSUE THREAD

**Issue by hugobessa** [tomturner/django-tenants#149]
The model delete method works properly, but if you call the queryset method nothing happens to the schemas.

These are the models related to tenants in the project that I'm having the issue:

```python
class Client(TenantMixin):
    name = models.CharField(max_length=100)
    created_on = models.DateField(auto_now_add=True)

    # default true, schema will be automatically created and synced when it is saved
    auto_drop_schema = True
    auto_create_schema = True

class Domain(DomainMixin):
    pass
```

This in the code I'm using to reproduce the issue:

```python
clients = Client.objects.all()
for c in clients:
    c.delete()  # this deletes the tenant model and the schema

Client.objects.all().delete()  # this deletes only the tenant model, not the schema
``` 

OBS.: Also tried setting `AUTO_DROP_SCHEMA` in django settings, but it also didn't work.

**Comment by tomturner** [comment]
@hugobessa What version of Django are you using

**Comment by hugobessa** [comment]
Django 1.11, @tomturner

**Comment by hugobessa** [comment]
and the latest version of django-schemas!

**Comment by gilsonbp** [comment]
Has anyone been able to delete the eschemas automatically? I am in Django 2.x and it also does not work, I delete a Client but Schema remains.

**Comment by scardine** [comment]
As explained [here](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#delete) the delete method from the queryset object doesn't call delete() method on each item but it DOES calls signals. I will do some research on how signals work regarding inheritance and try to send a PR moving the logic from the delete method to an implementation using signals.

**Comment by coler-j** [comment]
Any luck with that @scardine ?

**Comment by pauloscardine** [comment]
> Any luck with that @scardine ?
Thanks for mentioning, I totally forgot about this. It should be a small patch, will try to get it done this weekend.

**Comment by coler-j** [comment]
@pauloscardine do you have this fix on a public repo anywhere? If not, we are going to take stab at it an PR.

**Comment by scardine** [comment]
@coler-j can you test https://github.com/scardine/django-tenants ?
I was not able to run tests on my local environment (something about python 3.4 incompatibilities) and don't have time right now to fix it.

**Comment by scardine** [comment]
I think we still need the callback for the manager method. This test is failing.

```
class TenantManagerMethodsTestCaseTest(BaseTestCase):
    """
    Tests manager's delete method.
    """
    def test_manager_method_deletes_schema(self):
        Client = get_tenant_model()
        Client.auto_drop_schema = True
        tenant = Client(schema_name='test')
        tenant.save()
        self.assertTrue(schema_exists(tenant.schema_name))

        domain = get_tenant_domain_model()(tenant=tenant, domain='something.test.com')
        domain.save()

        Client.objects.filter(pk=tenant.pk).delete()
        self.assertFalse(schema_exists(tenant.schema_name))
```

**Comment by scardine** [comment]
The callback could be something like this:
```
@receiver(post_delete)
def tenant_delete_callback(sender, instance, **kwargs):
    if not isinstance(instance, get_tenant_model()):
        return

    if instance.auto_drop_schema and schema_exists(instance.schema_name):
        instance._drop_schema(True)
```
In fact we could remove the `drop_schema` method from the `delete` implementation and leave it to signals.

**Comment by tomturner** [comment]
@scardine when I tried it with that callback it never got called. Travis is saying all tests have passes.

**Comment by scardine** [comment]
Mind you, my first implementation was flawed. I was testing `isinstance(sender, ...)` where I should be doing `isinstance(instance, ...)`.

**Comment by tomturner** [comment]
Yes your merge should of work I will look tomorrow

**Comment by gnalbandian** [comment]
What's the status on this?

**Comment by pauloscardine** [comment]
> What's the status on this?

Can you try the PR and report back here?
