### ISSUE TITLE
PyPi update?

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#151]
Hi,

I noticed that this repo's version is at 2.0 in [this](https://github.com/tomturner/django-tenants/blob/master/setup.py) file. But when I check [PyPi](https://pypi.python.org/pypi/django-tenants/1.3.3)  I see it's stuck to 1.3.3.

When do you guys plan on updating the PyPi repo?

Thanks,

**Comment by bartmika** [comment]
For now I'll use ``pip install git+https://github.com/tomturner/django-tenants`` but I would prefer to have it available in PyPi as soon as possible.

**Comment by rodolfomartinez** [comment]
Massive +1

**Comment by tomturner** [comment]
I have been testing it before I release it. I will try and upload to pypi within a few days

**Comment by tomturner** [comment]
Done
