### ISSUE TITLE
DefaultTenantMiddleware

### ISSUE THREAD

**Issue by Guest007** [tomturner/django-tenants#154]
As I understand in DefaultTenantMiddleware you want to override get_tenant() method? 
For now there is get_domain() and it is not work properly.
https://github.com/tomturner/django-tenants/blob/40e549a89fc1783ce02e736b1615cbd0a3918958/django_tenants/middleware/default.py#L17

Am I right?

**Comment by tomturner** [comment]
What error are you getting

**Comment by Guest007** [comment]
The same behavior as with SuspiciousTenantMiddleware. But if rename method `get_domain` to `get_tenant` - it will work rigth.
