### ISSUE TITLE
Error when I try to use template based on tenants, on Django 2.0.2

### ISSUE THREAD

**Issue by moacirmoda** [tomturner/django-tenants#158]
In django 2.0.2 i have found this error:

```
'FilesystemLoader' object has no attribute 'get_contents'
```

This error occur when I try to use templates based on tenant.

The documentation is deprecated, so I've searched new solutions, until I got this:
```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'loaders': [
                'django_tenants.template_loaders.FilesystemLoader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MULTITENANT_TEMPLATE_DIRS = [
    'tenant/templates/%s',
]
```

Can anyone help me to find if there is anything wrong with my configurations?

**Comment by moacirmoda** [comment]
Apparently I do some workaround that seems to work. I created a class that based on `FilesystemLoader` inserting `get_contents` method (copied from [here](https://github.com/django/django/blob/2.0.2/django/template/loaders/filesystem.py#L21)), and subscribing method `get_template_sources`, that changes the yield to return instead of a `str` object, a `Origin` object (copied from [here](https://github.com/django/django/blob/2.0.2/django/template/loaders/filesystem.py#L42)).

See the whole code:
```python
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured, SuspiciousFileOperation
from django.db import connection
from django.template import TemplateDoesNotExist, Origin
from django.utils._os import safe_join
from django_tenants.postgresql_backend.base import FakeTenant
from django_tenants.template_loaders import FilesystemLoader as TenantFilesystemLoader


class FilesystemLoader(TenantFilesystemLoader):
    def get_contents(self, origin):
        try:
            with open(origin.name, encoding=self.engine.file_charset) as fp:
                return fp.read()
        except FileNotFoundError:
            raise TemplateDoesNotExist(origin)

    def get_template_sources(self, template_name, template_dirs=None):
        """
        Returns the absolute paths to "template_name", when appended to each
        directory in "template_dirs". Any paths that don't lie inside one of the
        template dirs are excluded from the result set, for security reasons.
        """
        if not connection.tenant or isinstance(connection.tenant, FakeTenant):
            return
        if not template_dirs:
            try:
                template_dirs = settings.MULTITENANT_TEMPLATE_DIRS
            except AttributeError:
                raise ImproperlyConfigured(
                    'To use %s.%s you must define the MULTITENANT_TEMPLATE_DIRS' %
                    (__name__, FilesystemLoader.__name__))

        for template_dir in template_dirs:
            try:
                if '%s' in template_dir:
                    name = safe_join(template_dir % connection.tenant.schema_name, template_name)
                else:
                    name = safe_join(template_dir, connection.tenant.schema_name, template_name)

                yield Origin(
                    name=name,
                    template_name=template_name,
                    loader=self,
                )
            except UnicodeDecodeError:
                # The template dir name was a bytestring that wasn't valid UTF-8.
                raise
            except (SuspiciousFileOperation, ValueError):
                # The joined path was located outside of this particular
                # template_dir (it might be inside another one, so this isn't
                # fatal).
                pass
```

I don`t make any PRs because I'm not sure if the problem was solved, but I agree that is a beginning.

**Comment by coler-j** [comment]
I am also experiencing this issue (same error) after adding the template loader for tenant specific templates. Template settings are as follows:

`TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(BASE_DIR, 'templates'),
        ],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
            'loaders': [
                'django_tenants.template_loaders.FilesystemLoader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]

MULTITENANT_TEMPLATE_DIRS = [
    'tenants/%s/templates'
]

`

**Comment by coler-j** [comment]
After reviewing the code `get_contents` definitely does not existing on the `TenantFilesystemLoader` or base loader class. So this is a bug, or something. At leas the settings are currently for Django < 1.8 (where the loader settings was changed)

**Comment by coler-j** [comment]
This fix from `django-tenant-schemas` likely also needs to be merged into this library: https://github.com/bernardopires/django-tenant-schemas/pull/457

**Comment by coler-j** [comment]
Guess we should switch back to `django-tenant-schemas` it seems to be more active now than this fork.

**Comment by tomturner** [comment]
I deleted you comment as it wasn’t true this fork is active

**Comment by jcass77** [comment]
@tomturner, we can probably close this now that #198 has been merged: it provides a new template loader with more detailed configuration documentation.
