### ISSUE TITLE
Accesing tenant schema_name on models layer.

### ISSUE THREAD

**Issue by juanefren** [tomturner/django-tenants#16]
Hi, first of all not sure if "Issues" section is the correct way to post this, since this is not an issue at all just asking an open question for opinions.

I am migrating a django project to django tenants, we have several years working as SaaS in a traditional way using basically one site per customer. 

We put the equivalent to "tenant.schema_name" in settings.py since each customer works on a site with its own settings file so any time I needed to use it I'l just get it from django.conf.settings. How ever since django tenants has this on request it isn't available on models layer.

Our current working solution is to pass schema_name as a parameter every time a model function that needs this info is called, but I am wondering other options about this, for example storing schema_name in the models which need it.

How do you commonly deal with this?

**Comment by tomturner** [comment]
What were you migrating from was it django_tenant_schemas?
I personal can't see you need to store the schema_name more than once. Can you give an example please?

**Comment by ivome** [comment]
Do you want to get the current tenant? 
Something like this?

````
from django.db import connection
current_tenant = connection.tenant
```

**Comment by juanefren** [comment]
No, I haven't used postgresql schemas at all before, I work for a SaaS company where each customer has it's own site/database/subdomain customer management is run by automated scripts (altering databases, creating new customers, etc...) Everything has worked that way since we started about 6 years ago, but now we realize we NEED to lower our memory consumption since our profitability is lower than we expected, for example with less than 100 customers we need a 64GB memory for our application server and still we have less than 90 sites running. Looking for solutions we found django_tenant_schemas and django_tenants so we are basically just starting to migrate.

....At the moment of writting this Ivome response just popped up, apparently that is exactly what I need, thanks :)
