### ISSUE TITLE
Superuser does not have permissions

### ISSUE THREAD

**Issue by Jromero97** [tomturner/django-tenants#160]
I create a superuser in Django Tenants, first works pretty good, but I make a modification in admin site to have my tenant app separated from public tenant, now when I try to view any tenant admin site told me that Superuser does not have permissions to edit anything! 

Someone with similar problem? I need some help!

Thanks a lot!

**Comment by tomturner** [comment]
You need to explain how you got your site setup. IE have you got your users in every Tenant or just in the public tenant

**Comment by gilsonbp** [comment]
I have the same problem. A public user does not have access to the data of the tenants? In my case I tried to add my user module to Public Apps and Private Apps but even so my public Admin does not have access to a Tenant's data.

**Comment by Jromero97** [comment]
I had only in the public tenant my auth user table, @gilsonbp if you put in both shared and tenant apps what you doing is creating a table auth user for every schemas, so if you create an user in public schema you don't have access in the tenant schemas cause you have other table and your users don't be created yet.

**Comment by gilsonbp** [comment]
@Jromero97 True, the vacation I was adopting with tenant-only permissions was not working well.

**Comment by marimuthuinchennai** [comment]
> I create a superuser in Django Tenants, first works pretty good, but I make a modification in admin site to have my tenant app separated from public tenant, now when I try to view any tenant admin site told me that Superuser does not have permissions to edit anything!
> 
> Someone with similar problem? I need some help!
> 
> Thanks a lot!

The same issue for my self also whether you solved this issue and how you handle individual tenant view with restriction from public tenants

**Comment by ishtiaque06** [comment]
> I create a superuser in Django Tenants, first works pretty good, but I make a modification in admin site to have my tenant app separated from public tenant, now when I try to view any tenant admin site told me that Superuser does not have permissions to edit anything!
> 
> Someone with similar problem? I need some help!
> 
> Thanks a lot!

I've been trying to do this as well. So essentially, I want a superuser account that can access all data in **all** tenants. Right now, the way I have my project setup, all my users only have tenant-specific permissions and authenticaion (i.e. superuser with `schema=public` has permission on `www.example.com` but not on `tenant1.example.com`, which makes sense, but is kindof useless because on the public schemas I'd prefer to have only global admins of the whole project, and whenever someone else tries to log in/sign up, they will automatically be redirected to a specific tenant). I feel like this is a vital part of having multi-tenancy in SaaS apps because we the developers would prefer it if we could access all the tenants from one account that has privileges above all other accounts in our project.

**Comment by marimuthuinchennai** [comment]
> > I create a superuser in Django Tenants, first works pretty good, but I make a modification in admin site to have my tenant app separated from public tenant, now when I try to view any tenant admin site told me that Superuser does not have permissions to edit anything!
> > Someone with similar problem? I need some help!
> > Thanks a lot!
> 
> I've been trying to do this as well. So essentially, I want a superuser account that can access all data in **all** tenants. Right now, the way I have my project setup, all my users only have tenant-specific permissions and authenticaion (i.e. superuser with `schema=public` has permission on `www.example.com` but not on `tenant1.example.com`, which makes sense, but is kindof useless because on the public schemas I'd prefer to have only global admins of the whole project, and whenever someone else tries to log in/sign up, they will automatically be redirected to a specific tenant). I feel like this is a vital part of having multi-tenancy in SaaS apps because we the developers would prefer it if we could access all the tenants from one account that has privileges above all other accounts in our project.

yes you need to register your sub domain in hosts then only it will works

**Comment by ishtiaque06** [comment]
@marimuthuinchennai I already do that. I think you misunderstood my question. I want a global superuser who has access to everything in my app (i.e. all the data in all subdomains).

**Comment by tomturner** [comment]
If you have your users defined in each tenant and a super user in the public. The super user will not have access to each tenant. One of the reasons for this is the if for the public user ID will clash with a tenant user. To get round the problem create a super user on each tenant or look at https://github.com/Corvia/django-tenant-users/blob/master/README.rst

**Comment by marimuthuinchennai** [comment]
> > @marimuthuinchennai I already do that. I think you misunderstood my question. I want a global superuser who has access to everything in my app (i.e. all the data in all subdomains).
> 
> oh yes sorry, if you want to access all app data in public schema to private schema you can be able to handle only through user models please refer PostgreSQL schema privileges public schema to tenant schema and as well as tenant schema to public schema

Thanks for your reply, I quite outside, I completed the task the same way as you mentioned
