### ISSUE TITLE
Getting Error while creating domain names even though schemas been created fine.

### ISSUE THREAD

**Issue by ramukodandapuram** [tomturner/django-tenants#170]
Hi, 
I am sorry to asking this, I have been  implementing rest api for registering tenants for that created models same as[ django-tenants](https://github.com/tomturner/django-tenants/blob/master/docs/use.rst) right after then inserting data from browser instead using shell. you can find out code below
`
from customers.models import Client,Domain

class RegisteringTenants(APIView):

    def post(self,request,format=None):

        default_domain = '.example.com'
        try:
            serializer = ClientSerializer(data=request.data)
            if serializer.is_valid():
                serializer.save()
                domain = Domain()
                domain.domain = request.data['schema_name'] + default_domain
                domain.tenant=serializer
                domain.is_primary=True
                domain.save()
                return Response(serializer.data,status=status.HTTP_201_CREATED)
            
        except DatabaseError:
            raise Http404
`
above code been able to create schemas for tenants but was failing to add record which contains domain names for respective schema in it's child table(Domain table), actually I have no idea that which value to assign 

**domain.tenant = serializer**

`
class Client(TenantMixin):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    created_on = models.DateField(auto_now_add=True)

class Domain(DomainMixin):
    pass
`
once schemas was created getting error like **<UniqueValidator(queryset=Client.objects.all())>])": "Domain.tenant" must be a "Client" instance.**   
any reply can be helpful. 
Thanks in Advance

**Comment by kosz85** [comment]
Check what you assigned to `domain.tenant`, I guess this is djangorestframework, so you assigned serializer instance to domain.tenant, not tenant object :)
You are probably facepalming right now :D Have a nice day!

**Comment by ramukodandapuram** [comment]
yes you @kosz85 are right, I was not assigning tenant object to  `domain.tenant` in fact having no idea, getting confused with here I was saving serialized data , where in  [django_tenants](https://django-tenants.readthedocs.io/en/latest/use.html)  doing this way
`
from customers.models import Client, Domain
tenant = Client(schema_name='public',
                name='Schemas Inc.',
                paid_until='2016-12-05',
                on_trial=False)
tenant.save()

domain = Domain()
domain.domain = 'my-domain.com' 
domain.tenant = tenant
domain.is_primary = True
domain.save()
`

one thing please tell me how to assign  `tenant object `  to  `domain.tenant` and how can I get current saving object at very instant.

**Comment by ramukodandapuram** [comment]
thank you @kosz85 issue got resolved. Thank you so much!!
