### ISSUE TITLE
django.contrib.contenttypes: shared vs tenants

### ISSUE THREAD

**Issue by lorinkoz** [tomturner/django-tenants#171]
I've noticed that all models are registered as content types regardless of whether `django.contrib.contenttypes` is in `SHARED_APPS`, `TENANT_APPS`, or in both. I read a comment from @kosz85 a few days ago stating (maybe not with this exact words) that it would be best if content types are placed in `SHARED_APPS` alone. Diving into the code I've found some defensive code for weird behavior in content types, such as `middleware/main.py` on line 53 `ContentType.objects.clear_cache()` with a long explanation about content type separation in shared and tenant schemas. In the documentation I see that the example encourages to have `contenttypes` on both `SHARED_APP` and `TENANT_APPS`.

In my code, I've tested both cases. All work fine. I even removed `contenttypes` from `TENANT_APPS` and the existing schemas continued to work fine, while the new schemas were properly mapped against the `public` schema holding the content types table (as all models were registered on all tables anyways.)

My proposal:
1. Remove defensive code, as all content types are registered on every content type table.
2. Officially suggest that content types be kept in `SHARED_APPS` only, as it's more clear and less prone to confusion.

**Comment by lorinkoz** [comment]
This is just an idea, if you find it acceptable I can submit a PR for it.

**Comment by tomturner** [comment]
I don’t mind it changing however It must also work if it is defined in both places

**Comment by kosz85** [comment]
That "defensive" code, could really be run only when `contettypes` are in `TENANT_APPS`, as we are clearing cache so it's crippling performance that way or another. It's also bad idea, as tenant contenttypes table duplicates content of shared table, as well as it may cause some problem if data in both don't match. Like `contenttype.id` of model A in one table have id of model B in other table.
So if we have generic relation in shared table not overwritten in tenant, but our `contenttype` table is overwritten, then our generic object relation would have wrong entries, and would create wrong entries for public schema too.

I had such issue once, so it's proven by my own example of spectacular fail :D

**Comment by lorinkoz** [comment]
Experimenting this in https://github.com/lorinkoz/django-pgschemas
