### ISSUE TITLE
Proposed new setting: SCHEMA_PREFIX

### ISSUE THREAD

**Issue by lorinkoz** [tomturner/django-tenants#172]
Sometimes it's useful to have a common prefix when `Tenant.schema_name` is converted to the actual schema name. It might help avoiding name clashes with other existing schemas, while keeping `Tenant.schema_name` as originally entered for ease of use in tenant commands.

My proposal:
Add a new setting `SCHEMA_PREFIX`, blank by default, which will be prepended to `Tenant.schema_name` for all database schema operations. This setting should comply itself with `SQL_IDENTIFIER_RE` and `SQL_SCHEMA_NAME_RESERVED_RE`, making the resulting concatenation also compliant.

**Comment by lorinkoz** [comment]
This is just an idea, if you find it acceptable I can submit a PR for it.

**Comment by tomturner** [comment]
Am I right you want to have all the schemas prefixed with some characters,

**Comment by lorinkoz** [comment]
Yes, I'd like to retain the ability to use the original schema name when passing as argument of `-s` in `tenant_command` while actually prefixing it with some characters in database.

**Comment by lorinkoz** [comment]
Experimenting this in https://github.com/lorinkoz/django-pgschemas
