### ISSUE TITLE
Invalid HTTP_HOST header: 'tenant.localhost:8000'. You may need to add 'tenant.localhost' to ALLOWED_HOSTS

### ISSUE THREAD

**Issue by NajmathUmmer** [tomturner/django-tenants#173]
I followed the django-tenants doc. But while running this error is showing for all urls. It was working when I did this in my older version of Django using django-tenant-schema.How can I get rid of this?

**Comment by ramukodandapuram** [comment]
change 
`ALLOWED_HOSTS = ['localhost', '.example.com']` in your settings.py file, right after then open
your terminal  and type  ` sudo nano /etc/hosts`  ( assuming you were using OS linux ubuntu ) there you have to define 
`127.0.0.1               example.com 

   127.0.0.1            tenant.example.com`

alternatively you can define simply like 
`127.0.0.1  .example.com`  then run your file.

**Comment by NajmathUmmer** [comment]
I tried it already.It's working with django-tenant-schema But not able to do with django-tenant

**Comment by ramukodandapuram** [comment]
I came to know one point that you were requesting with `tenant.localhost:8000` yes it's working fine with **django-tenant-schemas**. but not with **django-tenants**. really no idea about theory behind it. so you must try with **domain-name** istead **localhost**. lets say example `tenant.domain.com:8000` . I hope it works, have a nice day.

**Comment by ramukodandapuram** [comment]
try with `my-domain.com:8000/admin` , still if it's not working,  define url pattern for admin  in your  **urls_public.py** file `
urlpatterns = [ 
url(r'^admin/',admin.site.urls),
 ]`
apply same for **urls_tenants.py**

**Comment by NajmathUmmer** [comment]
I've included  path('admin/', admin.site.urls), in both urls_public.py and urls_tenants.py.Still showing same error

**Comment by ramukodandapuram** [comment]
The `Site` object for your Django project is missing. Each Django project has a `Site` object which contains the site's name and domain. It is usually automatically created when creating a Django project (in particular, when the syncdb command runs) but in your case it seems that didn't happen
To fix it:
Open the Django shell for your site (`python manage.py shell`).
Type the following:
`
from django.contrib.sites.models import Site

Site.objects.create(name='example.com', domain='example.com')
`

change `SITE_ID = 1` in your settings file

**Comment by NajmathUmmer** [comment]
It all went good.But my admin page is not like the usual Django Admin page.(And also I ran makemigrations and migrate schema shared ).It would be appreciated if You can help me with this too

**Comment by NajmathUmmer** [comment]
I added 'django.contrib.staticfiles', to shared and tenant apps and worked perfectly fine.And Thanks a lot!!!!

**Comment by coler-j** [comment]
Ran into this problem as well. It worked for the public schema, but when trying for a tenant I was getting the site not found error as reported above.

I have NOT added the sites app to the tenant apps, BUT adding `SITE_ID = 1` to settings resolved this.

**Comment by alexk345** [comment]
For me its not working for public_schema. Work well for tenant. created customers and able to see for t1 and t2. But demo.local do not load.
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost


127.0.0.1 t1.demo.local
127.0.0.1 t2.demo.local
127.0.0.1 t3.demo.local
127.0.0.1 www.demo.local
127.0.0.1 demo.local

**Comment by vinous22** [comment]
solved the admin issue by moving   'django.contrib.admin' right under   'tenant_schemas', in Installed and shared Apps.
