### ISSUE TITLE
Ambiguous requirement: Use `psycopg2-binary` or `psycopg2<2.8` instead

### ISSUE THREAD

**Issue by dionyself** [tomturner/django-tenants#174]
hi, i started to get this warnnig.

https://github.com/tomturner/django-tenants/blob/0a5ff14478e44f55ea566d020e0252bb6ca5ac24/setup.py#L50

UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

Users may have problems on versions >=2.8

**Comment by chpmrc** [comment]
Why was this closed? I'm building from master to have compatibility with Django 2.1 and this is a valid complaint.

**Comment by tomturner** [comment]
@chpmrc yes it was a bug however i have fixed the issue
