### ISSUE TITLE
How can I route public schema requests?

### ISSUE THREAD

**Issue by francocorreasosa** [tomturner/django-tenants#175]
When I try to enter into my main domain (without specifiying a tenant) I'm viewing 
> No tenant for hostname "example.com"

But when I go into some tenant (ex: `franco-dev.example.com`) it does work. I have set my `PUBLIC_SCHEMA_URLCONF` to a valid `urls.py` though.

Thanks!

**Comment by tomturner** [comment]
You can do your own version of the middleware then you can override the routing to the correct place. I do this on my project to make 127.0.0.1 route to my demo tenant. Hope this helps

**Comment by francocorreasosa** [comment]
Just found a solution :) I created a "public" schema with the main domain (w/o subdomain) and it recognized it fine. Thank you.
