### ISSUE TITLE
Taking SaaS based on django Tenants into production, expecting 5000 tenants.

### ISSUE THREAD

**Issue by karantank** [tomturner/django-tenants#177]
Hello

I have used django tenants to build a SaaS platform, We currently have more than 80 tenants using the system and the system runs fine, We are now checking that if the system would be scalable enough if the tenants out grew to around 5000. For this we deployed the code on a different server to test the scalability, While performing the migrations it took days to create approximately 1000 tenants with 3 workers running in parallel, we are fine with the time as there won't be a time where we would require such number of creation but the migrations failed in between with leaving partially changed database.  So we ran the migrations again and now the migrations won't go ahead from the failed migrations as it says table already exists so we are stuck. I looked around to find a way to rollback migrations but couldn't find anything.

Is there anyway where I can rollback a migrations for a particular schema? Also is there a better way to roll down migration for a set of schemas like 100 each time, so that I can effectively roll changes to the database in chunks rather than rolling it to all of them at once?  Do you have some strategies to support thousands of tenants?

Thanks!

**Comment by kosz85** [comment]
You can migrate particular schema with `--schema <name>`, but if this migration breaked, and didn't rollback, you have 2 options: fake migration then rollback or manually change DB.

My strategies:
1. Make as little changes as possible.
2. Do not use RunPython, and if you do: all changes make with single sql update, so all actions are at postgres.
3. All python side  data migration do as celery background task.
4. Split migrations that needs data migrations into steps: add new columns, migrate data in background task, migrate code, remove columns.
5. Squash old migrations. (You probably don't need it anyway)

About creating schemas, you can create clean one, copy it and then modify. It should be faster.

**Comment by karantank** [comment]
Thanks for a quick revert.

About your suggestions:
1. We try to reduce the db changes but a new feature request would require us to do such changes, hence for atleast first 500 tenants we expect there would be changes.
2. We have not used RunPython as of yet
3.  Currently there are no data migrations rolled out; They are just db based migrations like creating new fields or tables.
4. This is really helpful and will change my migrations strategy 
5. Squashing migration I have not tried, because I don’t want to mess up my migrations file and it looks very risky, I need to test out the whole process first  so I am not focusing on this now.

Your suggestion about copying schemas, can you please elaborate, I have never done something like this, what happens if I do copy a schema and after that I roll new migrations would that work as normal as it does like a new schema from migrations?

**Comment by kosz85** [comment]
5. Squashing is not risky, it's almost like creating new initial migration. We did it already 2 times, when our migrations started to have 2-3 as second digit.  It's really faster after squashing. If you have no custom migrations, it should go without any problem. But sure, test it.

6. Just copy schema. I extended a little django-tenants, so I have statuses like DELETE, DRAFT, MIGRATING, as so on, so it doesn't break app when upgrading. I'm not doing this, as we don't need to create it that fast, and squashing migrations speed up it enough for us, but in theory you can have DRAFT schema, that you copy, then rename. and just add specific changes in public schema (like Sites, Tenants, etc). That shouldn't be really hard to do.
About new migrations, you just need to also migrate this DRAFT schema used for coping, as any normal existing schema :) It's normal live schema, but hidden from users.
You can achieve copy by pgdump or some fancy postgres script, available in the net :)

**Comment by karantank** [comment]
Thanks @kosz85  for your inputs, I think this would help me in generating the schemas faster without actual migrations being performed. Also I was successful in rolling back the migration with manual db change. I'll continue the scalability testing.

Thanks!
