### ISSUE TITLE
Questions about README

### ISSUE THREAD

**Issue by cdvv7788** [tomturner/django-tenants#180]
What is the difference between this and django-tenant-schemas? If that is documented somewhere, I could not find it.
Could you copy the docs link to the project description? To find it you have to dig it from the readme.

**Comment by tomturner** [comment]
I have answered this on some tickets before. I forked django tenant schemes when it looked like the project was dead. I also didn’t like all the support of all the back versions of django as there where lots of if statements. So the I forked it I tidied a lot of the code. I believe this has been done now. I am using this for a couple of my project. In general there is not much difference now as features will end up in both in the end.

**Comment by cdvv7788** [comment]
Hi @tomturner , thanks for replying.
What I mean is that this could be moved to the readme, so the users can know that and have a clearer view to decide which to use.
I found a couple details from this app that are better documented than on DTS (like the delete tenants bit).
