### ISSUE TITLE
Celery support (?)

### ISSUE THREAD

**Issue by domdinicola** [tomturner/django-tenants#184]
tenant-schemas-celery provide celery support to django-tenant-schema (https://github.com/maciej-gol/tenant-schemas-celery/blob/master/setup.py) 

is there already something similar for django-tenants?

**Comment by tomturner** [comment]
It’s quit easy to add celery support without any additional library. However that library should just work

**Comment by tomturner** [comment]
This has been fixed pin django tenant celery
