### ISSUE TITLE
Heroku with django-tenants 

### ISSUE THREAD

**Issue by allidoisace** [tomturner/django-tenants#185]
I have a really weird situation I cannot seem to figure out. I have not touched my implementation of this package since the beginning of the year and now the functionality ceases to exist on my live heroku server. I currently have a Create Account form on my public tenant which generates a tenant/domain just as the docs do and django-tenants does its auto schema generation. This works correctly on my localhost and have zero problems. **However on my live server**, I proceed to get a `Not Found...The requested URL / was not found on this server.` 

I have a CNAME record on DNSimple which points to a wildcard domain which appears to be working, because I have already have a tenant I made awhile ago that is working at `some-customer.mydomain.com`

I was hoping that there might be some enlightenment as to what I am doing/have done wrong to make this issue occur.

**Comment by Hudeh** [comment]
hello am having same issue using my heroku paid app niot seeming to be working after go through the doc working on localhost perfect. even tried using shell to create client same issues. please i need help added my domain.com still not working.
