### ISSUE TITLE
Run tests without migrations

### ISSUE THREAD

**Issue by CleitonDeLima** [tomturner/django-tenants#186]
It is possible to use this application with [django-test-without-migrations](https://pypi.org/project/django-test-without-migrations/)?

if it is not possible, ideas to perform this way?

**Comment by tomturner** [comment]
I don't think you can use that library without modifying it. Have a look at there source it seem like you could embed it in to your project without modifying to much.

**Comment by CleitonDeLima** [comment]
I'm using [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas).  

I opened this issue here because I believe I could have an answer quickly and the test part is very similar with django-tenants.
Now running the tests without migration, tables are created only in schema public.  
I have little knowledge about tests, I'd like to know how I could run this operation.

(sorry for my english :sweat_smile:)
