### ISSUE TITLE
Super User Logging Problem for Tenants

### ISSUE THREAD

**Issue by marimuthuinchennai** [tomturner/django-tenants#190]
User logging in Successful for public tenant how to create view  for individual tenats I restricted in my django settings app can u have any solution for individual tenant login with separation from other tenants, Here is my settings app

SHARED_APPS = (
    'tenant_schemas',  # mandatory, should always be before any django app
    #'customers', # you must list the app where your tenant model resides in
    'shared',
    #'django.contrib.auth',
    #'django.contrib.contenttypes',
    #'django.contrib.sessions',
    #'django.contrib.messages',
    #'django.contrib.staticfiles',
    #'django.contrib.admin',
    'classroom',
    'river',
    # everything below here is optional
)
TENANT_APPS = (
    #'django.contrib.auth',
    'django.contrib.contenttypes',
    #'django.contrib.sessions',
    #'django.contrib.messages',
    #'django.contrib.staticfiles',
    #'django.contrib.admin',
    #'tenantexample.tenant',
    'classroom',
    'shared',
    'river',
    #'accounts',
    # your tenant-specific apps
)
INSTALLED_APPS = [
    'tenant_schemas',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'classroom',
    'river',
    #'accounts',
    'shared',
]

In this any changes are required please do the need i am struggling in this issue

**Comment by coler-j** [comment]
What is your specific question?

**Comment by tomturner** [comment]
Don't understand the question?

**Comment by marimuthuinchennai** [comment]
> What is your specific question?

I tried to login admin but it shows errors, and now i cleared this issue,
