### ISSUE TITLE
Map / Table of how authentication works based on SHARED_APPS and TENANT_APPS mapping of auth, sessions, and users.

### ISSUE THREAD

**Issue by coler-j** [tomturner/django-tenants#191]
How specifically do you share authentication, users, and sessions between shared + tenant apps?

Currently I have the following setup:

But when I navigate from public tenant space to tenant specific subdomain, then the user becomes anonymous.

I see lots of issues that talk _around_ this topic, but nothing the explicitly lays it out.

Current settings are:
```
SHARED_APPS = (
    'django_tenants',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'my_app.apps.tenant_stores', # Custom defined app that contains the TenantModel. Must NOT exist in TENANT_APPS
    'my_app.apps.users',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.admin',
    ...
)

TENANT_APPS = (
    'django.contrib.admin',
    'django.contrib.contenttypes',
    ...
)
```

I would have though that with this setup (sessions, users, and auth in `SHARED` that when I sign in on the public site, that users permissions would extend to any tenant app subdomains.

Is this addresses / outlined anywhere in the docs?

**Comment by coler-j** [comment]
Found a solution (potentially) in the original django-tenants-schemas library.
Needed to add a `SESSION_COOKIE_DOMAIN = '.example.com'`
https://github.com/bernardopires/django-tenant-schemas/issues/306

**Comment by tomturner** [comment]
@coler-j You can create a PR to add this to the documentation in you want
