### ISSUE TITLE
How to populate schemes after creating the tenants

### ISSUE THREAD

**Issue by marimuthuinchennai** [tomturner/django-tenants#193]
Hi,

I need to redirect and populate after successful login for the user to be directed their own tenant.  please provide what to do next to redirection and populate the particular tenant.

Thanks

**Comment by coler-j** [comment]
@marimuthuinchennai can you be more specific? What are you trying to do? Any code samples?

**Comment by marimuthuinchennai** [comment]
Ya Sure, 

After creating tenant i need to redirect into particular tenant directly and i need to populate my tenant tables based on user login

**Comment by marimuthuinchennai** [comment]
> @marimuthuinchennai can you be more specific? What are you trying to do? Any code samples?

Ya Sure,

After creating tenant i need to redirect into particular tenant directly and i need to populate my tenant tables based on user login

**Comment by marimuthuinchennai** [comment]
> @marimuthuinchennai can you be more specific? What are you trying to do? Any code samples?

from django.db import connection
schema_name = connection.schema_name

from this i can able to populate public schema and similarly how to populate other schemas

**Comment by coler-j** [comment]
Have you read the docs for this project? ([docs](https://django-tenants.readthedocs.io/))

To programmatically create a new tenant you would do the following:

```
from customers.models import Client, Domain

# create your first real tenant
tenant = Client(schema_name='tenant1',
                name='Fonzy Tenant',
                paid_until='2014-12-05',
                on_trial=True)
tenant.save() # migrate_schemas automatically called, your tenant is ready to be used!

# Add one or more domains for the tenant
domain = Domain()
domain.domain = 'tenant.my-domain.com' # don't add your port or www here!
domain.tenant = tenant
domain.is_primary = True
domain.save()
```

Once that tenant is created you could redirect to a URL / subdomain for the newly created tenant/schema.

You can also act directly on a tenant schema with the following util:

```
from django_tenants.utils import tenant_context

with tenant_context(tenant):
    # All commands here are ran under the schema from the `tenant` object

# Restores the `SEARCH_PATH` to its original value
```

[- util reference](https://django-tenants.readthedocs.io/en/latest/use.html#tenant_context)

**Comment by tomturner** [comment]
I populate my database using celery with a couple of signals. tThe signal are called 'post_schema_sync'  and 'post_schema_sync'

**Comment by marimuthuinchennai** [comment]
> Have you read the docs for this project? ([docs](https://django-tenants.readthedocs.io/))
> 
> To programmatically create a new tenant you would do the following:
> 
> ```
> from customers.models import Client, Domain
> 
> # create your first real tenant
> tenant = Client(schema_name='tenant1',
>                 name='Fonzy Tenant',
>                 paid_until='2014-12-05',
>                 on_trial=True)
> tenant.save() # migrate_schemas automatically called, your tenant is ready to be used!
> 
> # Add one or more domains for the tenant
> domain = Domain()
> domain.domain = 'tenant.my-domain.com' # don't add your port or www here!
> domain.tenant = tenant
> domain.is_primary = True
> domain.save()
> ```
> Once that tenant is created you could redirect to a URL / subdomain for the newly created tenant/schema.
> 
> You can also act directly on a tenant schema with the following util:
> 
> ```
> from django_tenants.utils import tenant_context
> 
> with tenant_context(tenant):
>     # All commands here are ran under the schema from the `tenant` object
> 
> # Restores the `SEARCH_PATH` to its original value
> ```
> [- util reference](https://django-tenants.readthedocs.io/en/latest/use.html#tenant_context)

Thank you for your Repsonse

**Comment by marimuthuinchennai** [comment]
> I populate my database using celery with a couple of signals. The signal are called 'post_schema_sync' and 'post_schema_sync'

Hi tom, 

can u able to provide the link to use celery

Thanks

**Comment by kosz85** [comment]
You should just run the same code to create tenant in celery task. That's all, no magic links for simple tasks. Tenant creation can be longer then request, that's why we are doing it as background task. You can't redirect user directly to not existent tenant, so you will need to implement some kind of waiting page, that will check with ajax calls, if `Tenant` is ready, and when it's created redirect to it.

**Comment by marimuthuinchennai** [comment]
> You should just run the same code to create tenant in celery task. That's all, no magic links for simple tasks. Tenant creation can be longer then request, that's why we are doing it as background task. You can't redirect user directly to not existent tenant, so you will need to implement some kind of waiting page, that will check with ajax calls, if `Tenant` is ready, and when it's created redirect to it.

Sorry I went out for Vacation thanks for your reply
