### ISSUE TITLE
How to run script on all tenants?

### ISSUE THREAD

**Issue by serbboy23** [tomturner/django-tenants#194]
I have serialized data unique to each tenant, and if I update how my serializer works, I don't want to individually go into each tenant with tenant_command shell and then run the script to update that tenants serialized data. Am I able to run my script from one place and have it do what it needs to do to each tenant?

Thank you

**Comment by allidoisace** [comment]
I would like to know as well.

**Comment by kosz85** [comment]
You can write such script, that iterates over multiple tenants. Just normal `for tenant in tenants:` loop with `with tenant:` block were you do whatever you want, for example call command.

**Comment by allidoisace** [comment]
We can definitely close this @tomturner @serbboy23
