### ISSUE TITLE
When are you going to release v2.1.0 ?

### ISSUE THREAD

**Issue by atodorov** [tomturner/django-tenants#195]
Hi @tomturner,
I see the latest devel version supports Django 2.1.2 which is what I have already. Just wondering when are you planning to release a new version ? 

Are there any particular blockers for a new release? If yes, which ones, maybe I can help with a poull request.

Thanks.

**Comment by jcass77** [comment]
Not sure if it is a blocker, but static file handling appears to be broken for Django > 2.0. See: #197.

**Comment by rodolphopivetta** [comment]
it would be great to see this release on pypi, looks the #197 was solved.

**Comment by bartmika** [comment]
Would love to see this as well.

+1

**Comment by rodolfomartinez** [comment]
+1

**Comment by tomturner** [comment]
Done
