### ISSUE TITLE
how to query a tenant specific app's object?

### ISSUE THREAD

**Issue by develpmentbegins** [tomturner/django-tenants#208]
How do i write orm query to get an grab one object of a class that is registered as tenant specific app. 

As in then tenant tutorial you have class TableOne classs in tenant_only app.
now how do i get the first instance of this class. 
i am getting error while trying it as TableOne.objects.first()
Please help me! Thank you

**Comment by coler-j** [comment]
... what error are you getting? Provide a code sample.

**Comment by bartmika** [comment]
```
from django.db import connection # Used for django tenants.

# I am assuming you are in the main public tenant.
connection.set_schema_to_public() # Switch to Public. 

# Here is how you switch to a different tenant.
connection.set_schema("the-schema-name-of-your-tenant", True) # Switch to Tenant.        

# You are now in the tenant you want, therefore any call you make will be made from that db schema.

# Therefore making this call is all you need after.
object = TableOne.objects.first()
```

If you want to see actual code, feel free to look here: https://github.com/over55/workery-django/blob/master/workery/shared_etl/management/commands/update_away_logs.py
