### ISSUE TITLE
tox support

### ISSUE THREAD

**Issue by domdinicola** [tomturner/django-tenants#210]
Do you think would be appreciated if I add tox here in order to test django-tenants against different django version 2.0/2.1/2.2?

**Comment by tomturner** [comment]
At the moment I only support 2.0 and 2.1 once 2.2 is out I will drop support for 2.0

**Comment by jcass77** [comment]
Just a reminder that Django 2.0 was the last version to support Python 3.4 - so we can probably drop support for that as well.

**Comment by tomturner** [comment]
I know test different version of django
