### ISSUE TITLE
Help needed: Run collectstatic_schemas once a tenant is created by admin interface

### ISSUE THREAD

**Issue by gnalbandian** [tomturner/django-tenants#216]
As the title says, I need to run a collectstatic_schemas command after dynamically created tenant is saved.
I believe I should do it by capturing post_save signal, but I don't know how to run the command from the function called by the signal.

This is where i got to:

```
from django_tenants.management.commands import collectstatic_schemas
from django.core.management import call_command
from django.db.models.signals import post_save, pre_delete

@receiver(post_save, sender=Tenant)
def collect_static_tenant(sender, instance, **kwargs):
    # print(settings)
    call_command(collectstatic_schemas.Command(), schema=instance.schema_name, settings="project.settings.tenants")
```

But I am getting the following error:

> DatabaseWrapper' object has no attribute 'set_tenant'

Any help would be much appreciated.
Thanks

**Comment by tomturner** [comment]
The is a post signal you can use called post_schema_sync

**Comment by gnalbandian** [comment]
> post_schema_sync

Thanks, I have just try that but it seems the signal isn't triggered after schema is saved

**Comment by gnalbandian** [comment]
Looking at save method:

```
if has_schema and is_new and self.auto_create_schema:
            try:
                self.create_schema(check_if_exists=True, verbosity=verbosity)
                post_schema_sync.send(sender=TenantMixin, tenant=self.serializable_fields())
            except Exception:
                # We failed creating the tenant, delete what we created and
                # re-raise the exception
                self.delete(force_drop=True)
                raise
```

Should't this be
`if **not** has_schema and is_new and self.auto_create_schema:`

**Comment by gnalbandian** [comment]
I realize part of the problem is with the architecture of my project.
I am trying to manage tenants from a project whose settings doesn't have 'django_tenants' in it's INSTALLED_APPS, but does have the tenant app where tenant model is defined.

How can I manage to do this?
