### ISSUE TITLE
Moving from django-tenant-schemas

### ISSUE THREAD

**Issue by jeroenbrouwer** [tomturner/django-tenants#222]
Hi, currently I'm using `django-tenant-schemas` with some customizations to the storage and tenant middleware. Because that project seems abandoned / no longer maintained I've been looking at this project. What are the main differences between the two projects and would it be easy to switch over? Thanks!

**Comment by tomturner** [comment]
That the reason I created this project as the it seemed abandoned however DTS has been lots of enhancements done on it since. One of the main differences is the DT requires a domain model and a tenant model.

**Comment by tomturner** [comment]
And this project isn't backwards compatible with Django 1.X I believe DTS is

**Comment by jeroenbrouwer** [comment]
Thanks for the feedback. I don't need a domain model in my current project (tenants are only set in a userprofile model), so it sounds like there is no reason for me to move to this project currently. But, I will keep an eye on here in case DTS becomes incompatible with future django versions.

**Comment by rob101** [comment]
Could someone provide a use case for a domain model? I can't see how an app would require tenants using more than one domain. Isn't the domain meant to represent the schema and therefore be unique to each tenant?

**Comment by tomturner** [comment]
@rob101 No domain and schema can be different. You can have two domains pointing to the same schema.    I have two domain set for one schema. I use a number for the schema and use that for one domain. Then I also use a friendly company name for the other domain.  Hope that helps
