### ISSUE TITLE
[Question] class-based views with django-tenants

### ISSUE THREAD

**Issue by ishtiaque06** [tomturner/django-tenants#230]
Hello,

I was trying to figure out how to make class-based views work with django-tenants. It seems like I can't figure out how to get the right queryset from the right schema whenever I try to test my view with a tenant that's not the public tenant. Any pointers would be helpful.

Thank you.

**Comment by tomturner** [comment]
I always use CBV with DT they do work. To help we would need a copy of your settings file

**Comment by ishtiaque06** [comment]
> I always use CBV with DT they do work. To help we would need a copy of your settings file

I had figured it out but I might as well ask you whether there are better way to do things than I am right now. This is the view that I was having trouble with but figured out: 

```python
class DashboardView(LoginRequiredMixin, ListView):
    template_name = "dashboard.html"
    context_object_name = 'collections'
    paginate_by = 50

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def get_queryset(self):
        schema = self.request.META['HTTP_HOST'].split('.')[0]
        with schema_context(schema):
            queryset = Collections.objects.get(status = Collections.AVAILABLE)
        return queryset
```
So here I had to manually parse the request object to get the schema name. Do you do things this way as well? If so, maybe we can have a CBV Mixin or something similar that would do this automatically for us?

Thank you.
