### ISSUE TITLE
Backport a content_type cache clear change from the django-tenant-schemas

### ISSUE THREAD

**Issue by bsod90** [tomturner/django-tenants#232]
Hello, django-tenants maintainers!

It seems like this change from the django-tenant-schemas project is also relevant for django-tenants:
https://github.com/bernardopires/django-tenant-schemas/commit/7e104037c9522a408138c79c1fa8be3f98fc5894

Would it be possible to cherry-pick it? Without clearing the content types cache on every schema switch, all kinds of weird things are happening...

Thank you!

**Comment by lorinkoz** [comment]
Are you getting weird behavior with content types? Where do you have the content type app, in shared and/or tenant schemas?

-----Mensaje original-----
De: "Maxim" <notifications@github.com>
Enviado el: ‎24/‎01/‎2019 23:44
Para: "tomturner/django-tenants" <django-tenants@noreply.github.com>
CC: "Subscribed" <subscribed@noreply.github.com>
Asunto: [tomturner/django-tenants] Backport a content_type cache from thedjango-tenant-schemas (#232)

Hello, django-tenants maintainers!
It seems like this change from the django-tenant-schemas project is also relevant for django-tenants:
bernardopires/django-tenant-schemas@7e10403
Would it be possible to cherry-pick it? Without clearing the content types cache on every schema switch, all kinds of weird things are happening...
Thank you!

**Comment by bsod90** [comment]
Ho, @lorinkoz 
I have contenttypes in the TENANT_APPS section.
Basically, what I'm getting, is this. Sometimes, in the middle of a request, we have to switch tenants. If that happens, the content_types cache is not always cleared and, because the actual content type IDs may vary per tenant, we get a corrupted record in one or the other tenant schema.

**Comment by lorinkoz** [comment]
I think the current code clears the cache when switching tenants on `middleware/main.py:53`. But my real suggestion is, never put content types on `TENANT_APPS`, put them only on `SHARED_APPS` as that will guarantee that all content types are available to all tenants, regardless of the apps they synchronize.

**Comment by bsod90** [comment]
Yeah, I understand that putting contenttypes into the SHARED_APPS could've been a better idea but it's a bit too late for our app :)

Right now the cache clear happens only at the beginning of the request and, if you do multiple switches during the request, things may go wrong. The commit in the django-tenant-schemas moves the cache clearing from the middleware to the set_tenant() method, which is more reliable.

**Comment by tomturner** [comment]
@bsod90 and @lorinkoz thanks to both of you for this
