### ISSUE TITLE
Requirements should reference psycopg2 instead of psycopg2-binary

### ISSUE THREAD

**Issue by 007** [tomturner/django-tenants#233]
Per the [psycopg2 docs](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi) (emphasis added):

>Note The -binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements. **If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency.** For production use you are advised to use the source distribution.

It would be fine to pin `psycopg2<2.8` as recommended in #174, but it would probably also be fine to leave it floating and ignore the warning.

**Comment by lorinkoz** [comment]
Using `psycopg2` alone brings annoying warnings.

**Comment by 007** [comment]
@lorinkoz Your complaint ignores several important points:

1. The `psycopg2` docs recommend against using `-binary` as a dependency.
1. The docs recommend using the source distribution `for production` which should be the primary concern for most packages.
1. The `psycopg2` developer has stated that this warning should only happen for the 2.7.x series, and will go away with the release of 2.8.
1. I _explicitly said_ `and ignore the warning` in the report.

I'm trying to avoid https://github.com/unbit/uwsgi/issues/1569 and this package is including the `-binary` version against the recommendation of the upstream developer. The workaround is to `pip uninstall psycopg2 psycopg2-binary` and then reinstall it explicitly without the `-binary` suffix.

IMO packages should optimize for production use, and if any workaround is required it should be for development, since that's where people will be watching / interacting with the project directly.
