### ISSUE TITLE
Use for one app?

### ISSUE THREAD

**Issue by KrunchMuffin** [tomturner/django-tenants#237]
I would like to use django-filer which is not multi-tenant and was curious if django-tenants could be used on just that app?

**Comment by tomturner** [comment]
I can’t see why it shouldn’t work.

**Comment by KrunchMuffin** [comment]
So would I just follow the instructions as is or would some customization need to be done?

**Comment by tomturner** [comment]
Try it put the in installed app in the tenant side

**Comment by KrunchMuffin** [comment]
would that also include apps that the tenant app requires? or just the main app?
