### ISSUE TITLE
assertRedirects does not take into account tenant host

### ISSUE THREAD

**Issue by salvadormrf** [tomturner/django-tenants#24]
It seems to be an issue when using __assertRedirects__ 

Response redirected to 'http://tenant.test.com/admin/images/', expected 'http://testserver/admin/images/'

```python

from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model

from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient, TenantRequestFactory

from nvcimages.models import get_image_model

from .utils import get_test_image_file


class BaseSetup(TenantTestCase):

    def setUp(self):
        self.client = TenantClient(self.tenant)

    def login(self):
        # create a user
        user = get_user_model().objects.create_superuser(
            email='test@email.com',
            password='password'
        )
        # login
        self.client.login(email='test@email.com', password='password')
        return user

class TestImageDeleteView(BaseSetup):

    def setUp(self):
        super(TestImageDeleteView, self).setUp()
        self.image = get_image_model()(
            title="test.png",
            file=get_test_image_file(),
        )
        self.image.save()
        self.login()

    def get(self, pk):
        return self.client.get(reverse('nvcimages_image_delete', args=[pk]))

    def post(self, pk):
        return self.client.post(reverse('nvcimages_image_delete', args=[pk]))

    def test_simple(self):
        response = self.get(self.image.pk)
        self.assertTemplateUsed(response, 'nvcimages/images/confirm_delete.html')

    def test_delete(self):
        response = self.post(self.image.pk)
        self.assertEqual(Image.objects.all().count(), 0)
        self.assertRedirects(response, reverse('nvcimages_index'))
```

```
$ python manage.py test apps.nvcimages.tests.test_cms_views.TestImageDeleteView  --failfast
Creating test database for alias 'default'...
=== Running migrate for schema public
=== Running migrate for schema public
=== Running migrate for schema test
F
======================================================================
FAIL: test_delete (apps.nvcimages.tests.test_cms_views.TestImageDeleteView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zzzz/backend/apps/nvcimages/tests/test_cms_views.py", line 174, in test_delete
    self.assert_redirects(response, reverse('nvcimages_index'))
  File "/zzzz/backend/apps/nvcimages/tests/test_cms_views.py", line 48, in assert_redirects
    super(BaseSetup, self).assertRedirects(*args, **kwargs)
  File "/zzzz/.virtualenvs/zzz/local/lib/python2.7/site-packages/django/test/testcases.py", line 306, in assertRedirects
    (url, expected_url))
AssertionError: Response redirected to 'http://tenant.test.com/admin/images/', expected 'http://testserver/admin/images/'

----------------------------------------------------------------------
Ran 1 test in 8.657s

FAILED (failures=1)
```

response.url is __http://tenant.test.com/admin/images/__ and
expected_url is /admin/images/

For now I need to specify the host on kwargs to "solve" the issue
```python
    def assertRedirects(self, *args, **kwargs):
        kwargs['host'] = self.tenant.get_primary_domain().domain
        super(BaseSetup, self).assertRedirects(*args, **kwargs)
```

Any thoughts ?

**Comment by tomturner** [comment]
Sorry I haven't used assertRedirects before we will wait for someone else to reply

**Comment by kosz85** [comment]
Check this: https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.SimpleTestCase.assertRedirects

I think that issue may be on your side, I don't see anywhere in your code setting `HTTP_HOST` nor `host`. TenantClient is setting default value of `HTTP_HOST` due to tenants specifics to `self.tenant.get_primary_domain().domain` if not provided. You can provide yours or set `host` argument of `assertRedirects` to proper value and fix your issues.

**Comment by MikeSmith12222** [comment]
I just stumbled upon this problem today. 

Debug showed that assertRedirect actually renders the expected url to the one you mentioned.

I faked it by passing a full url including ("http://") - in a similar way that you did it. It feels a bit fake though

**Comment by kosz85** [comment]
Sorry, but tests shouldn't use real domain, tests should use test domain as it shouldn't be a difference where you run it. Why domain should matter? Env where you run your tests (staging or production (who is really running tests on production when it's too late?)) shouldn't make a difference.
Maybe rethink your tests.

**Comment by gannetson** [comment]
Maybe we should add some extra functionalities to TenantTestCase to properly set the domain?
Something like https://github.com/onepercentclub/bluebottle/blob/saas/bluebottle/test/utils.py#L100-L101 might fix the problem.

**Comment by salvadormrf** [comment]
Thanks for the feedback,
TenantClient already sets the HTTP_HOST with the tenant hostname for all HTTP methods https://github.com/tomturner/django-tenants/blob/1.0.2/django_tenants/test/client.py#L53

So the issue is related to assertRedirects, which can be solved by passing the host as argument as suggested.

###### Specify *host* argument on assert_redirects
```python
self.assert_redirects(response, reverse('experts_index'), host=self.tenant.get_primary_domain().domain)
```
###### Override *assertRedirects*

```python
def assertRedirects(self, *args, **kwargs):
    kwargs['host'] = self.tenant.get_primary_domain().domain
    super(BaseSetup, self).assertRedirects(*args, **kwargs)
```

###### Create you own method *tenantAssertRedirects*
```python
def tenantAssertRedirects(self, *args, **kwargs):
    kwargs['host'] = self.tenant.get_primary_domain().domain
    super(BaseSetup, self).assertRedirects(*args, **kwargs)
```
