### ISSUE TITLE
Multi db support?

### ISSUE THREAD

**Issue by webapp-dev** [tomturner/django-tenants#243]
If this has been answered elsewhere point me to it...but what is the status on this? I see a time soon when my multi-tenant db is full, there are performance limits we are all going to hit. Ideally, I want tenants 1-1000 in (db1) 1001-2000 in (db2) etc etc. and at the same time using db1 for the public tenant and for the authentication. Is this possible in django-tenants current form? any progress in this area? Should be achievable when authenticating on (db1) to get the details of the database to login to for the multi-tenant application side... Any forks attempting this? any anything? Would also be nice to handle the read replicas at the same time.

**Comment by allidoisace** [comment]
FYI: There is a Heroku PG Backups limitation of about 50 schemas or 20GB before there are issues, so yes there may be performance limits that may not have to do with django-tenants necessarily.

I am in this situation of handling multiple databases with multiple schemas. As long as your public schema doesn't have relations to any of the tenants, then you can probably keep that in db1. You cannot have cross relation databases, so anything that does have relations to djanbo.contrib models must be in the same database. I plan on tying specific databases to tenant models and using a DB router to route to that specific db.

The implementation I just described is what I am going to try to accomplish in the next week or so. I believe there has been talk here about Multi db support, but I can't find it again. I will let you know how my implementation goes.

**Comment by allidoisace** [comment]
Right now I am kind of stuck. Not sure how I can get the tenant information over to a DB router. Worst case scenario is just use `using` on EVERY query. jesus that will be horrible.

I can intercept the views request with some quick middleware, but that doesn't do me any good for the Database Router.

**Comment by tomturner** [comment]
Not quite sure how i would do this. I would be tempted to have multi sites to spread load.
Any other ideas are welcome

**Comment by kosz85** [comment]
My question is why are you doing it on django level (routers, tenants, etc), and why not at Postgres level? Postgres can scale horizontally. If heroku backups has limitation, then maybe do not use it?
About postgres and performance, standard postgres configuration sucks, so if you didn't do anything there, you can do plenty of optimizations before even starting thinking about scaling. Also upgrading postgres is thing to reconsider, as newest releases has parallel query running, and use power of multiprocessing, planning, etc. But you need to enable it in config ;)

You will have problems running it properly with routers, as routers are not for shared data. Here you are sharing public and some tenant schema. And this public schema has to be in each DB the same - so again it's more about scaling then about routing requests. Routing can be for heavy querying and master - slave setups.

I suggest to read about postgres first.

**Comment by kosz85** [comment]
Just to add, in general I don't think that django-tenants is app for addressing performance issues, but rather encapsulating data of your clients, and offer multi-tenancy. Performance issues, should be addressed in layers they occurs.

**Comment by tomturner** [comment]
@kosz85 I agree with your comments

**Comment by webapp-dev** [comment]
Firstly this issue has many layers to it, agreed the small Heroku's or any system with a 20GB limit should not be used for a commercial multi-tenant application. I use AWS because I can scale a database up to up 16 TB and scale out with master and multiple read slaves and it is auto mirrored into different zones (datacentres) which become the master in the event of a failed master. This provides fault tolerance, everything one would expect if you are going to be running a professional multi-tenant SAAS.

Xero.com one of the biggest most successful SAAS providers (millions of worldwide users on their system) use one client per schema based architecture also on AWS. They limit the number of companies (schemas) in a single database server because regardless of theory, real-world testing reveals at a certain size you start to lose performance. 

Expecting a single database server now matter how you cluster it, scale it vertically or horizontally will eventually hit its own inherent limits, then at that point, you will wish your software could have simply stored the database details of a company/schema stored so when it authenticated it used the database assigned.

At some point I will be looking to address this, I think django-tenants is a great multi-tenant layer for django.  Tom and all the contributors have done a cracker of a job. But if it could handle multiple-databases it would take it into the stratosphere!

**Comment by kosz85** [comment]
The question is if at that level this is still problem of django-tenant lib. I don't think so. If you have so much clients that you have such problems, you should have also money to develop solution. At this level it may be possible to hire postgres db developer to fix slower parts.
It may be also solved by creating layer over django app, and creating some proxy or loadbalancer depending on schema/domain/some part of url. In fact by keeping public schema almost empty, or just without public-tenant relation, you can easily have separate dbs. I can imagine general "master" public schema from which you can create slave public schemas in separated dbs, run by separate set of apps, still without any dajngo db routing.
You will just have to create some scripts to sync some data from your master public db (that would be separated) to your slave public db (that would have let's say 50 tenants each). But this really is not a problem of this lib. It's probably easier to make it in layer higher and layer lower. If you don't want to integrate it higher, them only thing would be routing for master public, and slave dbs, depending on active schema.

**Comment by allidoisace** [comment]
Okay I am not complaining about Heroku first of all. I plan on implementing my own Database generator and load balancer for tenants.

**Comment by webapp-dev** [comment]
> The question is if at that level this is still problem of django-tenant lib. I don't think so. If you have so much clients that you have such problems, you should have also money to develop solution. At this level it may be possible to hire postgres db developer to fix slower parts.
> It may be also solved by creating layer over django app, and creating some proxy or loadbalancer depending on schema/domain/some part of url. In fact by keeping public schema almost empty, or just without public-tenant relation, you can easily have separate dbs. But in any other example where you do not have any data flow between tenatns, I can imagine general "master" public schema from which you can create slave public schemas in separated dbs, run by separate set of apps, still without any dajngo db routing.
> 
> You will just have to create some scripts to sync some data from your master public db (that would be separated) to your slave public db (that would have let's say 50 tenants each). But this really is not a problem of this lib. It's probably easier to make it in layer higher and layer lower. If you don't want to integrate it higher, then only thing would be routing for master public, and slave dbs, depending on active schema. But rest has to be done in postgres anyway, to sync master public and salve public, maybe some automation for new db creation in django when creating schema, and so on.

You raised many good points, it is true there are many many ways to approach this, and like you say it could be done right now by letting postgresql auto replicate the public tenant to each additional database so you have authentication ability handled on each database, then I just need work out how to route them during login to the appropriate database.... many good ideas

**Comment by webapp-dev** [comment]
> Okay I am not complaining about Heroku first of all. I plan on implementing my own Database generator and load balancer for tenants.

allidoisace, well start a github project or share it here, I would be interested to see what you come up with. I am going to try and let postgresql manage most of it through replication., then figure out how to route them to their home database. The latest Django also has the ability to route to different dbs, not sure how that will work with django-tenants. here is a blog article with a copy of their routing code. Check it out: https://strongarm.io/blog/multiple-databases-in-django/

**Comment by kosz85** [comment]
Thx, for good words, I'm leaving from such ideas ;) 
I think that probably this is too early to even consider such approach, but let say you really need it.
I would suggest to keep public schema as small as possible, and avoid any interactions between tenants. Public schema replication would be nice thing if there is no other way, but without relations between public - tenant models, we get almost micro-service architecture, were public is just separate entity, and you don't need even to copy it. Public db would store info which tenant is in where, and use it to setup router. By activating tenant, you are just activating proper db, to use back public you just deactivate it.
The db router is in django long time already, it's nothing new. You will need to write router that is aware of active schema. What is more problematic, is that you can't do any public tenant modifications when you activate tenant schema, as this will force you to sync slave-public with master-public schema. Also your router will need to initialize search_path with your tenant schema, when you change tenant, this is smth that now django-tenant is doing, and this would need to be replaced there.
Quite funny code to do :) I like such problems. 
Next things to address is making migration on all dbs, background tasks and cron jobs. But by severing all relations between public and tenants there is much less to change. But you loose quite much of goodies from this lib :) In fact in some point you maintain app that is serving several microservices in single code base ;)  That cause just blowing memory by loading always all code of your apps, but you do not need to use and maintain API between microservices, and solve other complex problems related with this :)

**Comment by webapp-dev** [comment]
kosz85, I have been thinking maybe Redis cache server could be of use ... it offers more benefits, its easy to use and it can be turned into a Django session store easily, which really speeds up your Django application. If we expand its use just enough to store the database location details and schema name and have an alternate handler in Django-tenants to utilize Redis cache server... that would work like a charm. I realize it means you need to run up a second server, but that could be a simple micro service in a docker container. I already have an underutilized Redis cache server that handles celery tasks. 

django-tenants running super fast because it would be utilizing Redis cache server to route users to independent databases... that's gotta warm the cockles of your heart! ;-)

**Comment by allidoisace** [comment]
So, I am able to run `migrate_schemas --database='some_db'` and all my migrations run correctly. However, if I attempt to create object, I receive a `relation "app_model" does not exist` and I am not sure why that is since the tenant was saved correctly and I can access the tenant's domain with a login page.

**Comment by allidoisace** [comment]
I solved this problem by not doing multiple db's and actually moving everything over to AWS RDS from Heroku. It was simple as pie and now I can scale appropriately.

**Comment by mmcclelland1002** [comment]
Made a PR for this feature: https://github.com/django-tenants/django-tenants/pull/760
