### ISSUE TITLE
Unit Tests not Running

### ISSUE THREAD

**Issue by allidoisace** [tomturner/django-tenants#244]
Inside an app's `tests.py` I have this test (my first ever unit test)...
```
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient

class BaseSetup(TenantTestCase):
    def setUp(self):
        super(BaseSetup, self).setUp()
        self.c = TenantClient(self.tenant)

    def test_invoice_list_view(self):
        response = self.c.get(reverse('test'))
        self.assertEqual(response.status_code, 200)
```
When I run with the command `python manage.py test django_tenants.test` as specified in the documentation, I receive a result of...
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
```

I am not sure if I am doing something wrong, or if there are underlying issues. Thanks in advance.

**Comment by jcass77** [comment]
Not sure what you mean by:

> Inside an app's ``tests.py``

The command above assumes that all tests are located in ``django_tenants.test`` - is that where your test file resides?

Maybe also take a look at ``run_test.sh`` or ``run_tests_in_docker.sh`` to see if those will help you get started.
