### ISSUE TITLE
Logging in and redirecting to the view of the created domain

### ISSUE THREAD

**Issue by mariusz-kosakowski** [tomturner/django-tenants#245]
Below is the part of my code responsible for creating an account and user, then logging in and going to the home page.
Everything is OK until: `login(request, user)`. The user is redirected to e.g. test.localhost - to the login page, not to the view, after logging in.
Is there any way for a user from localhost - where user creates an account - to be logged in to the main view of test.localhost?

App in django 2.1.7 with django-tenants==2.1.0

```
def signup(request):
    if request.method == 'POST':
        client_form = ClientForm(request.POST, prefix='client')
        user_form = SignUpForm(request.POST, prefix='user')

        if client_form.is_valid() and user_form.is_valid():
            client = Client()
            client.schema_name = client_form.cleaned_data['name']
            client.name = client_form.cleaned_data['name']
            client.save()

            domain = Domain()
            domain.domain = client_form.cleaned_data['name'] + '.localhost'
            domain.tenant = client
            domain.is_primary = True
            domain.save()

            with schema_context(client.schema_name):
                user = user_form.save()
            login(request, user)
            redirect_url = 'http://' + client_form.cleaned_data['name'] + '.localhost:8000'
            return HttpResponseRedirect(redirect_url)
```

Please some hint.
Thanks and best.

**Comment by allidoisace** [comment]
Well your code is doing exactly what it is supposed to be doing. Try indenting your login(request, user) and let me know what happens. As your code sits now, you are logging in on the public schema.

**Comment by mariusz-kosakowski** [comment]
After chnaged to:

```
with schema_context(client.schema_name):
    user = user_form.save()
    login(request, user)
redirect_url = 'http://' + client_form.cleaned_data['name'] + '.localhost:8000'
return HttpResponseRedirect(redirect_url)
```

I received an error:
```
SuspiciousOperation at /accounts/signup/

The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
```

**Comment by allidoisace** [comment]
So, you have a public tenant request, and you are trying to login with that request on a different schema. I am not sure this is possible. You might be able to handle this redirection, which will send you to your tenant's login page. In that particular view you may be able to pass a user object and use the `login` function. Though I am not sure if this could be a security risk or cause unintended behavior.

My app consists of a signup page on the public site which generates a tenant, a public account, and a tenant account. I login to the public account and redirect to a public dashboard which they can access their tenant. Upon accessing their tenant, they MUST log in again with their same credentials. My public and tenant schemas hold 2 different user objects, but the tenant object maps to the public object. I am not sure if you will have to do something as tricky as this since my tenant login allows multiple users for that specific tenant as well as the main user that holds the public account.

**Comment by mariusz-kosakowski** [comment]
I thought there is a public tenant from that - where you can create user accounts for other tenants...
I also want other users to be able to log in to a particular tenant: one tenant --> multiple users.

Is it possible to separate the creation of an account for a particular tenant? That means:

1. Creating a tenant using the ClientForm form on localhost
2. Going to the next view already on test.localhost
3. Create a user for test.localhost

**Comment by kosz85** [comment]
Mariusz it all depends on your configuration and setup of your models. All points are probably possible.
You have to decide first on your approach, will you have one (shared) `User` model and list o tenants they can access, or each tenant will have separate table for it's users.
Then rest is just making it happen in code. You can separate creation of an account for a particular tenant, like any other model object. Maybe you will need adjust some standard django elements, but still all is possible.

**Comment by allidoisace** [comment]
kosz85 ia correct. You can also do both which I have accomplished. As a hint, you will need to modify if your `auth` app is shared or not.

My app has an account creation for the public as well as account creation for wach tenant.

**Comment by mariusz-kosakowski** [comment]
For me at the moment it is only possible to create an account and redirect an un-logged user to e.g. test.localhost

My goal is to have separate user accounts. For example, a person from group A cannot see a blog from group B. And vice versa. In group A and B there can be many users with different permissions (assigned by the group creator).

I have only ROOT_URLCONF configured (without PUBLIC_SCHEMA_URLCONF). Middelware is copied from a sample project.

Below are my settings, can you tell me if they are OK?
Accounts is an application where there is a usera and client model.

```
SHARED_APPS = (
    'django_tenants',  # mandatory
    'accounts',  # you must list the app where your tenant model resides in

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',

    'widget_tweaks',
    'accounts',
    'base',
    'blog',
    'django.forms',
    'debug_toolbar',
)

# Application definition
INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))
```

**Comment by kosz85** [comment]
Problem is in your thinking.
You can have account in shared, but if you want it totally separated, you should have it in tenant apps. But this will make some problems for you at public schema. But you can have it like it's now and you just need to not show other "blogs" to users that doesn't belong to it. It's not role of this lib to create your app, it's your role. I in fact doesn't understand your problem.

You create tenant let's say blog on public schema, redirect user to this blog url, and then it's role of your app to do the rest. You need to choose proper blog looking at url, so domain, url prefix, or whatever.

**Comment by atodorov** [comment]
In our case we have a public tenant at public.tenant.kiwitcms.org and users register their accounts on the public tenant. Creating a new tenant just creates new Tenant object in the database and redirects to $tenant_name.tenants.kiwitcms.org. Because the user is already logged in we have to share the session cookie between all the domains:

```
SESSION_COOKIE_DOMAIN = ".tenant.kiwitcms.org"
```
