### ISSUE TITLE
Schema cloning on PostgreSQL 10+

### ISSUE THREAD

**Issue by lorinkoz** [tomturner/django-tenants#246]
Starting on PostgreSQL 10, the way in which sequences are stored was drastically changed, breaking the current behavior of the schema cloning function. I don't see an easy way to support both versions, other than creating separate cloning functions and using one or another, depending on the version of Postgres.

I decided to drop support for PostgreSQL <10 in my project, in relation to schema cloning. I don't see many issues about cloning schemas here on `django-tenants`, so I take most users just run migrations on every tenant creation, and therefore this issue might be mostly irrelevant.

Just wanted to leave a note in case the issue pops up to anyone. Feel free to close if it's not helpful :)

**Comment by tomturner** [comment]
Fixed with #322
