### ISSUE TITLE
TenantFileSystemStorage doesn't work anymore

### ISSUE THREAD

**Issue by stygmate** [tomturner/django-tenants#249]
it's pretty easy to view the problem
just launch:
``` sh
./manage.py tenant_command shell --schema=schema1
```
and in the shell:
``` python
from django.core.files.storage import default_storage
print(default_storage.base_location)
```
the output will be:
```
/media/public
```

**Comment by stygmate** [comment]
@tomturner can you check that ?

**Comment by atodorov** [comment]
In my testing, starting with clean MEDIA_ROOT directory whichever tenant receives the first file upload ends up determining the directory path structure.

So if I first upload to the public schema I get `uploads/tenants/public/...` and everything ends up there.

If I first upload to a schema called `aero` I get `uploads/tenants/aero/...` and then uploads on public end up here too. Will look into the code for and try to make a PR.

**Comment by stygmate** [comment]
@atodorov i'm not behind the code but if i remember they remove path and url method overide of FileSystemStorage in TenantFileSystemStorage and keeped overided code only in __init__
...

**Comment by jcass77** [comment]
Should these changes perhaps also apply to `TenantStaticFilesStorage` as it inherits from `FileSystemStorage` too?

**Comment by atodorov** [comment]
@jcass77 maybe but I don't use that storage nor have the capacity to figure out how not to break existing behavior for people who are using the other storage classes.

**Comment by stygmate** [comment]
@atodorov maybe write a alternative BetterTenantFileSystemStorage class and pull it :) ?

**Comment by alexandernst** [comment]
I can confirm that this also applies to `TenantStaticFilesStorage`. Whatever tenant receives the first request get's to be the default and only for all requests, no matter to which tenant the requests are being directed to.

**Comment by jcass77** [comment]
Linking in related issue #248.

**Comment by alexandernst** [comment]
Here is the MR for this issue (the static files part): https://github.com/tomturner/django-tenants/pull/255

**Comment by alexandernst** [comment]
@atodorov Can you fix your unit tests in #252 so @tomturner can review it, and also review #255 and merge them if they look fine?

**Comment by atodorov** [comment]
> @atodorov Can you fix your unit tests in #252 

No, because I don't know how! 

As I've said in https://github.com/tomturner/django-tenants/pull/252#issuecomment-478183296 using the standard executor everything works and I've also verified that manually but I have no idea why the multiprocessing executor fails and I am asking for help to debug or hints how to figure out what the problem is.

You are doing work in the same space so maybe you can figure it out. Without more hints I'm kind of stuck on that multiprocessing test and not sure why Travis fails.

**Comment by alexandernst** [comment]
@atodorov ok, let me see if I can get around this. Do you mind if I hijack your MR?

**Comment by atodorov** [comment]
go ahead, we can always cherry-pick, rebase or whatever.

**Comment by tomturner** [comment]
@alexandernst and @atodorov thank you for all your hard work
