### ISSUE TITLE
How to test this on localhost?

### ISSUE THREAD

**Issue by MikeSmith12222** [tomturner/django-tenants#25]
Hi Tom,

I'm so glad that you continue the project and I got a very simple project up and running in Django 1.8.

BUT:
How do I test multiple tenants with djangos runserver? How to I set up the domains?
Or shall I install a local development server other then runserver? What do you recon?

Kind regards
Mikey

**Comment by tomturner** [comment]
So glad that you found my post the creator of django-tenent-schemas deleted my links!

I edited the host file to fake a domain and pointed that domain to 127.0.0.1

http://www.rackspace.com/knowledge_center/article/how-do-i-modify-my-hosts-file

**Comment by MikeSmith12222** [comment]
Hi Tom,
yeah thanks for your tip!! ﻿:-) 

and I think it is important to runserver on port 80.

On osx it is:
```
sudo python manage.py runserver fakedomain.com:80
```

Thanks a lot! At least now I see my templates on all tenant-domains... lets see how it goes on :-)

**Comment by tomturner** [comment]
You don't have to supply the domain name in the runserver.

**Comment by bartmika** [comment]
This was very helpful! Thanks!

**Comment by BillBrower** [comment]
If anyone else is having this issue, another solution is to install dnsmasq and have it route a particular domain, or even every domain with a particular extension (like .local), to 127.0.0.1

**Comment by Kazanz** [comment]
@tomturner can't setting 127.0.0.1 to localhost cause various problems with other parts of the system.  On OSX for example with the loopback interface?

```
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
```

**Comment by BillBrower** [comment]
@Kazanz you wouldn't set 127.0.0.1 to localhost, you'd just have a fake domain set to localhost.

**Comment by Kazanz** [comment]
🤦‍♂️ Wow, yep missed that.  Thank you.

**Comment by adnannazir** [comment]
do I still need to create it in host file?

**Comment by tomturner** [comment]
No you don't create a host file

http://anything.localhost:8000 will resolve to your local PC

**Comment by adnannazir** [comment]
`
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
# Application definition

SHARED_APPS = [
    "django_tenants",
    "website",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "tenant_users.permissions",
    "tenant_users.tenants",
    "accounts",
    # 3rd party libs
    "import_export",
    "django_htmx",
]

TENANT_APPS = (
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "tenant_users.permissions",
    "scheduler",
)
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
TENANT_USERS_DOMAIN = "localhost"
TENANT_MODEL = "accounts.Customer"  # app.Model

TENANT_DOMAIN_MODEL = "accounts.Domain"  # app.Model

AUTHENTICATION_BACKENDS = (
    "tenant_users.permissions.backend.UserBackend",
)

AUTH_USER_MODEL = 'accounts.User'
MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "scheduler.middlewares.AjaxMiddleware",
    "scheduler.middlewares.HandleSessionIssueMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "core.urls"
PUBLIC_SCHEMA_URLCONF = 'core.urls_public'

if DEBUG:
    SESSION_COOKIE_DOMAIN = None
else:
    SESSION_COOKIE_DOMAIN = '.localhost'

HOME_TEMPLATES = os.path.join(BASE_DIR, 'scheduler', 'templates')
`

Can you please check, what am I doing wrong????
