### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexandernst** [tomturner/django-tenants#257]
Since the currently released version of the library has some bugs related to file system storage/retrieval (fixed in #255 and #256), and there are a few other interesting changes, can you release a new version?

**Comment by alexandernst** [comment]
Great \o/
Remember to review and merge #256 before testing! That MR fixes the issues described in #248

**Comment by tomturner** [comment]
#256 Will have to wait until the next release otherwise another PR will come and I will never release. However I have had a look at #256 and it looks good.
Thanks

**Comment by alexandernst** [comment]
@tomturner but... the library as-is currently doesn't serve static files. Are you sure you want to release without merging that MR?

**Comment by tomturner** [comment]
@alexandernst A lot of people like my self don't have different static file per tenant. If I got time I will do the testing however I was ready to release.
