### ISSUE TITLE
axes_reset management command not called on all tenants

### ISSUE THREAD

**Issue by MikeSmith12222** [tomturner/django-tenants#26]
Hi guys,

I just set up a first test environment.

In my application I use a module called django-axes for security. It logs wrong login entries and bans IPs.
Anyway:
in my settings.py I got

```
SHARED_APPS = (
    'django_tenants', # ...
    'axes',  # enable security for my public tenant
)

TENANT_APPS = (
    'axes',  # enable security for my private tenants
)
```

after a
```
python manage.py makemigrations; python manage.py migrate_schemas
```
each tenant (1public plus 2 private) has its own wrong-login-attempts tables, and the banning itself works fine.

BUT:
when I then run the associated manamgenet command 
```
python manage.py axes_reset
```
ONLY the public app table is resetted.

I also tried a 
```
python manage.py tenant_command axes_reset
```
which just gives me the following error:
```
usage: manage.py tenant_command [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [-s SCHEMA_NAME]
manage.py tenant_command: error: unrecognized arguments: axes_reset
```

Any ideas whats wrong? How do I run this command on ALL tenants?

**Comment by tomturner** [comment]
See #3 same bug. I am waiting for a fix

**Comment by tomturner** [comment]
Should work now
