### ISSUE TITLE
Application management - how many accounts, how many users.

### ISSUE THREAD

**Issue by mariusz-kosakowski** [tomturner/django-tenants#260]
Hello to all,

I'm trying to create an application based on django-tenants. My question concerns account management, senise counting how many accounts there are, how many people are in the company etc.

At the moment I do not have for the "public" schema the possibility to access other schemas.

At this point in my settings, it looks like this:

```
SHARED_APPS = (
    'django_tenants',  # mandatory
    'accounts',  # you must list the app where your tenant model resides in
    'app_1',
    'app_2',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',

    'widget_tweaks',
    'accounts',
    'base',
    'app_1',
    'app_2',
    'django.forms',
)

# Application definition
INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))
```

I mean mainly applications app_1 and app_2. If they are in `SHARED_APPS` - no problem - there is access to them from the /admin/ level. However, if they are in `TENANT_APPS` - there is no access.
If I put app_1 and app_2 in `SHARED_APPS` - it is not safe. So is there any way to solve it (I mean management, checking accounts and users).

Thank you in advance for every hint.
Have a nice day.

**Comment by dperetti** [comment]
It would be nice to have an API to list / manage tenant, indeed.

**Comment by kosz85** [comment]
Then write it :)

**Comment by tomturner** [comment]
I agree it easy to write yourself
