### ISSUE TITLE
Docs at readthedocs.io out of date.

### ISSUE THREAD

**Issue by yangineer** [tomturner/django-tenants#277]
Greetings!

It looks like the documentation served at https://django-tenants.readthedocs.io/en/latest/ is out of date with master or the latest release.

The commit ID on readthedocs is `98f1c028` which was committed Nov 9 2018.
It looks like the last build happened 6 months ago: https://readthedocs.org/projects/django-tenants/builds/

Were the webhooks removed?

**Comment by atodorov** [comment]
> Were the webhooks removed?

or more likely there's a failure in RTD builds.

**Comment by tomturner** [comment]
I think I have sorted it
