### ISSUE TITLE
Problem when i try to access the schema domain, 404 not found

### ISSUE THREAD

**Issue by Nicolas-SistemaFactoring** [tomturner/django-tenants#278]
Versions ---- Django-tenants  **2.2.3** | Django  **2.1.7** | Python **3.7.2**

Mainly problem: 

> When i try access localhost and schema.domain.localhost i get 404 Not Found.

I coded my project according as your tutorial explained, i will let here my `settings.py` and my `urls.py` to avoid answers that indicate i am getting basics errors of django.
Also i cloned by project without django-tenants, and start migrate him to django-tenants. 
So, the project it self access the localhost:8000 normally without `404 not found`.

```
SHARED_APPS = [
    'django_tenants',
    # ****
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # ****
    'django.contrib.staticfiles',
    'widget_tweaks',
    'login',
    'project_name',
]

TENANT_APPS = [
    # Same imports used above between '' *** ''
    'dashboard',
]

INSTALLED_APPS = [
    'django_tenants',
     # Same imports used above between '' *** ''
    'django.contrib.staticfiles',
    'widget_tweaks',
    'login',
    'dashboard',
    'project_name',
]

TENANT_MODEL = "login.Connection"  # app.Model
TENANT_DOMAIN_MODEL = "login.Domain"  # app.Model

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

PUBLIC_SCHEMA_URLCONF = 'project_name.urls'
ROOT_URLCONF = 'project_name.urls'

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

```

Also when `INSTALLED_APPS = list(SHARED_APPS+TENANT_APPS)` the views can't find anymore my `.html` archives (i provide them in the apps directory into a template folder).

Run tab of Pycharm, when i try access `localhost `or `schema.domain.localhost` :
![image](https://user-images.githubusercontent.com/50324697/58101372-e0a94f00-7bb5-11e9-968f-a3e5196f5019.png)

- ### Proving it's not django basics erros.

Projetc_name > urls.py:
```
urlpatterns = [
    path('', include(login_urls)),
    path('dashboard/', include(dash_urls)),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
```
Login > urls.py:

```
urlpatterns = [
    path('', login_dash, name="login"),
    path('recovery/', pass_recovery, name="pass_recovery")
]
```
Login > views.py:
```
def login_dash(request):
    return render(request, 'login.html')
```

**Comment by Nicolas-SistemaFactoring** [comment]
1. I changed `PUBLIC_SCHEMA_URLCONF = 'project_name.urls'` to `project_name.url_public` and create the file, with the same data of `urls.py`(in the same directory as `urls.py` of project, not the `ursl.py` app), and i still got the same problem.

1.  Also i made it all configurations again, in a project and database, with the same resolution.

**Comment by tomturner** [comment]
Did you watch my YouTube video on how to set it up

**Comment by dev-sistemafactoring** [comment]
> Did you watch my YouTube video on how to set it up

Yes, i watched and i made exactly as you made it.
But also, it's possible i'm not understanding some configuration you explained.

What you think it's wrong?

**Comment by dev-sistemafactoring** [comment]
Good news, it's **WORKING**.

My problem was in my thought, i wasn't understanding how domains and models.py works, and that was getting me in trouble because it was not being clear what I needed to correct and what was wrong.

Anyway, for access in localhost you need to put in the end of domain ".localhost" (my OS it's **Windows**), for access in the localhost.

Thanks to Marcos Silva for having guided me better in the operation and how to use. 
And for @tomturner to provide that llb to simplify my life using multiple schemas.

**Comment by Nicolas-SistemaFactoring** [comment]
### Good news, it's **WORKING**. 
My problem was in my thought, i wasn't understanding how _domains_ and` models.py` works, and that was getting me in trouble because it was not being clear what I needed to correct and what was wrong.  Anyway, for access in localhost you need to put in the end of domain ".localhost" (my OS it's Windows), for access in the localhost. 

Thanks to Marcos Silva for having guided me better in the operation and how to use. And for @tomturner to provide that llb to simplify my life using multiple schemas.

**Comment by Manan-Meghani** [comment]
> ### Good news, it's **WORKING**.
> My problem was in my thought, i wasn't understanding how _domains_ and` models.py` works, and that was getting me in trouble because it was not being clear what I needed to correct and what was wrong. Anyway, for access in localhost you need to put in the end of domain ".localhost" (my OS it's Windows), for access in the localhost.
> 
> Thanks to Marcos Silva for having guided me better in the operation and how to use. And for @tomturner to provide that llb to simplify my life using multiple schemas.

Thanks a lot dude. I am stuck at from 1 day before only because of not putting .localhost at last on domain name for run it local machine. :)

**Comment by daym** [comment]
What is meant here is that one needs at least `ALLOW_HOSTS = ['.localhost']`.

**Comment by Manan-Meghani** [comment]
@daym No, just check this django-tenant [Doc](https://django-tenants.readthedocs.io/en/latest/use.html#running-in-development)
