### ISSUE TITLE
Can't create models.py with "class Meta:". (Tenant_apps)

### ISSUE THREAD

**Issue by Nicolas-SistemaFactoring** [tomturner/django-tenants#279]
### I'm testing everything since hours and my conclusion is, if your **tenant** model has `Meta` inside the class, the class will not migrate to the database.

**Proving that I'm not lying:**
![image](https://user-images.githubusercontent.com/50324697/58280386-d84c4200-7d76-11e9-8bf8-008fec80f59f.png)
![image](https://user-images.githubusercontent.com/50324697/58280395-df735000-7d76-11e9-9eb2-7c9dddf705f6.png)

So in my case `Meta` isn't something needed for the evolution and deploy of project, but i think it's for someone.

**Comment by Nicolas-SistemaFactoring** [comment]
Also, the migrations work fine, `makemigrations` too. 
When i run `migrate_schema` also print the migrate of tenant_model, but doesn't migrate. 
### Concluding it's not a bug maybe it's a code error

**Comment by Nicolas-SistemaFactoring** [comment]
I just notice that i can't create a model with
```
 class Meta: 
        managed = False
```
Doesn't have anything about `db_table = 'name'`

But anyway i'm not sure why this happen. It's because, with `managed =  false` django-tenant can't config the database?!

**Comment by kosz85** [comment]
Really? Please first check django docs: https://docs.djangoproject.com/en/2.2/ref/models/options/#managed

By putting there `manged = False` you inform django that you by yourself will manage this model, create its tables and do migrations.

**Comment by Nicolas-SistemaFactoring** [comment]
@kosz85 Yep, you are absolutely right. I'm sorry for this beginner mindset, i always forget to read the docs.
However i'm stucked in a problem related to this post. I restarted the project again to avoid simple problems that i can have done.

And for now i need to make tables with their names(i don't know if this issue it's caused by me or the llb), when i have a model with `db_table = 'modelname'` and i use that model, the code got errors trying to search into a table with name `appname_modelname`. Explaining like example project of **django-tenants**, the code are searching by customers_login and i need to search just by login (regardless if is public schema or not). And that is how i got here, i was searching what i was doing wrong. But i still with a problem.
Explaining in an image:
![image](https://user-images.githubusercontent.com/50324697/59362760-64181500-8d0a-11e9-971f-331e0f2d23c1.png)

I'm not sure why, and i just noticed this will break up the operation of the project

- Again, i'm sorry for the stupid question, is being a big burden for me to handle an advanced library without being advanced in django and i didn't notice the answer of `manage ` was in my face.

**Comment by kosz85** [comment]
https://docs.djangoproject.com/en/2.2/ref/models/options/#db-table

This should work like you say, without appname. You need provide more info. Dashboard is and app or model name? If model, then maybe it's not about table but about m2m relation table.

**Comment by Nicolas-SistemaFactoring** [comment]
@kosz85 I thought that it was enough information, sorry.
Dashboard is a app name, and is an tenant app. Yesterday i was testing with `db_table` in Meta of models, and got the error that i show in image below. I restarted the project some times to find whats going on, but without any success.

As i said, django-tenants it's trying to search by `appname_modulename` automatically. Do i need to set something to not search like this?!

**Comment by Nicolas-SistemaFactoring** [comment]
Okay, so i made **migrations** again, and **migrate_schemas** (yes i already did it before), and worked fine.

I still don't know why, but works, maybe was something i did wrong. Thank a lot @kosz85. Do i need to change something in here in #279 ? For documentation reasons?! If i need do it, tell me and i will do it.

 I will await your response to close the post, or if you want close be feel free to do it.

**Comment by kosz85** [comment]
Hah, and seeing your first comment I just wanted to suggest you deleting your db, migrations, and make it from scratch :) But I see that you did it on your own. Yes, making migrations and then migrate_schemas is always good thing to do.
I don't think you need to add smth in docs, as you just made it properly as you should from start. You can close this issue. No need for thanks, I answered by coincident, your email was mixed in my inbox. I don't have much time to answer questions normally.

**Comment by Nicolas-SistemaFactoring** [comment]
@kosz85 Uhhh deleting migrations sounds worrisome thing for me, do you know some doc to teach me by scratch?!
Also, thank you again. I will close it soon.

**Comment by kosz85** [comment]
@Nicolas-SistemaFactoring deleting migrations isn't that bad as you think :) It's almost same as squash. But if you are in small team, without production yet, deleting is sometimes more straight forward. You can always delete migrations, then make initial migration and apply it as fake, as it should represent state of your current DB. Of course without new changes in models.
