### ISSUE TITLE
Error when creating a new tenant, Django > 1.10

### ISSUE THREAD

**Issue by LiteWait** [tomturner/django-tenants#282]
if type_ is not None and infodict['type'] != type_:
KeyError: 'type'

"Removing an index from an IntegerField causes a KeyError exception"

See: https://code.djangoproject.com/ticket/28684

Postgres 9.6

**Comment by tomturner** [comment]
What version of Django are you using?

**Comment by LiteWait** [comment]
Trying to move to Django 2.2.X. Thanks.

**Comment by amitsarwara** [comment]
@LiteWait Please have a look at  [#527](https://github.com/jazzband/django-oauth-toolkit/issues/527#issuecomment-501982541)

**Comment by tomturner** [comment]
Is this still an issue

**Comment by LiteWait** [comment]
Nope. Solved it. Thanks Tom.
