### ISSUE TITLE
Jinja2

### ISSUE THREAD

**Issue by mronoffon** [tomturner/django-tenants#286]
Is there any documentation on implementing django_tenants and django_tenant_users (is this still active?)

thanks

**Comment by tomturner** [comment]
I once committed the code to make it work. I don't know if it still works.

**Comment by mronoffon** [comment]
Hi, thanks for your speedy response!

Are your referring to jinja or django-tenant-user?

**Comment by tomturner** [comment]
django-tenant-user

**Comment by mronoffon** [comment]
Will both projects work with jinja?  

Thanks

**Comment by tomturner** [comment]
Try it
