### ISSUE TITLE
TenantTestCase - All tests fail when auto_create_schema is False

### ISSUE THREAD

**Issue by bynjamin** [tomturner/django-tenants#288]
When auto_create_schema = False is on the TenantMixin model the TenantTestCase will not create the schema in the database. Is there some way to achieve schema creation forcibly?

**Comment by prudnikov** [comment]
Why is this closed without any comment? Don't you see issue with this?

For me currently easiest workaround is to override `setup_tenant` method on TenantTestCase to force `auto_create_schema = True`.

```
@classmethod
def setup_tenant(cls, tenant):
    tenant.auto_create_schema = True
    super().setup_tenant(tenant)
```
