### ISSUE TITLE
Admin shows tenant model in my Customer's admin interface (each tenant).

### ISSUE THREAD

**Issue by galileoguzman** [tomturner/django-tenants#293]
I am pretty sure it's something regarding the configuration of `django-tanants` but I spent all pass weekend without a solution.

I have the next configuration on my apps:

```
SHARED_APPS = [
    'django_tenants', # Mandatory
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customers', # you must list the app where your tenant model resides in
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notes',
]

INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))
```

# App schema

I only want to show my `notes` app in the admin for each of my customers. So I have in `notes/admin.py` the next content:

```
from django.contrib import admin

# Register your models here.
from .models import Note
admin.site.register(Note)
```

And in my `customers/admin.py` file the next content:

```
from django.db import models
from django.contrib import admin
from django_tenants.admin import TenantAdminMixin

from .models import Client

class ClientAdmin(TenantAdminMixin, admin.ModelAdmin):
        list_display = ('name', 'paid_until')

admin.site.register(Client, ClientAdmin)
```

Even though I followed the tutorial in the documentation and the youtube tutorial, I got the next result:

![Screen Shot 2019-07-22 at 09 40 25](https://user-images.githubusercontent.com/2016072/61641501-df9fa700-ac64-11e9-9917-574ac8709dcf.png)
![Screen Shot 2019-07-22 at 09 40 33](https://user-images.githubusercontent.com/2016072/61641517-e4645b00-ac64-11e9-82f2-eaf6d35ecbcb.png)
![Screen Shot 2019-07-22 at 09 40 51](https://user-images.githubusercontent.com/2016072/61641525-e7f7e200-ac64-11e9-8c31-81d63abf731e.png)
![Screen Shot 2019-07-22 at 09 40 57](https://user-images.githubusercontent.com/2016072/61641530-eaf2d280-ac64-11e9-812c-8534268a50ef.png)

As you can see in the first and second tenant I have the `TENANT_MODEL` in the admin interface. I don't want that for a lot of reasons.

# Can't edit tenant information

When I try to edit the customer model from the admin of one of tenants (`first.mydomain.local` or `second.mydomain.local`) I can't do it, though I don't want show the tenants model in the admin of each customer.

![Screen Shot 2019-07-22 at 09 41 05](https://user-images.githubusercontent.com/2016072/61641534-ed552c80-ac64-11e9-99ff-999b1de2c005.png)

### Requirements
```
Django==2.2.3
django-tenants==2.2.3
psycopg2==2.8.3
python-decouple==3.1
pytz==2019.1
sqlparse==0.3.0
```

Also if you need to get more info I put the code in the next repository:
```
https://github.com/galileoguzman/django-tenants-sample
```

**Comment by kosz85** [comment]
Why you think it should not show tenant model?
Think about it. App `django.contrib.admin` is django app, so totally not aware of tenants, and you register your models using `from django.contrib import admin; admin.site.register(...)`, so in fact you register all models in single admin site. So you have all models in single admin, and this is how this app works! It works correctly!

In fact what you need is to read django documentation on django admin: https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#multiple-admin-sites-in-the-same-urlconf

As in reality you want 2 separate admins, with completely different models set :)
I hope my answer would be helpful ;)

**Comment by tomturner** [comment]
You can get what you want with permissions on users

**Comment by delegate-it** [comment]
from django.contrib import admin
from django.apps import apps
from django_tenants.utils import get_public_schema_name


class TenantsAdmin(admin.ModelAdmin):
    '''
    Hides public models from tenants
    '''
    def has_view_permission(self,request, view=None):
        if request.tenant.schema_name == get_public_schema_name():
            return True
        else:
            return False
    
    def has_add_permission(self,request, view=None):
        if request.tenant.schema_name == get_public_schema_name():
            return True
        else:
            return False
    
    def has_change_permission(self,request, view=None):
        if request.tenant.schema_name == get_public_schema_name():
            return True
        else:
            return False
    
    def has_delete_permission(self,request, view=None):
        if request.tenant.schema_name == get_public_schema_name():
            return True
        else:
            return False
    
    def has_view_or_change_permission(self, request, view=None):
        if request.tenant.schema_name == get_public_schema_name():
            return True
        else:
            return False
    
app = apps.get_app_config('tenants')
for model_name, model in app.models.items():
    admin.site.register(model, TenantsAdmin)

**Comment by cehceh** [comment]
@kosz85 Helpful answer Thanks
