### ISSUE TITLE
Error when using uppercase in the schema name

### ISSUE THREAD

**Issue by maxthevoice** [tomturner/django-tenants#294]
I got this error when I use `Client` for the schema name:
```
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (relation "django_migrations" already exists)
```

It works with `client`.

I searched for Postgresql schema naming convention but didn't find anything.

I'm using the `postgres:10-alpine` docker image.

The regular expression should be changed:
```diff
-SQL_IDENTIFIER_RE = re.compile(r'^[_a-zA-Z][_a-zA-Z0-9]{,62}$')
+SQL_IDENTIFIER_RE = re.compile(r'^[_a-z][_a-z0-9]{,62}$')
```

**Comment by kosz85** [comment]
This is normal :) schema_names are not case sensitive, so `client` and `Client` are for posrtgres exactly the same schema, so creating 2 tenants like this you are trying to run second time migrations on the schema.

**Comment by maxthevoice** [comment]
Thank you for your quick answer.

The issue is not the fact that the schema `client` already exists. I got the error message when I use a schema name with at least an uppercase character. The only existing schema is `public`, then I create a Tenant `Client` by the admin panel and got the error.

If I run the command mannually in SQL it works, because Postgres will replace all the uppercase characters by lowercase, but there is something elsewhere that causing this issue.

I don't use the domain part. :)

**Comment by kosz85** [comment]
Are you sure you use clean db without client? As for me it seems that not.
`(relation "django_migrations" already exists)`
Tables are not creating from nothing ;)

The other reason may be that `search_path` complains and do not switch so you are accessing public, but it should be ok in theory.  But in the end it doesn't matter, just use lowercase schema names, that's the answer for this problem. Django probably is converting your `search_path` from `public, Client` that is understood by postgres as `public, client` to `"public", "Client"` which is not the same :)

You do not use the domain part, that's ok, I also don't, but it's useful not only there ;)

**Comment by maxthevoice** [comment]
I suggest that you try it with Django 2.2

Anyway I fixed the issue adding a clean method in the tenant model, just to avoid having this kind of error in the Rollbar.

Thank you for your time tho :)
