### ISSUE TITLE
How to find current tenant instance?

### ISSUE THREAD

**Issue by halukpy** [tomturner/django-tenants#296]
I am not able to get the tenant instance to limit choices or return limited query of other models.

e.g: Tenant has MTM relation with City model. The tenant has stores in some of those cities.
A different X model has MTM city field.

And question is, how can i limit the city list called by x object to those of tenant's?

Thank you 

P.S: Docs didn't help me for the issue

**Comment by allidoisace** [comment]
In your views just do `request.tenant`.

**Comment by kosz85** [comment]
First explain better your app layout, as you explained it in rather chaotic way. Write what models are in what app, and what app are in SHARED and TENANT APPS. Then, were is M2M field.

In general if you have M2M  between 2 models in SHARED and  TENANT_APPS, then you have to declare it on TENANT_APPS side, this way it will be automatically restricted to what relation were created on this TENANT, opposite won't work and even may break db integrity, as you may have m2m relation to not existing objects.
Example of breaking integrity:
You create M2M relation between Tenant and Model with id 10 that exists in Tenant A.
You create new Tenant B and switch to it, you list Models by M2M relation and have problem as M2M is pointing to Model id 10 witch doesn't exists yet at Tenant B.
If M2M would be on Tenant schema side, then this M2M relation table would be clear same way as this Model table, and thats how it should be done properly. Declare your cross schema relations on TENANT side.

**Comment by halukpy** [comment]
> In your views just do `request.tenant`.

Thank you. It works as expected.
P.S: is it possible to get it in models.py or admin.py ?

**Comment by kosz85** [comment]
I already told you about the solution:
```
from django.db import connection

def some_function():
     schema_name = connection.get_schema()
     tenant = connection.get_tenant()
     ...
```

Do not use connection in places like:
```
from django.db import connection
# do not use here
class Model(models.Model):
    # not here
   def method(self):
        # here is ok

def aaa():
    # here ok
```

**Comment by halukpy** [comment]
> I see that subject and description are 2 separate questions, so first was answered, but you can also use method on connection wrapper to just know current tenant: https://github.com/tomturner/django-tenants/blob/master/django_tenants/postgresql_backend/base.py
> 
> Second one:
> 
> First explain better your app layout, as you explained it in rather chaotic way. Write what models are in what app, and what app are in SHARED and TENANT APPS. Then, were is M2M field.
> 
> In general if you have M2M between 2 models in SHARED and TENANT_APPS, then you have to declare it on TENANT_APPS side, this way it will be automatically restricted to what relation were created on this TENANT, opposite won't work and even may break db integrity, as you may have m2m relation to not existing objects.
> Example of breaking integrity:
> You create M2M relation between Tenant and Model with id 10 that exists in Tenant A.
> You create new Tenant B and switch to it, you list Models by M2M relation and have problem as M2M is pointing to Model id 10 witch doesn't exists yet at Tenant B.
> If M2M would be on Tenant schema side, then this M2M relation table would be clear same way as this Model table, and thats how it should be done properly. Declare your cross schema relations on TENANT side.
> 
> Other way is to create M2M through model with additional tenant id indicator, but that just sucks :P

The question within the explanation was the real problem and the subject was the reason of it. Also the one in the description should be expected to explain the issue.

On the other hand, you are right that the two seems to be unrelated. Especially, if you have a clear understanding of django-tenants.. But I don't have that yet.

Thank you for your explanation. Sorry for the chaotic way of explanation, but it seems that it worked due to detailed explanation of the concept by you. Shared Apps and Tenant Apps are always be a problem for django-tenants.(at least for me) Which app to where? Are there any strict rules for it. How should be the relation btw them and so on.

Your second explanation is really valuable and I will be studying your first solution which is also great.. Thanks again.

P.S: my apps and models are:
```
tenants (shared app)
    Company (model)
        .... (field)
        city
        ...

location (shared app)
    City
        ...

another_app (tenant app)
    X
        city (choices to this field should be limited to current tenant's cities)
```

**Comment by halukpy** [comment]
> I already told you about the solution:
> 
> ```
> from django.db import connection
> 
> def some_function():
>      schema_name = connection.get_schema()
>      tenant = connection.get_tenant()
>      ...
> ```
> 
> Do not use connection in places like:
> 
> ```
> from django.db import connection
> # do not use here
> class Model(models.Model):
>     # not here
>    def method(self):
>         # here is ok
> 
> def aaa():
>     # here ok
> ```
> 
> As in such places it's run only at start, and you know that it would be `public` schema.

This is the head shot. Thank you again.

**Comment by kosz85** [comment]
If you do not need to have locations shared, then you can move them to tenant. But probably it's not this case, as it's wise to share locations. So in fact you need to dynamically filter cities. And then it depends how you solve it at frontend. If you load it by json query, just filter with `request.tenant`, if by form use dynamic choice fields: https://stackoverflow.com/questions/3419997/creating-a-dynamic-choice-field
