### ISSUE TITLE
tenant_commands are not executing

### ISSUE THREAD

**Issue by imcery** [tomturner/django-tenants#3]
runing something as simple as `python manage.py tenant_command check` is always returning error:

```
usage: manage.py tenant_command [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [-s SCHEMA_NAME]
manage.py tenant_command: error: unrecognized arguments: check
```

**Comment by tomturner** [comment]
Except it an error. Will look in to it.

**Comment by mikeshultz** [comment]
Command doesn't appear to be accepting arguments.

    [mike] # ./manage.py tenant_command loaddata --schema=votedumb
    usage: manage.py tenant_command [-h] [--version] [-v {0,1,2,3}]
                                    [--settings SETTINGS]
                                    [--pythonpath PYTHONPATH] [--traceback]
                                    [--no-color] [-s SCHEMA_NAME]
    manage.py tenant_command: error: unrecognized arguments: loaddata
    [mike] # ./manage.py tenant_command loaddata --help
    usage: manage.py tenant_command [-h] [--version] [-v {0,1,2,3}]
                                    [--settings SETTINGS]
                                    [--pythonpath PYTHONPATH] [--traceback]
                                    [--no-color] [-s SCHEMA_NAME]

    Wrapper around django commands for use with an individual tenant

    optional arguments:
      -h, --help            show this help message and exit
      --version             show program's version number and exit
      -v {0,1,2,3}, --verbosity {0,1,2,3}
                            Verbosity level; 0=minimal output, 1=normal output,
                            2=verbose output, 3=very verbose output
      --settings SETTINGS   The Python path to a settings module, e.g.
                            "myproject.settings.main". If this isn't provided, the
                            DJANGO_SETTINGS_MODULE environment variable will be
                            used.
      --pythonpath PYTHONPATH
                            A directory to add to the Python path, e.g.
                            "/home/djangoprojects/myproject".
      --traceback           Raise on CommandError exceptions
      --no-color            Don't colorize the command output.
      -s SCHEMA_NAME, --schema SCHEMA_NAME
                            specify tenant schema

When just issuing help, I get a trace

    [mike] # ./manage.py tenant_command --help
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/mike/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/home/mike/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/mike/.virtualenvs/project/lib/python2.7/site-packages/django_tenants/management/commands/tenant_command.py", line 21, in run_from_argv
        raise CommandError("Unknown command: %r" % argv[2])
    django.core.management.base.CommandError: Unknown command: '--help'

Hope that helps.

**Comment by mikeshultz** [comment]
I messed around a little bit, but I don't have something nice enough for a pull request.  Adding the following to `django_tennants.management.commands.tennant_command` gave me something that worked, but you still can't specify -s/--schema because of the conflicting params.

    def add_arguments(self, parser):
        super(InteractiveTenantOption, self).add_arguments(parser)
        parser.add_argument('args', metavar='fixture', nargs='+',
            help='Fixture labels.')

With this, I can run `./manage.py tenant_command loaddata fixturename` and it works as expected.  It prompts you for a schema name and it won't accept the `-s` option.

I messed around with trying to merge all args in `InteractiveTenantOption` as well but don't have any good fixes for everything.  It likely has to do with how `add_arguments` works with django, because I keep either overriding things or destroying everything.  tenant_command might just need to be refactored.  It's a good idea to be able to run any django command against a certain schema, if it can work.

I'll keep playing around, but I'm out of ideas for the night.

**Comment by mikeshultz** [comment]
How backward compatible does this need to be with django_tenant_schemas and django<1.8?  If I refactored this command code to work entirely different than it did before, it might not be backwards compatible at all and would not allow a seamless transition from django_tenant_schemas and django_tenants.

**Comment by tomturner** [comment]
This project is for django 1.8 and above

**Comment by mikeshultz** [comment]
That answers part of my question, but not all.  What about compatibility with django_tenant_schemas?  How important is that?

**Comment by tomturner** [comment]
@mikeshultz I am not worried about compatibility as people have to do quite a bit of work to migrate from django_tenant_schemas

**Comment by MikeSmith12222** [comment]
Hi guys,

any news on this one? can you post a pull request as a quick fix?

**Comment by MikeSmith12222** [comment]
Oh yeah baby! Works great!
