### ISSUE TITLE
Invalid string used for the schema name. When using only numbers

### ISSUE THREAD

**Issue by tomturner** [tomturner/django-tenants#302]
Before I just make a change I wanted to reach out.

I wanted to create a schema name with just number ie 123 however it doesn't work due to a regular expression 
`SQL_IDENTIFIER_RE = re.compile(r'^[_a-zA-Z][_a-zA-Z0-9]{,62}$')`

I have tried to create the schema manually in PgAdmin and PostgreSQL allows it! 

Does any mind if I change that regular expression? or do people many we to make it a setting?

**Comment by Tberdy** [comment]
#307
