### ISSUE TITLE
Error on use public domain with public schema

### ISSUE THREAD

**Issue by Nicolas-Coeficiente** [tomturner/django-tenants#306]
In the last months i have been using the django-tenants in the different way i was expecting, and today this came up to my mind and i realize it's working different then i thought and this is a problem to me. Summarizing the story:

- I was using `PUBLIC_SCHEMA_URLCONF `and `ROOT_URLCONF` with the value of `myproject.urls` (The root folder where wsgi.py file is).

-  The way to i excpect to work it's: User enter in the http://example.com/ domain, in a login page, the users are listed on the users django table of public schema. After the login the user goes to their specefic schema and log in the dashboard page as http://customer.example.com/.
As i searched in django-tenant-schemas who this project has forked, you can see it [here](https://github.com/bernardopires/django-tenant-schemas/pull/604). 

My project urlpatterns from myproject.urls: 
```
path("", include(login_urls)),
path('dashboard/', include(dashboard_urls)),
```
Also i read the docs, should i go on in this [way](https://django-tenants.readthedocs.io/en/latest/install.html?highlight=public%20url#tenant-view-routing)? And after [this ](https://django-tenants.readthedocs.io/en/latest/install.html?highlight=public%20url#separate-projects-for-the-main-website-and-tenants-optional)too?
I doesn't tried make like the github link i quoted, because i didn't understand ho to do it and don't know if will work in this project. I'm missing something? How does should work use public domain with public schema?

**Comment by Nicolas-SistemaFactoring** [comment]
My past tentatives:
-------------------------------------
✓ Works fine
```
PUBLIC_SCHEMA_URLCONF = 'myproject.urls'   
ROOT_URLCONF = 'myproject.urls'
```  
Only work when i put `myptoject.urls` in the `ROOT ` one.
_________________________________________________________
✗ Doesn't work
```
PUBLIC_SCHEMA_URLCONF = 'myproject.urls'   or whatever else
ROOT_URLCONF = 'dashboard.urls'            or whatever else, unless the 'myproject.urls'
```  
Also retrieve a `django.urls.exceptions.NoReverseMatch` error with `Reverse for 'login.views.login_name' not found. 'login.views.login_name' is not a valid view function or pattern name.`
___________________________________________________________

**Comment by Nicolas-SistemaFactoring** [comment]
It's possible to request this [commit ](https://github.com/bernardopires/django-tenant-schemas/pull/604)in this project?!

**Comment by tomturner** [comment]
You could use your own custom middleware. I do that I my own projects

**Comment by Nicolas-Coeficiente** [comment]
In my case a don't have capacity to do that, it's another level of coding. Can you indicate sources for do this?!

Also, are you sure the problem it's in middleware? It can't be another thing?
Based in what i saw that code i requested to commit would solve this thing(i guess), did you check the link?
