### ISSUE TITLE
Querying across tenants

### ISSUE THREAD

**Issue by adnathanail** [tomturner/django-tenants#309]
Just wondering if there is a good way to query data across tenants?

I would like to have records from the same model all as a part of the same QuerySet.

Currently I'm having to do .iterator() into lists for each schema and adding them together, but then I have to do dodgy hacks to get foreign keys/aggregations loaded.

**Comment by kosz85** [comment]
I had same problem in some point of time. But this is in fact not problem of ORM, but Postgresql. I suggest to create view for such query. And create django model on top of it to make queries from ORM.

**Comment by adnathanail** [comment]
Thanks for the quick reply!
When you say create a model on top of a view what do you mean?
Could you post a code snippet?

**Comment by kosz85** [comment]
You are very lazy :) Write in google `django model on database view`, I get this as first result:
https://books.agiliq.com/projects/django-orm-cookbook/en/latest/database_view.html

So seriously... you shouldn't be asking :)

**Comment by adnathanail** [comment]
I see, sorry!
I hadn't heard of "Database views" - I thought you were referring to Django views!
