### ISSUE TITLE
tenant -> shared app

### ISSUE THREAD

**Issue by brechmos** [tomturner/django-tenants#31]
I have an app that is listed in shared and tenants in the settings.py but it isn't showing up as shared when I add an object in one tenant (I don't see it in the other tenant).  It could be that I added the model to SHARED_APPS too late, but even when I do a makemigrations it doesn't pick up a change to that app (ie that it should be shared).

So... is there a way to make this model actually shared given it is in the SHARED_APPS list but doesn't appear to be shared?  

Or, is there something else I can check to see where the problem might lie (probably with me).

Thanks!

**Comment by MiltonLn** [comment]
I understood that shared apps are the applications that live on the public schema, not the applications that have the info shared to all tenants. Am i wrong?

**Comment by MiltonLn** [comment]
@brechmos the strategy that i've used to share information is loop on the tenants that i need:
i.e:
tenants = Tenant.objects.all()
for tenant in tenants:
   connection.set_tenant(tenant)
   ContentType.objects.clear_cache()
   # Do any stuff in the actual tenant, like queries or hit the databases...

As a recomendation i suggest to return to the actual tenant after you do your tasks.
'Tenant' is the app where you extend the TenantMixin in your models.

**Comment by brechmos** [comment]
Yeah, I use the Tenant loop method in one  place.

But I am actually wanting to see if I can move an app from the tenants (I
think I incorrectly added it there) to the public schema (which is better
worded than what I originally had).  If I need to create a new, public,
app, that is fine. I was just hoping to move the current one to the public
schema.

Craig

On Mon, Aug 17, 2015 at 11:06 AM, MiltonLn <notifications@github.com> wrote:

> @brechmos <https://github.com/brechmos> the strategy that i've used to
> share information is loop on the tenants that i need:
> i.e:
> tenants = Tenant.objects.all()
> for tenant in tenants:
> connection.set_tenant(tenant)
> ContentType.objects.clear_cache()
> # Do any stuff in the actual tenant, like queries or hit the databases...
>
> As a recomendation i suggest to return to the actual tenant after you do
> your tasks.
> 'Tenant' is the app where you extend the TenantMixin in your models.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomturner/django-tenants/issues/31#issuecomment-131855877>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by kosz85** [comment]
You can, but it's hard to not loose data.

The easiest way is to lost data and demigrate (migrate zero) your app, so you have no tables of this particular app in tenant schemas. Then move your app to SHARED_APPS and run normal migrations. That's all.
If you would leave old tables and just move it, then old tables would cover that from public schema in old tenants.

Of course there is also an option to do proper migration and not loose data, but this much harder, and you would need to write quite complex raw SQL.

**Comment by brechmos** [comment]
My case might be a little different as there is effectively no data in the
table. Any data in there I don't care if I lose.

So, if I were to go this route, I would have to create a migration that
removes all fields and the model?  I am not sure I understand that part.

On Tue, Aug 18, 2015 at 1:17 AM, kosz85 <notifications@github.com> wrote:

> You can, but it's hard to not loose data.
>
> The easiest way is to lost data and demigrate (migrate zero) your app, so
> you have no tables of this particular app in tenant schemas. Then move your
> app to SHARED_APPS and run normal migrations. That's all.
> If you would leave old tables and just move it, then old tables would
> cover that from public schema in old tenants.
>
> Of course there is also an option to do proper migration and not loose
> data, but this much harder, and you would need to write quite complex raw
> SQL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomturner/django-tenants/issues/31#issuecomment-132073473>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by kosz85** [comment]
No each migration can go forward an backward :) You can migrate to particular migration state from initial (0001) through each of next 0002, 0003..., also if you DB is in state 0003 you can migrate backward to 0002, 0001 or `zero` which is special point to reverse all existing migrations for this app.

Read the docs :) https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-migrate
Of course you will use `./manage.py migrate_schemas your_app zero`

**Comment by brechmos** [comment]
Hahah, clearly I have more document reading to do with migrations. Thanks!

On Tue, Aug 18, 2015 at 8:15 AM, kosz85 <notifications@github.com> wrote:

> No each migration can go forward an backward :) You can migrate to
> particular migration state from initial (0001) through each of next 0002,
> 0003..., also if you DB is in state 0003 you can migrate backward to 0002,
> 0001 or zero which is special point to reverse all existing migrations
> for this app.
>
> Read the docs :)
> https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-migrate
> Of course you will use ./manage.py migrate_schemas your_app zero
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomturner/django-tenants/issues/31#issuecomment-132188957>
> .
>



-- 


Craig Jones
craigj@jhu.edu
443-712-8152
mri.jhu.edu/~craig
Google Talk: brechmos
Skype: brechmos
FM Kirby Center, Kennedy Krieger Institute
Dept of Radiology, Johns Hopkins Medical Insitutes

**Comment by MiltonLn** [comment]
If you are in trouble with migrations you can do the following:
Delete the model from models.py, run makemigrations ans migrate, put again the model on models.py, run makemigrations and migrate.
It's a dumb solution i know, but i think it could help you

**Comment by brechmos** [comment]
Oddly, I appeared to have to come back to this and really needed a solution. I want to put it here to see if I am on the right track (and, if so, maybe it will be helpful for someone else).  I classes `Member` and  `Membership`:

```
member/models.py:
class member:
    lots of fields 

class Membership:
     member = ForeignKey(Member)
     other fields
```
The 'member' was listed in both the shared and tenant lists in the settings.py file.

I have another class:

```
station/models.py
class Station:
    more interesting fields
```

that was listed only in tenant.

I wanted to add a `station = models.ForeignKey(Station)` to the Membership class.  It threw errors saying "station_station" does not exist when I ran the `python manage.py migrate_schemas --shared`. 

So, I realized that I needed the station_station table in the public schema that was empty but had the same format as the station_station table in the non-public schemas.  So I did:

```
create table public.station_station as select * from nonpublicschema.station_station where 1=2;
create unique index "station_station_pkey" on public.station_station (id);
```

This let the migrate_schema --shared run to completion.  I think this is the correct solution but I would appreciate any possible places that I might be causing issues.

**Comment by kosz85** [comment]
You can use M2M filed and reference `member` in `Station`. 
```
member = ManyToManyField(Member, related_nam='_station')
```
Then add `@property` of name `station` that gets just first object or None.
```
@property
def station(self):
   return self._station.first()

@station.setter
def station(self, value):
   self._station.delete()
   self._station.add(value)
```
Smth like this.
If you think about it more, this is in fact M2M relation. You have 1 station per scheme, so you have many stations in fact for each member. You  can't handle it with single FK, as it can store only 1 value.
