### ISSUE TITLE
Django Rest Framework media

### ISSUE THREAD

**Issue by adnathanail** [tomturner/django-tenants#310]
Quite a specific use case here, so let me know if this is the wrong place to post this

I have an API for my tenant table using Django Rest Framework, and it is accessed through the public tenant
This means that all media urls then have /public/ instead of /<schema_name>/
Has anyone done this before/know a workaround so that the media urls will have the correct tenant?

**Comment by kosz85** [comment]
Overwrite field and create your own, as probably this is what you have problem with.

**Comment by adnathanail** [comment]
@kosz85 Sorry for the late reply on this
Do you mean create my own DRF serializer field?

**Comment by kosz85** [comment]
@adnathanail both assumed solutions are right, it all depends on your code. If it's django field problem (and it can be), fix it there, if it's only at DRF level, create your own. Do not be afraid to modify things, especially using django-tenants, as multiple things needs to be adjusted, sometimes whole libs has to be modified to play nicely with multiple schema DB, that's how it is.

**Comment by adnathanail** [comment]
Fair enough! Thanks for the help 😁
