### ISSUE TITLE
Deployed on Heroku, get AttributeError: 'DatabaseWrapper' object has no attribute 'schema_name'

### ISSUE THREAD

**Issue by maxwesterback** [tomturner/django-tenants#316]
The solutions I find are for the "old" tenant_schemas and they don't work anymore. When I try Heroku run python manage.py migrate_schemas --shared I get:
  File "/app/.heroku/python/lib/python3.6/site-packages/django_tenants/routers.py", line 37, in allow_migrate
    if connection.schema_name == get_public_schema_name():
AttributeError: 'DatabaseWrapper' object has no attribute 'schema_name'

**Comment by maxwesterback** [comment]
Added this to the end of settings file:

config = locals()
django_heroku.settings(config, databases=False)
# Manual configuration of database
conn_max_age = config.get('CONN_MAX_AGE', 600)  # Used in django-heroku
config['DATABASES'] = {
    'default': dj_database_url.parse(
        os.environ['DATABASE_URL'],
        engine='django_tenants.postgresql_backend',
        conn_max_age=conn_max_age,
        ssl_require=True
    )
}

**Comment by nifex007** [comment]
Using 
`import dj_database_url`
`import django_heroku`

In the Database section in setting 

```
DATABASES = {
      'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            engine='django_tenants.postgresql_backend',
            conn_max_age=600,
            ssl_require=True
        )
    }
```

At the bottom of `settings.py`

django_heroku.settings(locals(), databases=False)

**Comment by iamunadike** [comment]
How do I create django tenants database on github actions deploy? what steps for the database section
