### ISSUE TITLE
Migrating single-tenant to multi-tenant (again .. sorry.... )

### ISSUE THREAD

**Issue by bharling** [tomturner/django-tenants#318]
Hi, 

We in the position where we have a large production app live at the moment serving in the order of several hundred clients and need to move to a multi-tenant solution. Currently we're segregating data via foreign keys to client models, but definitely need to move to a schema segregation approach like django-tenants provides. 

The example in the docs #264 using dumpdata and loaddata definitely won't cut it for us, it'd involve days of downtime which we can't afford unfortunately. I saw it mentioned that a custom django management command would be the way to go to migrate single tenant data to multi - is there some example of a management command for this or a scaffold that we could start with?

Also - what are the actual implications of running migrate_schemas on a populated database? is it just impossible or is there some safe way to do it?

sincere thanks for any help!

**Comment by kosz85** [comment]
There is no such magic, think how it could work? You need to create new django tenants application, with all code adjustments of your original code, then you have to migrate data.
On your place I would connect new db with old one, and do the data mapping, so in fact copy, it would be like creating db views of old data in the way to present it in new way. Then you can develop it without turning off the old one. And when it's ready, copy and switch. You could have less downtime if you would add triggers to copy data in real time.

But I would think if this is really good solution? Why you think django-tenants would solve your problems? What problems you are experiencing? This for example won't solve performance problems, this only isolates data, and allows you to easily add/delete/hold and partially backup (some of data are shared) clients. In fact performance can be worse in some cases.

**Comment by bharling** [comment]
It's more a compliance issue for us in terms of guaranteeing isolation of client data in a demonstrable way. That is the main issue we need to solve, our clients are in a bunch of different industries some with quite stringent security criteria. We're also pursuing ISO27001 certification for which we'd benefit from using schema segregation of client data.

Triggers to copy the data across does sound like something to look into though thanks

**Comment by bharling** [comment]
I'd still be interested to know the actual implications if running migrate_schemas on a populated database though from a technical perspective if any one has any insight into that?

**Comment by kosz85** [comment]
Ok, if you want isolation then it's valid reason to migrate.
If you run migrate_schemas then what could happen? Your DB is `public` schema for default, you will have new public tables in your old DB, and when you will have some more schemas, that tables would be already isolated in there. You can dump DB, restore it somewhere and test this approach :)

You can also try alter public schema rename it to smth different like `old_base` and create new empty `public` schema to isolate new from old. In your old app, you would need to change search_path to use this `old_base` for default. Or do the opposite (which I do not recommend), change default django-tenant `public` to smth different like `base`.
Then you can migrate data.

In fact you can build app on your old code, you can add all existing code as shared apps, this means it will be in `public` schema, then create new  tenant apps, and migrate the data like this.
I don't know which approach is better (to share code or not), it's choice revolution over evolution. Both has good and bad sides. Sharing code and evolution would be a mess for some time ;) Especially that you are not experienced in working with schemas and will make some mistakes for sure. It's not that easy with migrating too, as migrations is slower - you need migrate each client schema. Without good approach and solutions like switching code version depending on schema migration state, you want be able to have almost no downtime updates, as you will have to down app, update code and wait till all schemas migrate, to not experience 500 errors with new code working on old tables or old code working on new tables.  I support app where we discussed this problems already, not to mention that sometimes migration can hang up when done on working app - that's worst thing for live updates.
