### ISSUE TITLE
Why is customer in shared apps?

### ISSUE THREAD

**Issue by maxwesterback** [tomturner/django-tenants#319]
Hi so I've set up a django app according to the tutorial with multiple tenants with their own schemas. Why do I need the customer app in shared_apps? I've moved it to tenant_apps and nothing changed. Is it so that I as the superuser can view all my tenants and when I create users for the tenants I make it so that they can't view the client app?

**Comment by kosz85** [comment]
You moved `Client` model , but you didn't removed this table from DB :) Try dropping DB, and start again, it won't work. It's not that you need customer app in shared_apps, you need `TenantMixin` model in shared app. Please familiarize with schema aproach and this article: https://web.archive.org/web/20160311212239/https://msdn.microsoft.com/en-us/library/aa479086.aspx

You want be able to access your tenants not knowing about them. And you won't know if you won't have TenantMixin in your public schema.
