### ISSUE TITLE
Create tenant on signup and permissions?

### ISSUE THREAD

**Issue by brandc87** [tomturner/django-tenants#321]
Hi, just a quick question more on usage rather than an issue, I have tenants installed and working just a few questions.

Is it possible to auto create the tenant say on user sign up? If two additional fields on the form are for name and domain?

I see that any requests made to tenant.my-domain.com will use that tenant, so are permissions something we need to add in to stop any user just typing any tenant domain and getting access?

**Comment by kosz85** [comment]
Yes you can, but you need to develop such form (for example inherit from standard register form) and create your tenant when handling this form POST data.

About second question, I'm not familiar with current state of work, but answer is rather obvious :) yes, you need to develop some kind of permissions.

**Comment by tomturner** [comment]
Have you watch my video?
