### ISSUE TITLE
Resolve subdomains for tenants in production with Nginx

### ISSUE THREAD

**Issue by Ngahu** [tomturner/django-tenants#327]
I have a project using django-tenants .On localhost , I can access `localhost:8000` and `tenant.localhost:8000` pretty fine. However, in production, only the public tenant is loading the other tenants can't be reached. What could be the issue?

Here is my ALLOWED_HOSTS = `['.example.com']`
and my Nginx conf is as below;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name *.example.com;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/ubuntu/projects/myproject;
    }
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}

**Comment by tomturner** [comment]
Have you got a wildcard in your DNS settings

**Comment by Ngahu** [comment]
Just added it and it has worked. Thanks!!

**Comment by tomturner** [comment]
@Ngahu No problem 😄

**Comment by alxroots** [comment]
@Ngahu I am facing the same problem, what is wildcard you have put on your solution? how did you set it up? Thanks

**Comment by Ngahu** [comment]
On your DNS Management page create a type A record and use * as the Host Name

**Comment by drayendrff** [comment]
I created a wildcard but it seems that it is not calling django to redirect on nginx on ubuntu

**Comment by drayendrff** [comment]
> 
> 
> Have you got a wildcard in your DNS settings

I have the wildcard A DNS with * but when I try to access the subdomain it doesn't display the login page
