### ISSUE TITLE
Permissions bug when `contenttypes` are in both `TENANT_APPS` and `SHARED_APPS`

### ISSUE THREAD

**Issue by 5starkarma** [tomturner/django-tenants#329]
I think this is a big bug in django tenants.

I moved my `auth` and auth user model to the `SHARED_APPS` and my permissions stopped working. The permissions are applied to groups and then users are applied to the group they belong in. 

This is my settings.py:
```
SHARED_APPS = [
    'django_tenants',

    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.companies',
    'apps.employees',
    'crispy_forms',
]

TENANT_APPS = [
    'django.contrib.contenttypes',

    'apps.categories',
    'apps.invite',
    'apps.memos',
    'apps.notifications',
    'apps.report_bug',
    'apps.videos',
    'apps.phone_verify',
    'apps.quiz',

    'django_cleanup',
]
```

It seems my whole permissions system is broken. To give an example.. in my admin panel when looking at the permissions in the admin panel you see:

```
admin | log entry | can add User Progress
auth | group | can add True/False Question
contenttypes | contenttype | Can view email message
```
This makes no sense. It is like my permissions are not lining up with their category..

Thoughts on what can be done to fix this?

**Comment by 5starkarma** [comment]
This is a bug that is actually recommended in the documentation. I don't understand why but it says to put contenttypes in the TENANT_APPS. Problem is it mixes up the permissions when you do this. Some are missing and some are gone. How to fix this? Remove `contenttypes` from `TENANT_APPS`

**Comment by kosz85** [comment]
Did you tested it on clear DB? If not, then removing any app from `TENANT_APPS` do not remove tables from schemas.  So you really can mess your DB this way.

This recommendation is not a bug, I use it in production environment for 6 years already.

**Comment by 5starkarma** [comment]
> Did you tested it on clear DB? If not, then removing any app from `TENANT_APPS` do not remove tables from schemas. So you really can mess your DB this way.

Yes, on two different projects on several new databases I am able to duplicate this bug.

> This recommendation is not a bug, I use it in production environment for 6 years already.

The result of the recommendation happens to be a bug. 

> How to fix it? Revert tenant migrations of apps you want to remove before removing them, use `zero`:
> https://docs.djangoproject.com/en/3.0/topics/migrations/#reverting-migrations

I tried removing all migrations and starting fresh with new databases every time I changed a setting. These are fresh databases and fresh migrations.

**Comment by quinceleaf** [comment]
I'm seeing similar behavior suddenly (permissions "jumbled"). Been in production for a year with one tenant, everything fine, with `contenttypes` in both `SHARED_APPS` and `TENANT_APPS`

Last week in preparation for adding 3 new tenants, upgraded django-tenants from 3.4.1 to 3.5.0 and from psycopg2 to psycopg3... so when I saw the jumbled permissions in the new tenants I first assumed the upgrade was responsible, but behavior persists even rolling back to previous versions

Haven't removed any apps.

When creating new tenants, the permissions for the new tenants is jumbled. And the count of the permission names is incorrect, so not merely shuffling between them.

Have a `Settings` model in each of 8 project apps. In the older app, the permissions are correct (and there are 8 of them for each of the default actions):

```
<Permission: common | settings | Can view settings>
<Permission: financial | settings | Can view settings>
<Permission: landing | settings | Can view settings>
<Permission: masterdata | settings | Can view settings>
<Permission: production | settings | Can view settings>
<Permission: purchasing | settings | Can view settings>
<Permission: tenants | settings | Can view settings>
<Permission: users | settings | Can view settings>]>
```

For new tenants, only 5 permissions are created, and the `app_model` listed for two of them are incorrect :

```
<Permission: financial | settings | Can view settings>
<Permission: masterdata | equipment cost | Can view settings>
<Permission: masterdata | item price | Can view settings>
<Permission: tenants | settings | Can view settings>
<Permission: users | settings | Can view settings>]>
```

And the exact same 5 results above occur across may 20 tenant creations, both with 3.4.1 and 3.5.0
