### ISSUE TITLE
Accumulative QuerySet 

### ISSUE THREAD

**Issue by danielcb29** [tomturner/django-tenants#33]
Hello! 

I am using the component to build a multi-tenant application. 

I am trying to collect all tenants information making an accumulative queryset using the method:

for t in tenants:
  connection.set_tenant(entidad)
  ContentType.objects.clear_cache()
  query = query | Class.objects.filter(some attr)

When loop change and tenant set to other one the queryset will execute in the current tenant , It is because of lazy django querysets however I thinks that you can have the same problem and maybe could have the solution. 

I need the query sets because the filter method and other powerful functionalities of it

**Comment by kosz85** [comment]
You can't do that like that. Each Class table is in fact different and separate table. It's like you would like to join Cars, Planes and Humans models. They have same same structure, but this are different tables. You can't have aggregated it in one django query - table rows have not unique ids as each starts from 1.
What you can do:
1. Raw SQL - if you do only 1 query it's fastest solution
2. Create Postgres View that will join all data in that tables in one table, add django Model to it, then you can use it.
3. I know that there are plenty of other possibilities, as postgres is powerful tool, but you will need help from someone better informed.
