### ISSUE TITLE
dist-info django version typo

### ISSUE THREAD

**Issue by tomaszsluszniak** [tomturner/django-tenants#331]
Hi, 
I'm using `Django 3.0.1` and I would like to use `django-tenants` (v. 2.2.3), but while installing it my Django version is downgraded to `2.2.9`. As it is in setup.py `Django 3.0.1` should be supported:
```
install_requires=[
        'Django >= 2.1,<3.1',
        'psycopg2',
    ],
```

When trying to install `django-tenats` I'm getting `ERROR: django-tenants 2.2.3 has requirement Django<3.0,>=2.0, but you'll have django 3.0.1 which is incompatible.`.

I noticed that `METADATA` file in dist-info has: `Requires-Dist: Django (<3.0,>=2.0)`. Is this a typo?

**Comment by tomturner** [comment]
This is because I haven't released the Django 3 compatible version yet. I am working on it. You can try and use the dev version if you like however it hasn't been tested
