### ISSUE TITLE
Order of SHARED_APPS + TENANT_APPS causes import errors

### ISSUE THREAD

**Issue by ivome** [tomturner/django-tenants#34]
In the documentation we have the following line in the installation guide. 

```
# settings.py
INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))
```

The problem with this is that it changes the order of the apps. I ran into import errors because some models were imported before the app was loaded:

model doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

To fix that I change it to the following: 

```
# Add shared apps to installed apps
INSTALLED_APPS = list(SHARED_APPS)
for app in TENANT_APPS:
    if app not in INSTALLED_APPS:
        INSTALLED_APPS.append(app)
```

That works for me, but maybe other's need the TENANT_APPS first... Opinions?

**Comment by kosz85** [comment]
Maybe better would be:
```
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
```

In my project I don't have duplicates and I have just: `INSTALLED_APPS = SHARED_APPS + TENANT_APPS` and it works :)

**Comment by tomturner** [comment]
I do

    INSTALLED_APPS = list(set(SHARED_APPS + TENANT_APPS))

I you happy that I can close this ticket?

**Comment by ivome** [comment]
I would change it in the docs to the line suggested by @kosz85 

You might not run into any problems, but if you have apps where the order matters, for example one app overwriting the templates of another, you will run into issues. I'll make a pull request when I find the time.

**Comment by tomturner** [comment]
The django-tenant-schema project has the same ticket 
https://github.com/bernardopires/django-tenant-schemas/pull/287

they are going for

INSTALLED_APPS = list(OrderedDict.fromkeys(SHARED_APPS + TENANT_APPS))

I still think this project is correct what do you think?

**Comment by ivome** [comment]
Looks like the same to me. Same issue, different solution, same result. I tested the performance for both out of curiosity. Ours seems to be 12x faster :dancers:  Not that it matters in this case... I think we should be fine with your fixes. Thanks btw!

**Comment by tomturner** [comment]
Thanks for the research I will now close the ticket.
