### ISSUE TITLE
v3 release notes

### ISSUE THREAD

**Issue by adnathanail** [tomturner/django-tenants#343]
Hi would it be possible for you to add release notes to v3?

The GitHub release says "Notes to come"
https://github.com/tomturner/django-tenants/releases/tag/v3.0.0

And the CHANGES file says "UNRELEASED" with very minimal other explanation
https://github.com/tomturner/django-tenants/blob/master/CHANGES.rst

**Comment by tomturner** [comment]
Dome

**Comment by adnathanail** [comment]
@tomturner Legend!
