### ISSUE TITLE
django-tenants vs django-schema-tenants

### ISSUE THREAD

**Issue by onno-timmerman** [tomturner/django-tenants#347]
Hi,

I see there are 2 very similar packages. This one is forked from django-schema-tenants

Is there a reason why to chose one above the other? 
Are the features on par? 
I'm wondering about long term maintainence? And if you start using one or the other it confusing what to pick.

**Comment by tomturner** [comment]
@onno-timmerman This has been asked many times.   A short answer is that django-schema-tenants seemed dead when I created this project. As I needed this for a project I was doing for work I forked it. I still require this project as this project is ongoing. Most of the  features are on par.

**Comment by onno-timmerman** [comment]
Thx for the answer... So you will not be dropping support for it in the for seeable future? 
Great thx for the swift reply. It think I'll go for django-tenants as the documentation is a bit better.

**Comment by tomturner** [comment]
No I won’t be dropping it for a long time.

**Comment by atodorov** [comment]
I think this can be closed
