### ISSUE TITLE
contenttypes in SHARED_APPS and use of GenreicForeignKey in TENANT_APP

### ISSUE THREAD

**Issue by theiviaxx** [tomturner/django-tenants#348]
This is stemming from me putting contenttypes in bot SHARED and TENANT app lists, however this is causing contenttype cache corruption and my generic foreign keys are getting the wrong content_type_ids.  So i was going to just move contenttypes into SHARED and remove from TENANT, but that leaves me to deal with the constraints on the contenttypes table.

That brought up another question though, is if my contenttypes table is in public, can i even create constraints from a tenant schema table to a public schema table?

**Comment by theiviaxx** [comment]
nvm, you can make a FK contraint to a different schema, i just need to do a migration.

Thanks

**Comment by yujinyuz** [comment]
Hi @theiviaxx do you mind sharing your solution?

I'm not sure I understand the `you can make a FK contraint to a different schema`

**Comment by theiviaxx** [comment]
@yujinyuz my tenant schemas had their own `django_content_type` tables that had different values for different content types across tenants.  I also had a model with a generic constraint, so when those objects were queried, they would sometimes get the wrong content type and all hell broke lose.  After reading a bit, this was apparently a bad idea and `django.contrib.contenttypes` should only go into the `SHARED_APPS` list.

I was somewhat lucky in that i just had to modify the existing constraints that were on the tenant tables to point to the public schema tables:

`tenant.django_content_type > public.django_content_type`

Once this was done i just had to fix the existing generic relation objects to point to the correct content type id.

If you are still in development and _can_ do it, move that package to SHARED only and redo your migrations and migrate again :)
