### ISSUE TITLE
How to findout which data is particular tenant data?

### ISSUE THREAD

**Issue by vijaykumar0425** [tomturner/django-tenants#352]
Hi team,
we have 10 tenants, so that time how to find out which data is particular tenant data?

**Comment by user37596** [comment]
You can't know it directly from the queryset or its results. It depends on which tenant was active when you evaluated the query. You can check the active tenant from `from django.db import connection; connection.tenant`.

**Comment by marcoaaguiar** [comment]
The middleware also also appends the tenant to all request in `request.tenant`
