### ISSUE TITLE
Apply Management Command to all tenants (but not to public schema)

### ISSUE THREAD

**Issue by marcoaaguiar** [tomturner/django-tenants#354]
I have a command from another package that I want to be applied to all the tenants but not to the public schema. Accordingly to the documentation I can apply to specific tenant using `tenant_command` but I couldn't find a way to apply it to every tenants without iterating overt all tenants (which I don't know without loading the DB) using `tenant_command`.

It would be nice to have a `all_tenants_command` if there isn't one, it would save the effort of having to extend all commands to inherit from `BaseTenantCommand`.

Best,
Marco

**Comment by tomturner** [comment]
@marcoaaguiar  I think this should do the trick

**Comment by paolosanchez** [comment]
Hi Tom @tomturner,
I tried to use this command to do a backup of the database, with all the schemas, and hope to used as well to load the data again.
">python manage.py all_tenants_command dumpdata -o pDB.json"
But, only got a list of the args used and no output file.
Did I use it wrong? Do you know a better way to do a backup? 
I am new to Web development, and software engineering. Maybe the question is trivial.
