### ISSUE TITLE
Django 3 compatibility

### ISSUE THREAD

**Issue by AlgoAdmin** [tomturner/django-tenants#355]
Hello,

I have a question, is this package compatible with the brand new version of Django 3.0.5? 
Is it worth a try using it, or are there any known issues or plans for supporting it in the future?

I have to make a decision of which version of Django to use.

Thank you

**Comment by atodorov** [comment]
It is. I am using it for Kiwi TCMS multi-tenant in production as of right now and we have a very aggressive upgrade policy.

The latest test in CI was about 2 months ago and the log shows it fetched Django 3.0.3. If you want to check-out 3.0.5 just fork the repo, enable Travis CI for you own fork and push a small change to readme to give it a try.

**Comment by AlgoAdmin** [comment]
Thanks a lot!
