### ISSUE TITLE
Configure pyup.io and/or dependabot

### ISSUE THREAD

**Issue by atodorov** [tomturner/django-tenants#356]
@tomturner  I see that requires.txt has Django 3.0.3 and b/c there have been no pull requests or changes recently the latest execution in Travis is about 2 months ago. 

How about enabling pyup.io and/or dependabot to monitor for dependency updates and automatically open pull requests, which will then kick off tests? I am using both of these services (they are duplicate) on all of my repos and they work kind of nice. 

Dependabot is smarter (will automatically rebase & close PRs) but pyup.io seems to be faster - opening pull requests as soon as it detects something on PyPI.

**Comment by tomturner** [comment]
@atodorov What a good system. I have enabled pyup.io
