### ISSUE TITLE
Single login endpoint

### ISSUE THREAD

**Issue by c-castillo** [tomturner/django-tenants#36]
Hi,

I'm using this library to implement multitenancy. I'm serving an API with djangorestframework.
I need a single endpoint to perform login (i.e http://mycompany.com/login) and then the login redirect to the user tenant ( http://sometenant.mycompany.com)
User data needs to be stored in each tenant.

Is that possible at this moment?

Thanks in advance,

**Comment by tomturner** [comment]
As far as I can tell you have 2 choices.
 1: Make your users unique across all tenants. If you do this you might as well store the user data in the main model as you can still have a FK to it in tenant model
 2: Ask for a schema, domain name or something else from the tenant model as well as the username and password

**Comment by c-castillo** [comment]
I used option #2 to fix this problem.

**Comment by tomturner** [comment]
@c-castillo glad it worked
