### ISSUE TITLE
TenantFileSystemStorage

### ISSUE THREAD

**Issue by jtangir87** [tomturner/django-tenants#382]
I have multiple apps running django-tenants so first .. thank you! My app running 2.2.3 is functioning great. However, I just started a new one and installed 3.0.1. The uploaded files are storing in the correct file structure, however, the image url does not include the correct path. It is skipping the folder for the tenant name. 

This is what django inserts into the template:
`<img class="img-fluid img-thumbnail" src="/media/photos/image6.jpg" alt="">`

This is the correct file path:
`<img class="img-fluid img-thumbnail" src="/media/t1/photos/image6.jpg" alt="">`

**Comment by jtangir87** [comment]
please disregard. Removing MULTITENANT_RELATIVE_MEDIA_ROOT = "" from settings.py resolved the issue.

**Comment by tomturner** [comment]
@jtangir87 Does this mean the ticket can be closed?

**Comment by jtangir87** [comment]
yes, thank you!
