### ISSUE TITLE
SQL_IDENTIFIER_RE doesn't seem compatible with hostname specification

### ISSUE THREAD

**Issue by atodorov** [tomturner/django-tenants#385]
In https://github.com/tomturner/django-tenants/blob/master/django_tenants/postgresql_backend/base.py we've got `SQL_IDENTIFIER_RE = re.compile(r'^[_a-zA-Z0-9]{1,63}$')` which per Postgres docs verifies that the schema name is correct. 

However debugging an issue on my end I think you can't have underscores b/c they seem to be forbidden in hostnames, see https://stackoverflow.com/a/14622263/1431647 (I didn't go through all RFCs).

Also I don't think the upper-case characters will play nicely with hostnames as well.

I was able to create a teanant with schema_name `debug_me` but when I tried visiting `debug_me.tenants.example.com` I got a 400. Trying an arbitrary domain for non-existing tenant gives me 404 (app is configured to check for this). 

@tomturner what do you think of this? I am in favor of restricting the above mentioned regex only to lower-case characters.

**Comment by tomturner** [comment]
Remember schema names can be different to domain name. I have a schema name with an underscore in it and it works fine.  underscores in sub domain are allowed https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it.

I think we should stop people from creating schema names and domain names with mixed case so i suggest with stop uppercase characters.

**Comment by tomturner** [comment]
@atodorov Do you want to do the pull request for that?

**Comment by atodorov** [comment]
I did try a sub-domain with underscore and it failed for me but I think there may have been an issue with how the actual environment is setup.  I will experiment a bit more and follow up with that PR.

**Comment by tomturner** [comment]
@atodorov On another point to do with the same sort of think.  I was just about to rename `_is_valid_schema_name` to `is_valid_schema_name` as I needed to access it inside my project and at the moment it gives a pep8 error

**Comment by tomturner** [comment]
I just tried it and got 

> Invalid HTTP_HOST header: 'demo_demo.myproject.local:8080'. The domain name provided is not valid according to RFC 1034/1035.

**Comment by tomturner** [comment]
Maybe we do need to stop people using underscore in the domain names
