### ISSUE TITLE
Update clone_schema function to use pg_roles instead of pg_authid

### ISSUE THREAD

**Issue by abhishektiwari** [tomturner/django-tenants#393]
Most of the Database as a service offering including RDS and Heroku Postgres doesn't allow superuser access. Schema cloning will fail with the following error

```
InternalError: Action: Collations  Diagnostics: line=SQL statement "SELECT n.nspname as schemaname, a.rolname as ownername , c.collname, c.collprovider,  c.collcollate as locale,
    'CREATE COLLATION ' || quote_ident(dest_schema) || '."' || c.collname || '" (provider = ' || CASE WHEN c.collprovider = 'i' THEN 'icu' WHEN c.collprovider = 'c' THEN 'libc' ELSE '' END || ', locale = ''' || c.collcollate || ''');' as COLL_DDL
    FROM pg_collation c JOIN pg_namespace n ON (c.collnamespace = n.oid) JOIN pg_authid a ON (c.collowner = a.oid) WHERE n.nspname = quote_ident(source_schema) order by c.collname"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 112 at FOR over SELECT rows. 42501. permission denied for table pg_authid
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean) line 669 at RAISE
```

By using `pg_roles` instead of `pg_authid` we can bypass this issue. I tested this change using a non-super-user locally and cloning worked. Now I am trying to test on Heroku but I am quite sure it will work.

I also checked [original script](https://github.com/denishpatel/pg-clone-schema) which is updated and now uses `pg_roles` instead of `pg_authid`

I am happy to send a pull request.

**Comment by lorinkoz** [comment]
I think this is done in master via https://github.com/tomturner/django-tenants/pull/381

**Comment by abhishektiwari** [comment]
Aha thanks @lorinkoz. I will close this issue then.
