### ISSUE TITLE
Can't automatically create a user within a schema?

### ISSUE THREAD

**Issue by flxfxp** [tomturner/django-tenants#4]
Hey Tom,
I've been busy trying to upgrade my app to Django 1.8 and django-tenants, but I've run into a snag.
My site has frontpage a form that:

1. Creates a Tenant
2. Logs into the Tenant by changing connection.set_tenant
3. Creates an superuser + Profile (works)
4. Creates a user + Profile based on form data (doesn't work)

It complains that it can't create a userprofile as it can't find the user in the database, which is untrue, because when I query the database before creating the profile, the user is present. Full error:
```
insert or update on table "webapp_core_userprofile" violates foreign key constraint "webapp_core_userprofil_user_id_4658f19604daf576_fk_auth_user_id"
DETAIL:  Key (user_id)=(2) is not present in table "auth_user".
```

My code:
```
    domain_urls = str(domain_urls[0]) #convert array field to string

    # Log into client schema
    newTenant = Customer.objects.get(domain_urls__contains=[domain_urls])
    connection.set_tenant(newTenant)
    ContentType.objects.clear_cache()

    # Create superuser
    from django.contrib.auth.models import User
    admin = User.objects.create_superuser(settings.SYSADMIN['username'], settings.SYSADMIN['email'], settings.SYSADMIN['password'])
    admin.first_name = settings.SYSADMIN['first_name']
    admin.last_name = settings.SYSADMIN['last_name']
    admin.save()
    # Add superuser to UserProfile
    from webapp_core.models import UserProfile
    adminprofile = UserProfile(user=admin)
    adminprofile.fresh_account=False
    adminprofile.save()

    # Create user
    user = User.objects.create_user(username=email, email=email, password=password)
    user.is_staff=True
    user.save()
    # Create userprofile
    myuser = User.objects.get(id=user.id)
    userprofile = UserProfile(user=myuser)
    userprofile.primary_owner=True
    userprofile.fresh_account=True
    userprofile.needs_password=False
    userprofile.save()
```

It's weird because it does work when creating a superuser but doesn't when I create a normal user. Any idea? Your help would be greatly appreciated :)

Thanks,
Dennis

**Comment by tomturner** [comment]
Do you think you can knock up a simple demo app with the problem in it?

**Comment by ivome** [comment]
Maybe you have one of the models in both SHARED_APPS and TENANT_APPS and it looks the data up in different shemas, depending on which tenant is activated? Just a guess, a demo app would be helpful.

**Comment by flxfxp** [comment]
Figured it out, pebcak :)
