### ISSUE TITLE
How could I integrate this project with cookiecutter-django?  

### ISSUE THREAD

**Issue by tkovalsky** [tomturner/django-tenants#43]
I need to integrate this project with the cookiecutter-django project.  What changes would I need to make to the settings?

https://github.com/pydanny/cookiecutter-django

Thanks!

**Comment by tomturner** [comment]
Cookie cutter gives you a basic project after you run it you should follow the instructions on https://django-tenants.readthedocs.org/en/latest/install.html

**Comment by tkovalsky** [comment]
Thanks tom...do I need to create the models as the first step?  Otherwise I have no models to sync against. 

Thanks for the help
