### ISSUE TITLE
Cannot create Tenants via Admin in 1.1.2

### ISSUE THREAD

**Issue by P0oky** [tomturner/django-tenants#48]
When adding a new Tenant via the default admin, the view processing is decorated with "transaction.atomic". If a postgres connection is closed while in a transaction, the server performs an automatic rollback. There is no exception thrown, nor error shown. The Tenant simply isn't created.

The connection is closed in migration_executors/base.py, lines 30-31. Commenting out these two lines seems to make adding a new Tenant work as expected.

I replicated this using the dts_test_project, adding this admin file:

<pre>
#customers/admin.py:

from customers.models import Client
from django.contrib import admin

class ClientAdmin( admin.ModelAdmin ):
    pass

admin.site.register( Client, ClientAdmin )
</pre>

**Comment by CGenie** [comment]
Here's a fix for this issue. It is impossible to assert atomic transactions for the `multiprocessing` executor. But for the `simple` one they can be atomic.

**Comment by tomturner** [comment]
@CGenie Can you create a pull request for changes

**Comment by CGenie** [comment]
Done :)

**Comment by P0oky** [comment]
Looks good, thank you folks.
