### ISSUE TITLE
Inconsistency with multiple domain_urls breaks whole page

### ISSUE THREAD

**Issue by ivome** [tomturner/django-tenants#5]
We have the problem, that the domain_urls values are not consistent. 
The ```CharField``` of ```domain_urls``` has ```unique=true```, but that only works for single values. 

For example I can create multiple tenants with the same domain, which is pretty bad and breaks the whole page:

```
tenant = Client(domain_urls=['tenant.my-domain.com', 'other.my-domain.com'],
                schema_name='tenant1',
                name='My First Tenant',
                paid_until='2014-12-05',
                on_trial=True)
tenant.save()

# Same domains reverse order does not throw exceptions
tenant = Client(domain_urls=['other.my-domain.com', 'tenant.my-domain.com'],
                schema_name='tenant1',
                name='My First Tenant',
                paid_until='2014-12-05',
                on_trial=True)
tenant.save()
```

I would vote to remove the option of multiple domain_urls and make it a single value again. That way we can properly build distinct reverse URLs that include the domain name, for example for confirmation emails etc. We can also properly create an index on the domain (which is lacking right now). If someone needs support for multiple domains, the middleware could be easily extended or it could be handled with a redirect to avoid duplicate content. 

Any opinions?

**Comment by tomturner** [comment]
Sorry one of the reason I did this project is to have multiple domain URL so I want to keep it!!! 
The reason I want multiple domains is it allows my customer to purchase a domain name and point it to a tenant. There was no easy way of doing this without this mod.

I know having it doesn't check for unique urls I except that needs to be done.

**Comment by tomturner** [comment]
@ivome Just been thinking can you not just use the first one in the list as the primary one. Perhaps we should provide an example middleware that forward all requests to the primary url. As I said I do want to keep this feature.

**Comment by flxfxp** [comment]
Hey Tom, I think that #4 might have to do with this issue as well, though I still need to look into this. Custom domains would indeed be nice, however it won't be that useful for me, as changing the domain name will break the SSL certificates, which are 100% necessary for me. Though I wonder about your usecase, would love to hear about it, maybe you know about a solution :)

**Comment by ivome** [comment]
I could do that, but that does not solve the issue of the unique constraint which should be handled on the DB level. With the array field we would also have to do some custom SQL to create a GIN index to make the queries fast. And they should be fast since this table is queried basically on each request. Also see: 
https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#indexing-arrayfield

The queries in other parts of the page might also need to be tuned (not sure right now how django exactly queries arrayfields). 

That would be a lot easier if we had only one value field.
For your usecase it might be best to keep the domains in a separate model, so you can store additional information like when they were added, paid_until, HTTPS enabled etc.

**Comment by tomturner** [comment]
I am 100% aware of SSL however my customers would also have to purchase that as well. The other reason I want multiple domain names is for development. My project hasn't gone live yet. For interest how many tenants do you have

**Comment by tomturner** [comment]
It also worth having two fields abstact class one domain_urls for user like me and another domain url for user like you.

**Comment by tomturner** [comment]
I did try and put domains in a different table however I ran into so many problem with migrations

**Comment by ivome** [comment]
I don't think we should go for the two way solution with domain_url and domain_urls, that would get confusing in documentation and we would have to implement two solutions in each part. For example tests, the test client etc. 

If we have two models we would have to implement that with swappable models like it is handled with custom user models in some apps. Doable but a little bit of work. 

I think it would be easier for your use case to just put the Domain data into a separate app and model and write a small middleware which sets the tenant and use that instead of the TenantMiddleware of django_tenants. If we keep it as it is right now, we still need to solve the issues mentioned above regarding indexing and unique values.

**Comment by tomturner** [comment]
Ok I will have a look at the options and we will work out the best way forward

**Comment by ivome** [comment]
Perfekt, I think I will try and give the approach with Domains in a separate model a shot.

**Comment by ivome** [comment]
I implemented a solution where we have two models, one for domains, one for tenants. Both are abstract models and can be extended with anything. Check out my commit and let me know what you think. How to use is described in the readme: https://github.com/ivome/django-tenants/tree/develop

I like this idea more and more: As a nice side effect we can now pre-generate tenants without running into the issues of unique constraints when we don't know the users domain yet. 
The user then does not have to wait for the whole migration to complete, we can just connect a domain with an unused tenant and the instance is instantly available. 

While implementing I also found out that the solution with domain_urls that we currently have breaks the template_loaders. So that could be solved with the change too. 

Any feedback is welcome. If you like the solution, I can finish that up and make it clean. Also let me know if you run into any problems with migrations, I didn't have any issues so far.

**Comment by flxfxp** [comment]
I like it, a very clean solution to the problem, best of both worlds!
@tomturner what do you think?

**Comment by tomturner** [comment]
I am happy with the use of off another adstract class. I was going to do the same sort of fix today. Can you create a pull request

**Comment by gannetson** [comment]
+1 for the related model with domain_urls. That was I was thinking too.

**Comment by ivome** [comment]
The basic functionality should work with the code from the pull request. There are still a few things left to be done: 

- Testing in general, I only briefly checked this
- Check documentation and update
- Fix and test template_loader
- Unittests

Since I won't have time to work on it for the next days I created the pull request without the complete update. Feel free to merge and fix the remaining stuff.

**Comment by tomturner** [comment]
Thank you very much i will look at doing this.

**Comment by tomturner** [comment]
All the left is to write some unittests

**Comment by ivome** [comment]
Thanks for the merge and the updates!
