### ISSUE TITLE
Should django.contrib.contenttypes be in TENANT_APPS?

### ISSUE THREAD

**Issue by suriya** [tomturner/django-tenants#53]
This question is regarding the `django.contrib.contenttypes` app. The documentation specifies that this app should be present in `TENANT_APPS` https://django-tenants.readthedocs.org/en/latest/install.html#configure-tenant-and-shared-applications Could someone please explain why this is the case?

I think that having `django.contrib.contenttypes` only in `SHARED_APPS` is sufficient. The `ContentType` model and its corresponding `django_content_type` will reside in the `public` schema and will contain definitions for all models (shared and tenant-specific).  There is no harm in the table referring to tenant-specific models. You only need to ensure that when you lookup objects from a tenant-specific model, you have set the tenant.

If we do so, we don't have to clear the `ContentType` cache in `TenantMiddleware.process_request`. https://github.com/tomturner/django-tenants/blob/master/django_tenants/middleware.py#L31

**Comment by kosz85** [comment]
I have it in `SHARED_APPS` and it works just ok, thought there might be some little problems when migrating after deleting some models, as it like to check that there are no more some of contenttypes and then it asks some silly questions ;) but `--noinput` fixes problem with silly questions ;)

**Comment by suriya** [comment]
Thank you for the answer. Just to clarify. you have it only in `SHARED_APPS`, right? Maybe the documentation has to fixed? https://django-tenants.readthedocs.org/en/latest/install.html#configure-tenant-and-shared-applications

The question when deleting modules is not because of `django_tenants`, right?

**Comment by kosz85** [comment]
Yes, only in `SHARED_APPS`, in fact I don't have any app from a lib in my `TENANT_APPS`, so all django goodies are shared.
Yeah I think it should be, create pull request ;)
I think that now in django 1.8 it's even impossible to have duplicated apps, so it shouldn't work anyway ;) I think it's in fact from older lib version, I  deleted it  when  migrating to django 1.8.

**Comment by suriya** [comment]
I think this issue should be re-opened. There are two steps to resolve this ticket. 1) Fix the documentation  to make it clear that `django.contrib.contenttypes` does not have to be present in both `SHARED_APPS` and `TENANT_APPS`.  2) Do not call `ContentType.objects.clear_cache()` if `django.contrib.contenttypes` is not in `TENANT_APPS`. https://github.com/tomturner/django-tenants/blob/master/django_tenants/middleware.py#L31
