### ISSUE TITLE
What is is_primary property for?

### ISSUE THREAD

**Issue by juanefren** [tomturner/django-tenants#54]
I don't see find anything in the repository about
https://github.com/tomturner/django-tenants/search?utf8=%E2%9C%93&q=is_primary

I was wondering this since today I realized I had incorrect set is_primary on all my tenants and was wondering If it could have affected my application in any way.

**Comment by kosz85** [comment]
Looks like smth that sets main domain, if you check `DomainMixin.save` method then there is response for question in comments. The question is if it's used by anybody ;) and if it should be really part of this lib.

**Comment by tomturner** [comment]
@juanefren Please see #4. And my comments about is primary.

**Comment by juanefren** [comment]
@kosz85 it just set is_primary=False to the rest of the domains of the same tenant.
@tomturner somehow I skipped get_primary_domain of TenantMixin since I use multiple domains mostly for versioning purposes of my application (eg. tenant.domain.com, tenant.beta.domain.com, tenant.dev.domain.com), building distinct reverse URLs (eg. notification urls) was always schema_name + domain. Thanks for the reference.
