### ISSUE TITLE
Django 1.9 Does it work?

### ISSUE THREAD

**Issue by tomturner** [tomturner/django-tenants#58]
Has anyone tried Django Tenants with 1.9. I will try it shortly

**Comment by JeancarloBarrios** [comment]
I tried it with the tutorial example it worked until the part of going to the tenant urls it throws a 404 error

**Comment by tomturner** [comment]
Thank you I will try and fix this soon

**Comment by tomturner** [comment]
I did the example project and it worked!!!

**Comment by 23doors** [comment]
Could you check the migrations for different tenants? I had some very strange results. Like: one tenant got migrated properly, second one got django_migrations populated and that's it, nothing else was done. Retrying worked so I figured that it is some kind of internal cache introduced in 1.9 (1.8 works).

**Comment by JeancarloBarrios** [comment]
yes, i tried Again and now it works just run it again. So what you are
saying sounds about right after that it keep working fine Great job by the
way.

Gracias por su tiempo y concideración
Jeancarlo Barrios
ACM Student Chapter Chair
CCTI vocal

**Comment by 23doors** [comment]
I wouldn't call it "working" when you need to retry for every separate tenant.

**Comment by 23doors** [comment]
On the other hand, it may have been unrelated issue I was facing. So ignore my previous comment.

**Comment by CGenie** [comment]
Well, our Travis tests run on 1.9 since in `setup.py` we have `Django >= 1.8`:

```nstalled /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/psycopg2-2.6.1-py2.7-linux-x86_64.egg
Searching for Django>=1.8.0
Reading https://pypi.python.org/simple/Django/
Best match: Django 1.9
Downloading https://pypi.python.org/packages/source/D/Django/Django-1.9.tar.gz#md5=110389cf89196334182295165852e082
Processing Django-1.9.tar.gz
```

(see https://travis-ci.org/tomturner/django-tenants)

**Comment by 23doors** [comment]
Good to hear! Sorry for all the confusion caused then guys. I may have personally just run into some unrelated issues with 1.9 then and misinterpreted strange results I was getting.
