### ISSUE TITLE
How does it differ from django-tenant-schemas

### ISSUE THREAD

**Issue by DataGreed** [tomturner/django-tenants#59]
How does this project differ from django-tenant-schemas? As I can tell django-tenants is a fork of django-tenant-schemas, though, I cannot figure out whic to use and why.

**Comment by kosz85** [comment]
django-tenant-schemas is less active developed and is less open for pull-requests. It was forked because it didn't support newer version of Django.
Now few improvements were made, better interfaces to Tenants like `tenant.activate()` or `with tenant:` to work on particular schema, that were proposed but never merged in django-tenant-schemas.
We have extension for parallel migrations, we use it for production env so it should be stable enough for other projects, and will be fixed when there would be any bug.
Our community is maybe smaller, but much nicer ;)

**Comment by DataGreed** [comment]
@kosz85 thanks you very much for the answer!

**Comment by tomturner** [comment]
@DataGreed It was forked when Django 1.8 came out. I tried to get changes into django-tenant-schema however my changes didn't go in (nor did I get any feedback). The change for 1.8 is now in to django-tenant-schemas he was busy at the time in came out. When I went to Django con euro I spoke to @gannetson and we decided to fork it as we thought django-tenant-schemas wasn't be developed. There are other changes that django-tenants has like parallel migrations thanks to @CGenie. We also have multiple domain support (I think that gone in to django-tenant-schemas). We have also drop support for anything below Django 1.8 as there was a lot of if conditions depending on version .

Hope this helps.

Tom

**Comment by EfraimGENC** [comment]
Finally I found my answer, I feel more comfortable now. Maybe It could be better explain this topic top on README file.. I was very confused till I find these answers.

**Comment by Sagar-Shah33** [comment]
Hi kosz85, I need your help. I am confused about which library is best to use Django-tenant library or the Django-tenant-schema library

**Comment by tomturner** [comment]
They are basically the same however Django tenant schema hasn’t been
updated for years. I created the fork years ago and actively maintain this
as it required for a large project I am working on.

**Comment by Sagar-Shah33** [comment]
@tomturner thank you very much for the answer!

**Comment by Sagar-Shah33** [comment]
The multi-tenant system is possible without using library in Django

**Comment by Sagar-Shah33** [comment]
Hi @tomturner, I Got this error "Can't create tenant outside the public schema. Current schema is CST." please help me how to fix it.

**Comment by olrrai** [comment]
I need to show users some things in real time (not too much). What is recommended as a starting point for using Django Tenants+Django Channels? And especially for scalability?
