### ISSUE TITLE
Add a way of cloning a tenant

### ISSUE THREAD

**Issue by tomturner** [tomturner/django-tenants#60]
I need to be able to clone a tenant.

**Comment by MiltonLn** [comment]
An excellent idea for performance testing, any examples of how to use it? thank you

**Comment by tomturner** [comment]
Use the management command
`clone_tenant`

**Comment by MiltonLn** [comment]
Cool, i'm attempting to do a process that takes a tenant and clones it a thousand times with data included, this command must be helpful to do this task right?

**Comment by tomturner** [comment]
Correct that what it does
