### ISSUE TITLE
relation "customers_client" does not exist

### ISSUE THREAD

**Issue by JeancarloBarrios** [tomturner/django-tenants#61]
Im getting this error whenever I try to save a tenant.
I'm using Django 1.9 with python 3

django.db.utils.ProgrammingError: relation "customers_client" does not exist
LINE 1: INSERT INTO "customers_client" ("schema_name", "name", "desc...
I have try the tutorial and it seems to work, but i cannot make it work outside of it.

**Comment by kosz85** [comment]
You need to write us some more input about your case :)
1. What schema you are using when you get this error? It looks like you are on `public` schema/tenant, and you try to fetch data from model in app from `TENANT_APPS`?
2. Where is model (from what app) `customers_client`?
3. Did you do anything to `PG_EXTRA_SEARCH_PATHS`?
4. Did you run migrations?
5. Where you get this error - shell, wsgi, celery, etc
6. Did you modify tenant save

In general, you try to use relation to some model that is not in your `search_path` (so it's not existing in public schema), or if it's error in create_schema, you try to reference table in migration that is not visible. Write more about your setup.

**Comment by JeancarloBarrios** [comment]
1. What schema you are using when you get this error? It looks like you are on public schema/tenant, and you try to fetch data from model in app from TENANT_APPS?

Yes it is public schema the very first one .

2. Where is model (from what app) customers_client?

The model Client is in and app called Customer just like in the documentation.

3. Did you do anything to PG_EXTRA_SEARCH_PATHS?

I'm not currently using PG_EXTRA_SEARCH_PATHS

4. Did you run migrations?

Yes i ran: python manage.py migrate_schemas --shared 

5. Where you get this error - shell, wsgi, celery, etc

I get this error in the shell, when i try to manually add the first public tenant
6. Did you modify tenant save
No, i did not modify the tenant save 

Will you like me to post my settings or something else?
thanks alot

**Comment by tomturner** [comment]
Try running the migrate_schemas without the --shared at the end.

If that doesn't work see if it has created the table customers_client in PostgreSQL

**Comment by JeancarloBarrios** [comment]
If I run it without the shared at the end i get the very same error
django.db.utils.ProgrammingError: relation "customers_client" does not exist
LINE 1: SELECT "customers_client"."schema_name" FROM "customers_clie...
It does not create a customers_client table
![screenshot from 2015-12-20 17-59-43](https://cloud.githubusercontent.com/assets/8561557/11921335/22179414-a744-11e5-9b0b-e286cfb0ce62.png)

**Comment by kosz85** [comment]
Yes, please paste `TENANTS_APPS` and `SHARED_APPS`, and code of your `customers.models.Client`.

**Comment by tomturner** [comment]
I was going to ask you to paste the migration file that add the customer client.

**Comment by JeancarloBarrios** [comment]
DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)
THIRD_PARTY_APPS = (
    'rest_framework',
    'django_tenants', 
)
MY_APPS = (
    'customers',
)

TENANT_APPS = (
    
'django.contrib.contenttypes',

)

SHARED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + MY_APPS
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

**Comment by kosz85** [comment]
Khem... ;)
First of all use backticks \`\`\` for pasted code, normally you have it before key `1`.
Second how you want to do anything without migrations? You need to generate them. First migration creates tables, so your actual DB.  Please read Django documentation and do some little project in core django before trying smth more complex :) This lib isn't easiest one, as problem is also not that easy.

Your error is caused by not having any tables - you just don't have any db tables.
Problem solved.

**Comment by JeancarloBarrios** [comment]
thanks a lot, i was not quite sure how this lib work, i just follow the tutorial   and thought python manage.py migrate_schemas --shared will replace the makemigrations, migrate from django core thanks a lot anyways

**Comment by dozie** [comment]
Hello @JeancarloBarrios how did you get past this issue. I've gone through the comments and I'm not sure I follow the solution

**Comment by kosz85** [comment]
He generate initial migrations, as he didn't have any, so they didn't exists.

**Comment by dozie** [comment]
Thanks for answering my question @kosz85. Unfortunately, I am still having the same issue
I am following the tutorial for the django-tenant-schemas as well. I have my application created and I ran the migration on the application (makemigrations <application>)  and that worked then I proceeded to migrate_schema on the public schema which worked.

However when I tried to create my client schema (which I'd believe should be the new schema) I run into a relation does not exist error. At this point I am not sure what the issue is as I have spent quite a bit of time trying to figure out why this is the case.

**Comment by kosz85** [comment]
More details needed :) Especially settings, don't look at `django-tenant-schemas` this is different project, we have smth in common, but it's not this project, you can unconsciously do some errors.
You are missing table from shared or tenants apps?

**Comment by dozie** [comment]
```
SHARED_APPS = (
    'tenant_schemas',  # mandatory
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
)

TENANT_APPS = (
    'django.contrib.contenttypes',
    'nprod',
)


TENANT_MODEL = 'nprod.Client'


INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]
```

And for my model

from django.db import models
from tenant_schemas.models import TenantMixin


```
class Client(TenantMixin):
    name = models.CharField(max_length=128)
    created_on = models.DateField(auto_now_add=True)

    auto_create_schema = True

    class Meta:
        db_table = 'Client'
```

so initially I had my application under the tenant app and then I placed it in the shared application. When I tried to apply migration, there was nothing new to do. This is what my environment looks like

**Comment by kosz85** [comment]
Ok, first of all `nprod` should be at `SHARED_APPS` - how you want to knew about Tenants (which are schemas) when you don't have information about them at `public` schema? :)
So first of all app with model that extends `TenantMixin` should be at `SHARED_APPS`.

On your place I would start DB from scratch, you shouldn't move apps around between `TENANT_APPS` and 'SHARED_APPS`, as later some table can overlap other.

Think of it as space inside space. SHARED is `public` space, inside you have `tenant` space that you switch. For `public` schema  (default one) it's empty, for tenant `X` it has the `X` schema inside.
Being at tenant `X` you an access both public and X elements, beeing at `public` you have `NULL` tenant so you can access only things defined at `SHARED` like name says :)

**Comment by dozie** [comment]
Now I am having issues with content type. Am I supposed to have any applications in my tenant app at all?

**Comment by dozie** [comment]
@kosz85 I'm not sure where the issue is arising from in this case but now I am having the same relations problem with the content_type after I moved my application to the shared application.

I don't know if I have the right understanding of this framework because my understanding is this is a way to create a schema for your db so you could work with multiple schemas. 

If I want my tenant application to have its own schema, why do I need to include it in the public schema and even after I have done this, the content app which was syncing in the past (I know because I saw the table before I tried reinstalling my application) doesn't seem to be working.

**Comment by kosz85** [comment]
Oh, I didn't notice you have duplicated `ContentTypes` I suggest to leave it in `SHARED`. Duplicating apps is rather bad idea. In `TENANT` apps you want specific tenant apps, like `apps.blog` or `myshopapp`, `somecontentapp`, that data has to be separated and not shared.  I don't know what kind of webapp you are doing, but for now you don't have any app that should be in `TENANT` section.

**Comment by dozie** [comment]
I wasn't sure what was wrong so I restarted my project and that seems to have solved the issue. 
So if I understand the scenario, its best to use this framework when having multiple applications in my project that might have some common functionality?

**Comment by kosz85** [comment]
To visualise example. You can have blog app. This lib allow you to have multiple blogs served by 1 webapp. You would have `SHARED` apps with models like `User`, `Tenant`, `Site`, etc. And `TENANT` apps with models like `Post`, `Images`, `Comment`, etc.
Now you have nicely separated Data, you have one DB of users that can login to each blog with same account to comment and such, this DB has also info about blogs (tenants). And You have multiple blogs (tenants) each in separate postgresql schema,  with all it's posts, comments and such. You can easily backup/create new/delete such blog, and what is most important  you serve it from 1 webapp, just by switcing the schema you actually use. To serve blog A you switch to schema A, to serve blog B you switch to schema B, and it happens automatically, very easy and nice approach.

**Comment by dozie** [comment]
From your scenario, you used a blog and each blog having its schema. Are they all from the same app cause the way I understand django, an application houses it's models and since we already have our application as part of the shared apps all our models will be added to the shared schema which is not necessarily the case we want. Is it possible to have different models in the same application in SHARED and other in TENANT?

**Comment by kosz85** [comment]
No it's not possible. If you have 1 big app, you need to split it into 
at least 2 smalller apps, one with public models, and second with shared 
models.

**Comment by yasinrawther** [comment]
I have face the same issue in different scenario.
In my project 
```
SHARED_APPS = (
    'tenant_schemas',  # mandatory, should always be before any django app
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'oauth2_provider',
    'rest_framework',
    'schools',
    'users',
)
```
```
TENANT_APPS = (
    'django.contrib.contenttypes',
    # your tenant-specific apps
    'classes',
)
```
And my models structure for classes app:
```
class Grades(models.Model):
    name = models.CharField(max_length=100)

class Sections(models.Model):
	name = models.CharField(max_length=50)

class Classes(models.Model):
    grades = models.ForeignKey(Grades, related_name='grades')
    sections = models.ForeignKey(Sections, related_name='sectionss')
    display_name = models.CharField(max_length=100, null=True, blank=True)
    school = models.ForeignKey(School, related_name='schooldbased')
```
When I am try to fetch the data from classes models from tenant domain. I got the relational error like no relation "classes_grades"

How can I fix this?
