### ISSUE TITLE
How to correctly have contrib.auth in both shared and tenant schemas?

### ISSUE THREAD

**Issue by P0oky** [tomturner/django-tenants#68]
Or: how to disable public <=> tenant relationships in apps common to both

I'm seeking a bit of advice:

I'm trying to use auth in both my public site and tentant sites. Specifically, the User model. My public site is pretty simple, containing only default admin pages for editing Users and Tenants. But django raises an exception when I try to delete any user on my public site. This exception being django is trying to look for a relation that should only exist in tenant apps.

The underlying issue is that django is relating a public User with tenant models. The default behaviour for relationships is to cascade on delete. Which causes a lookup for that tenant model, which doesn't exist in the public schema. Which goes kaboom. I know I can completely disable the reverse relation, but this is not desirable as I still want the reverse to work within tenant apps.

The options I've considered:
A. I'm doing something stupid, or missing something, and I'm too nearsighted to see what
B. using a custom public schema auth/user model that won't interact with tenant relationships
C. going through all of my apps and changing on_delete = CASCADE to on_delete = DO_NOTHING.
D. splitting the public website into its own project
E. spend a lot of time digging through the core code to see if I can selectively disable relationships on the fly
F. add any app containing a User foreign key in TENANT_APPS into SHARED_APPS

For now, I'm operating under the assumption that option B is the least crappy to implement. Options C-F all have some aspect to them that I don't like. 

Any further input would be greatly appreciated.

Thanks.

---
To replicate this, I used the tenant_tutorial as a basis, with just the only data being a public schema and a single tenant/customer.

add the following to tenant_only/models.py:

```python
from django.conf import settings

class TableThree( models.Model ):
     name = models.TextField()
     worker = models.ForeignKey( settings.AUTH_USER_MODEL )
```

open a shell to the public schema and create, then delete, a user:

```python
> python3 manage.py tenant_command shell --schema=public
>>> from django.contrib.auth.models import User
>>> u = User( username = 'test1' )
>>> u.save()
>>> u.delete()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/base.py", line 862, in delete
    return collector.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/deletion.py", line 292, in delete
    count = qs._raw_delete(using=self.using)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/query.py", line 614, in _raw_delete
    return sql.DeleteQuery(self.model).delete_qs(self, using)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/subqueries.py", line 81, in delete_qs
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "tenant_only_tablethree" does not exist
LINE 1: DELETE FROM "tenant_only_tablethree" WHERE "tenant_only_tabl...
                    ^

>>> for att in dir( u ):
...   if '_set' in att:
...     print( att )
... 
__setattr__
__setstate__
_set_pk_val
tablethree_set                # <<< this should not be here
>>> 
```

python 3.4.2
django 1.9.1 ( I also tested this in 1.8.9 with the same results )
django_tenants 1.1.3

**Comment by kosz85** [comment]
Hi,

First of all - you have shared User model.
Second you are trying to delete relation that currently maybe doesn't exist, but can exists! Think about it. If you delete user that is used in some tenants, then this tenant would be corrupted, as it's relations would point to not existent rows in shared User table. This error is raising not without reason.

So you need to clean not only public schema, but all tenants schema, and delete User related data from there also!

A. A bit stupid in my opinion :) Why you need to delete user? Can't you mark it as deleted and set `is_active` to false? Or mark it as "public deleted".
B. This could be, I would think about smth like `UserTenantProfile` shared model, that can be per each tenant and you don't need to delete it, or you can mark further deletion, and do it in some background task (celerybeat one for example) once a while. Tenants models would only use this "UserTenantProfile", without touching directly "User" model. It has many good points, as you will know which users are in which tenants.
C. Rather making one model that you will inherit from, but it's an option. But B. is better.
D. Public would be still there.
E. I think it's possible, but this kind of desing is rahter bad design. You would create a bug factory.
F. Think twice before writing such things ;) You will move whole app into one app, as this relations, are also related to smth, and problem would remain, so you would move next Models, till every model would end in SHARED_APPS.

**Comment by P0oky** [comment]
> First of all - you have shared User model.

I'm interpreting "shared" here to mean global - a single list of users for all tenants + public. And I'm fairly confident this is the case. At least intentionally.
Again using the default tutorial example, I've also run tests to create users in public and tenant schemas. They all end up in the correct place, not all lumped in to the public user table.
I'm only encountering the problem when I delete users from the public schema, not from any of the tenant schemas.

There are already some issues revolving around shared auth( #9, #32 ). I'm not doing anything remotely close to this.


```python
> python3 manage.py tenant_command shell --schema=public
>>> from django.contrib.auth.models import User
>>> u = User( username = 'tester' )
>>> u.save()
>>> ^D

> python3 manage.py tenant_command shell --schema=tenant1
>>> from django.contrib.auth.models import User
>>> u = User( username = 'tester' )
>>> u.save()                                       ### if the user list was truly global, this would error, since username has a unique constraint.
>>> u.delete()                                     ### no error on delete
>>> ^D

> python3 manage.py tenant_command shell --schema=public
>>> from django.contrib.auth.models import User
>>> u = User.objects.get( username = 'tester' )
>>> u                                              ### if users really are global, get should throw a DoesNotExist error
<User: tester>
>>> u.delete()
Traceback (most recent call last):
(... same exception as in original post ...)
```

**Comment by kosz85** [comment]
No, public is your shared space. This is how postgresql schemas works. This is just a namespace, and search_path magic. You have search path set to seek table first in shared schema (public) then in tenant one.
If you add user in one tenant, it should be visible in all tenants if the User model is defined in shared app. If you don't want such behavior, then just don't use public at all, and move app with `User` to tenant apps. You won't have there users at all.

I don't remeber how `python3 manage.py tenant_command shell --schema=tenant1` works, maybe this is a problem that it doesn't add public to `search_path`, why you don't use `python3 manage.py shell` and activate `tenant1` from there?

**Comment by P0oky** [comment]
> manage.py tenant_command shell --schema=tenant1

is equivalent to

> connection.set_tenant( "tenant1" )
> run_command( "shell" )

This has gotten a bit side tracked. Let me add some usage details to my original statement...
Tenants can log into their own domains, and only their own domains. This is working correctly.
I want to have some sort of portal where my company employees can log in to administer tenants.
These public admins do not have permission to log into tenant sites.
Currently, I am using the public tenant as this portal. 
Public users are my company admins. tenant users are client employees. Completely independant.

>https://django-tenants.readthedocs.org/en/latest/use.html
>> The first thing we should do is to create the public tenant to make our main website available.


django.contrib.auth is in both shared and tenant apps:
> https://github.com/tomturner/django-tenants/blob/master/examples/tenant_tutorial/tenant_tutorial/settings.py#L135


So, first off, given the documentation, and the example/tutorial, is using the public tenant for internal employees to edit other tenants acceptable?
And if so, is using the default authentication for everyone also acceptable?

**Comment by tomturner** [comment]
How I am planning to overcome your problem is by creating a hidden user on my tenants which is used for internal staff.

**Comment by kosz85** [comment]
The key info that you just provided is that you have same app with `User` in both `SHARED` and `TENANTS`. You have situation that one `User` table is overlapping another, this is just wrong. On tenants you have in fact 2 `User` tables in same time.

You should create separate auth model just for `public` that is not using any relation to not existent tables.
Other solutions are possible but hacky, as I like hacking ;) then 2 quick ideas:
- You can try to do separate django model, that would point to the same db table (use `Meta` to directly point  `db_name`, you could even point directly schema)
- You can overwrite relations fields and check internally if current tenant is `public`, and if so... just pass over the `RelationField` code.

**Comment by adnanmuttaleb** [comment]
@P0oky have you solved the problem? I am encountering exactly the same problem
