### ISSUE TITLE
ContentType question

### ISSUE THREAD

**Issue by brechmos** [tomturner/django-tenants#69]
This might be related to a question just recently asked but I wanted to give specific context to my question.

I have content types in TENANT_APPS in my settings.py file:

```
TENANT_APPS = (
    'django.contrib.contenttypes',

```

I have approximately 20 tenants and am trying to set a content_type variable in a Tag to a specific content_type.  There were issues, so I boiled it down to:

```
from customer.models import Customer
from django.db import connection
from django.db.models import get_model
from django.contrib.contenttypes.models import ContentType
tenants = Customer.objects.exclude(schema_name="public")

for tenant in tenants:
    if not 'public' in tenant.schema_name:
        print('---------------------------------------------')
        connection.set_tenant(tenant)

        # Add the call tags
        app, model = 'call.Call'.split('.')
        class_object = get_model(app, model)
        print('class object {}'.format(class_object))

        ct = ContentType.objects.get_for_model(class_object)
        print('CT {} and CT.id {}'.format(ct, ct.id))

        cts = ContentType.objects.filter(model__icontains='Call')
        print('CTS: {}'.format([(x.id, x) for x in cts if x.name=='Call']))

```

When I run the above code I get the output below.  What I am confused by is why the CT.id is always "24" from the get_for_model does not match the id when I do the ContentType.objects.filter call.  The last one is what I would expect is correct.  

```
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(90, <ContentType: Call>)]
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(55, <ContentType: Call>)]
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(26, <ContentType: Call>)]
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(17, <ContentType: Call>)]
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(60, <ContentType: Call>)]
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(1, <ContentType: Call>)]
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 24
CTS: [(88, <ContentType: Call>)]


```

I am using django 1.8, Python 3.4 and django-tenants 0.9.1 (yes, slightly older).

**Comment by kosz85** [comment]
I needed to think about your words to have idea what is your problem. And I know it now :)
`get_for_model` is caching first value. It's better to have `ContentTypes` in shared apps, as you will encounter such issues, without doing it. If you insist to have it in tenant apps, then you need to overwrite all `ContetType` cache behaviours to setup multi-tenancy.

**Comment by brechmos** [comment]
Oh, that is interesting.  I just started moving towards that last night with some testing I was doing, but you nailed it.  

I added:
`ContentType.objects.clear_cache()`

after the tenant is set and then everything worked as I expected:

```
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 88
CTS: [(88, <ContentType: Call>)]
CT: Call 88
class object <class 'call.models.Call'>
new CT Call and CT.id 88
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 8
CTS: [(8, <ContentType: Call>)]
CT: Call 8
class object <class 'call.models.Call'>
new CT Call and CT.id 8
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 4
CTS: [(4, <ContentType: Call>)]
CT: Call 4
class object <class 'call.models.Call'>
new CT Call and CT.id 4
---------------------------------------------
class object <class 'call.models.Call'>
CT Call and CT.id 23
CTS: [(23, <ContentType: Call>)]
CT: Call 23
class object <class 'call.models.Call'>
new CT Call and CT.id 23
---------------------------------------------

```

So, admittedly I am still a little confused.  Should the ContentType be in the SHARED or TENANT apps?  It seems the ContentType somehow sits on the edge of the whole tenant thing as it caches but sort of across tenants. (My understanding here is limited.)  I would love to understand it a little more so I don't mess things up.  (And thanks for your help)

**Comment by kosz85** [comment]
Sorry for so late response, I overlooked it. From my point of view, if you are not doing anything strange with `ContentType` you should have it in SHARED apps, it will just share ids for all types. Question is, why you want to have it also in TENANT apps? It will be there already from SHARED.

**Comment by kosz85** [comment]
I don't think it's needed. My big scale production app has no `contenttypes` app in TENANT_APPS. I would even suggest to have it only there. The opposite situation is only good with very slim SHARED apps where we are not using any `contettypes` related features.

If you have time you can contribute to docs.
