### ISSUE TITLE
Where should I put users, auth, session, etc?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [tomturner/django-tenants#7]
Shoud users, auth, session, etc be in the shared schema or per tenant?

Thank you!

**Comment by tomturner** [comment]
Auth can go in both.
Session on need to go in shared


See example app https://github.com/tomturner/django-tenants/tree/master/examples/tenant_tutorial/tenant_tutorial

**Comment by BillBrower** [comment]
@tomturner If auth goes in both how does that work? If you create a user from a tenant only endpoint would it get saved in the tenants auth table?
