### ISSUE TITLE
Difference between shared and tenants apps in testing

### ISSUE THREAD

**Issue by george-silva** [tomturner/django-tenants#70]
Hello everyone,

I might have not see anything like this in the docs, but I checked and I'm not sure.

I have a custom method to create my tenants, which I'm trying to test it. There are things that I need to do to set the client/tenant and I rather not have this scattered all over.

So, I basically create a new client, calculate it's domain based off some settings, create the domain and then I modify the default Site record (SITE_ID = 1) so it's domain matches the domain we created.

This is the method:

```python
    def criar(self, nome, cpf_cnpj, email, dominio=None):
        '''Função wrapper que contém a lógica da criação de um novo
        cliente.'''

        if not self.validador_documento.e_valido(cpf_cnpj):
            raise ValidationError(_(u'CPF ou CNPJ inválido: %(value)s'),
                                  params={'value': cpf_cnpj},
                                  code="cpf_cnpj_invalido")

        cliente = Cliente()
        cliente.nome = nome
        cliente.cpf_cnpj
        cliente.email = email
        cliente.save()

        dominio = Dominio()
        if dominio:
            dominio.domain = self._calcular_dominio_cliente(dominio)
        else:
            dominio.domain = self._calcular_dominio_cliente(cliente.nome)

        dominio.tenant = cliente
        dominio.is_primary = True
        dominio.save()

        site = Site.objects.get(pk=1)
        site.name = cliente.nome
        site.domain = dominio.dominio_completo()
        site.save()

        return cliente
```

When ```auto_create_schema = True```, there is some problem when I hit the cliente.save() line (cliente = tenant). It seems that django-tenants does not create the new schema.

Inside the test, I've tried also, to set (just for the test) ```auto_create_schema = False```. This gives me an error, saying that the Site table does not exists. Of course, django just copied the database definition so it can be run inside the test, and Site is just a ```TENANT_APP```, not a shared one.

Any thoughts on how we can make this happen? I don't care to set ```auto_create_schema=False``` for the tests, I just want to make it work. Also I rather not have to maintain a separate test database.

Thanks

**Comment by kosz85** [comment]
What you mean it's not creating schema? It ends with some error? What is content of your DB after running it?
You just said that when you turn it off then you have error, so probably it is creating smth (the table that doesn't exists).

More info needed.

**Comment by tomturner** [comment]
@george-silva I agree with @kosz85 we need more information or a sample project

**Comment by george-silva** [comment]
sure, Ill post tbe tracebacks when I get a chance.
thanks!

**Comment by tomturner** [comment]
@george-silva did you sort the problem out or can I close the ticket?

**Comment by tomturner** [comment]
No answer so closed the ticket
