### ISSUE TITLE
Problem with Tenant specific user groups

### ISSUE THREAD

**Issue by BenPriceA** [tomturner/django-tenants#71]
Hi Everyone,

I'm having a difficult time trying to get django-tenants to play nicely in my app and I'm wondering if someone can point me in the right direction.

What I am trying to do:

- Use django-tenants to provide schema separation for tenants
- Use django-userena and django-guardian for user accounts and permissions respectively
- Have users be held within the tenant schema and not in the public schema (i.e. each tenant has their own user pool)

What I have tried:

I have tried putting `django.contrib.auth`, `userena` and `guardian` in the SHARED_APPS setting.  This works but results in a single user model that spans all tenants - not what I want (although enough to let me get on with testing other functionality).

Next I tried moving everything user related, including `django.contrib.auth`, into the TENANT_APPS setting.  When I do this I _cannot_ get my initial migrate_schema to run cleanly.  It consistently fails with an error about a broken relation to auth_user.

`django.db.utils.ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...`

Which makes sense because in this configuration auth_user will only exist in the tenant schema and I haven't created those yet.

So...based on some digging through previous issues here I duplicated `django.contrib.auth` in both SHARED_APPS and TENANT_APPS.  This allows the initial migrate_schema command to run cleanly and allows me to create tenants.  However it creates another problem - I now have multiple copies of the auth_ tables.  My specific problem is with auth_group.  With only the basic public and a single tenant created I have:

`public.auth_group
tenant1.auth_group`

Which is as it should be.  My issue is that I have some code that sets up the initial state of the application database which includes creating some groups.  This is a command line tool that I run with the following command:

`python application/manage.py tenant_command setup_my_app --schema=tenant1 --settings=config.settings.local`

This code uses the `Model.objects.get_or_create` method to create the groups and I am getting a really weird problem.  The creation of the object seems to work as expected and creates a row in the tenant1.auth_group table.  However a subsequent use of that group seems to query the public.auth_group table where the row doesn't exist and the code blows up at that point!

Finally I'd like to say thank you very much to everyone who has put time and effort into this project - it has been really helpful for me and I hope one day I'll be able to do something as useful!

**Comment by kosz85** [comment]
I would focus on your initial migration, that can't be created as it's place where the problem lays.
Placing `auth` at `TENANT_APPS` is correct move, but you have to ensure, that you have no relations pointing to `User` at apps from 'SHARED_APPS`. If there are any, you have to move them. But, you can have opposite, so relations at `TENANT_APPS` pointing at models from `SHARED_APPS` (as then your FK and M2M are created in tenant schema, not public)

Please add some more info about migration error, or figure it out alone from my description of solution.

**Comment by BenPriceA** [comment]
Okay, so I've run down the problem and it is with the django-guardian package.  If I remove that everything else migrates cleanly.

As far as I can discern the issue is that guardian creates a default 'Anonymous' user every time a migration is called.  Since at the point where this first runs the user tables don't yet exist this throws the error.

Luckily the Django-Guardian guys understand people may do odd things with their user tables and give you a easy way to override the default anonymous user creation function by way of setting the `GUARDIAN_GET_INIT_ANONYMOUS_USER` value in settings.py to the value of a custom function.

So what I need to do is create a function which checks if it is running against the public tenant and if so simply does nothing while functioning as expected if it runs against an actual tenant.  If anyone has any quick ideas of how to do that I will be all ears but in the mean time I'm off to do some thinking.

Thanks for the pointer in the right direction - I'll keep this updated when / if I fix it.

**Comment by BenPriceA** [comment]
Okay - kind of fixed it by a different route.

set `ANONYMOUS_USER_ID = None` in your settings.py to disable the anonymous user.  Django-guardian then doesn't try to create the anonymous user in the database and everything migrates cleanly.

For me that is fine - I won't have anonymous users hitting the system, everyone is authenticated before they can do anything.  Others mileage may vary of course.

As an aside the approach of a custom `GUARDIAN_GET_INIT_ANONYMOUS_USER` doesn't work.  Here is the code snippet in guardian that causes the blowup:

`def create_anonymous_user(sender, **kwargs):
    """
    Creates anonymous User instance with id and username from settings.
    """
    User = get_user_model()
    try:
        lookup = {User.USERNAME_FIELD: guardian_settings.ANONYMOUS_USER_NAME}
        User.objects.get(**lookup)
    except User.DoesNotExist:
        retrieve_anonymous_function = import_string(
            guardian_settings.GET_INIT_ANONYMOUS_USER)
        user = retrieve_anonymous_function(User)
        user.save()
`

It is the code in the try block that causes the migration to fail and the custom function isn't called until after that happens.  In fact it would never run as it's not catching the 'right' exception in our context.

Without patching the django-guardian code to recognize this particular edge case and react appropriately I can't think of a way around this.  However for my needs turning anonymous users off is enough.  I'll leave this open for the rest of today in case anyone has any thing to add and if it hasn't been closed by tomorrow morning by someone else I'll do it myself.

**Comment by kosz85** [comment]
Yeah, like you said :) I would monkey-patch `create_anonymous_user` to solve your issue, or commit change at django-guardian code. But as you see problem not lays in django-tenants, but other custom solutions.

**Comment by tomturner** [comment]
Looks like you have sorted the issue out so closing the issue
