### ISSUE TITLE
set MEDIA_ROOT per  tenant

### ISSUE THREAD

**Issue by juanefren** [tomturner/django-tenants#72]
Hi, I have my MEDIA_ROOT in /srv/www/upload using default django FileFields/ImageFields from django using upload_to parameter as bare strings for example:
```
class Car(models.Model):
     profile_picture = ImageField(upload_to="profile_pictures")
     billing_document = FileField(upload_to="billing_documents")
     specs_file = FileField(upload_to="specs_files")
```

It automatically uploads the content to:
/srv/www/upload/profile_pictures
/srv/www/upload/billing_documents
/srv/www/upload/specs_files

How would you recommend to proceed if I want to change uploads to:

/srv/www/upload/SCHEMA_NAME/profile_pictures
/srv/www/upload/SCHEMA_NAME/billing_documents
/srv/www/upload/SCHEMA_NAME/specs_files

where SCHEMA_NAME is connection.db.tenant.schema_name

How could I sublcass models.ForeignKey to get that result? (according to docs I could write a custom callable and pass it as upload_to parameter, but that would imply to create one function for each field)

Any ideas about this?
 
Thanks  in advance :)

**Comment by kosz85** [comment]
RTFD :P So please check: https://docs.djangoproject.com/es/1.9/ref/models/fields/#filefield

Then you will know, that `upload_to` can be also callable (function), so you can check there what tenant is active and construct path as you wish.

**Comment by tomturner** [comment]
@juanefren Can you confirm that you have sorted this out if so can you close the ticket

**Comment by juanefren** [comment]
Hi @kosz85  , thanks for the response (also sorry for late reply, I saw this in my phone the weekend and forgot completely).

I was already aware about the docs as I mentioned in the last sentence of the post, but since the only parameters accepted by that callable are the instance and filename so I would be missing the "folder" attribute, (eg. profile_pictures, billing_documents, specs_files). Then figured out I coud create a closure instead of creating a function for each field.

```
def custom_upload_to(folder_name):
     def func(instance, filename):
             return "%s%s/%s" % (MEDIA_ROOT, connection.tenant.schema_name, filename)
     return func


```
Then change each upload_to parameter like this:

```
class Car(models.Model):
     profile_picture = ImageField(upload_to=custom_upload_to("profile_pictures"))
     billing_document = FileField(upload_to=custom_upload_to("billing_documents"))
     specs_file = FileField(upload_to=custom_upload_to("specs_files"))
```
Still I need to copy each instance files of each tenant to it respective folder, I wonder about other possible solutions.

Cheers....

**Comment by kosz85** [comment]
The solution that you proposed was exactly the one I was thinking about. And I think it's good solution it's almost the same as `upload_to="folder"`.
Other solutions... You can create your own `TenantImageField` and `TenantFileField`, and just hide `custom_upload_to` inside, or you can replace `ImageField` and `FileField` with new versions, but I suggest to leave it like it is now.  Less work, look nice, why you want to do anything about it?

This uploading is nothing really complicated, it's just path to file, I don't know what you are expecting to invent here :)
