### ISSUE TITLE
Required Fields in Tenent when running TenantTestCase

### ISSUE THREAD

**Issue by tomturner** [tomturner/django-tenants#73]
If you have required fields in you Tenant or Domain models the test will fail as it hasn't got a value. I am working on a fix.

**Comment by BillBrower** [comment]
For anyone that stumbles across this now you can add your required fields in the  `setup_tenant(cls, tenant)` method by subclassing `TenantTestCase`  like this:

```python
class MyTenantTestCase(TenantTestCase):
    @classmethod
    def setup_tenant(cls, tenant):
        """
        Add any additional setting to the tenant before it get saved. This is required if you have
        required fields.
        :param tenant:
        :return:
        """
        tenant.required_field = 'Value'
        return tenant
```

**Comment by ishtiaque06** [comment]
> For anyone that stumbles across this now you can add your required fields in the `setup_tenant(cls, tenant)` method by subclassing `TenantTestCase` like this:
> 
> ```python
> class MyTenantTestCase(TenantTestCase):
>     @classmethod
>     def setup_tenant(cls, tenant):
>         """
>         Add any additional setting to the tenant before it get saved. This is required if you have
>         required fields.
>         :param tenant:
>         :return:
>         """
>         tenant.required_field = 'Value'
>         return tenant
> ```

You give me faith in humanity. This saved my life.
