### ISSUE TITLE
Typo in docs - django-tenants-schema 

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#76]
Hi,

When I look here: http://django-tenants.readthedocs.io/en/latest/use.html

I see you have **django-tenants-schema**, should it not be **django-tenants**?

**Comment by tomturner** [comment]
Yes I will change it unless you want to put a pull request

**Comment by bartmika** [comment]
I'd like to make a pull request.

**Comment by tomturner** [comment]
No problem you can do so
