### ISSUE TITLE
Is there a way to delete a tenant?

### ISSUE THREAD

**Issue by MiltonLn** [tomturner/django-tenants#8]
Hi, i'm needing a functionality to delete a tenant, is there a way to do it or a new functionality is needed?

**Comment by flxfxp** [comment]
On whatever you've set your `TENANT_MODEL` (e.g. `TENANT_MODEL = "tenant_app.Customer"`) to, add the following to your model:
```
class Customer(TenantMixin):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField('created on',default=timezone.now, blank=True)
    auto_drop_schema = True
    auto_create_schema = True
```
You can now delete tenants by just deleting the entry via the Django ORM.

**Comment by MiltonLn** [comment]
@flxfxp Thank you dude!!!!

**Comment by flxfxp** [comment]
You're welcome, please close :)

**Comment by tomturner** [comment]
A help page is required for this please don't close

**Comment by flxfxp** [comment]
I thought this was in the original tenant-schemas docu?
