### ISSUE TITLE
public & test tenant tests in TenantTestCase?

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#88]
I am looking https://github.com/tomturner/django-tenants/blob/master/django_tenants/test/cases.py and I don't see a **public** test schema, I only see a **tenant** test schema.

I understand how to write unit tests to test out the tenant test schema but I don't understand how to write public test schema. Can anyone give some points or help? I looked at the documentation for testing but it doesn't talk about public/tenant unit testing.

Thanks!

**Comment by kosz85** [comment]
Eeee.... **public** schema is used as default one? So every not **tenant** test is just **public** schema test. Also you can explicit set **public** tenant schema like for normal tenant. It's just matter of changing `search_path` in db cursor.

**Comment by bartmika** [comment]
This issue was solved in #86. Closing ticket.
