### ISSUE TITLE
Different configurations of email by tentant in settings.py ?

### ISSUE THREAD

**Issue by mateuspadua** [tomturner/django-tenants#98]
In my `settings.py`, for first Tenant I need one email that is different of second Tenant, and so on:

`For first Tenant:` 
SERVER_EMAIL = 'contact@mysite1.com.br'
EMAIL_FROM = 'contato@mysite1.com.br'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'contato@mysite1.com.br'
EMAIL_HOST_PASSWORD = 'mypassword_1'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

`For second Tenant:`
SERVER_EMAIL = 'contact@mysite2.com.br'
EMAIL_FROM = 'contato@mysite2.com.br'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'contato@mysite2.com.br'
EMAIL_HOST_PASSWORD = 'mypassword_2'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

There is a way to make this setting?
Any help is welcome, :)

**Comment by kosz85** [comment]
There is, and it's building your own solution.
You just have to have stored this settings somewhere (`settings.py`, `TennantSettings` custom model, etc) and switch `django` settings to that define per tenant before sending an email.
If you have one method of sending emails/notifications/etc (and you should have it with well design app), then you need to ensure that in this single place.
And that is the way.

**Comment by mateuspadua** [comment]
Kosz85, Thanks for your reply. But how i can change settings on fly, because i read in many sites that don't is possible change settings at runtime.
https://docs.djangoproject.com/en/1.8/topics/settings/#altering-settings-at-runtime

**Comment by kosz85** [comment]
It's possible if you know what you are doing ;) Like always, switching schemas at runtime is also smth that is not recommended (because for example of ContentType's cache), but django-tenants allow it.
You can switch email settings (and so connection), if you know what you are doing, and ensure, that all related cache objects are cleared.
Looking at that document part you linked, I also wouldn't recommend switching `DEBUG` flag on the fly, as it involve to many places in django code, but email settings are used only for creating email connection. So if you will ensure clearing previous connection, it should be ok :)

**Comment by mateuspadua** [comment]
Thanks Kosz85. Now I feel more comfortable to do this. I thought it was not possible.
I will do this and then I put the solution here, in case someone else needs. Thanks again.

**Comment by kosz85** [comment]
No need to thank. I really like to encourage people to seek their solutions and hack on their own, as programming is in fact hacking. When you can do that, then nothing is impossible, just your imagination :D and maybe your lifespan ;)

**Comment by mateuspadua** [comment]
I agree with you. :)

**Comment by tomturner** [comment]
@mateuspadua Can i close this now

**Comment by mateuspadua** [comment]
Yes, you can, thanks

**Comment by mateuspadua** [comment]
Here, the solution I found to this problem:

> file: tenants.py

```
TENANTS = {}
TENANTS["my_tenant_1"] = {}
TENANTS["my_tenant_1"]["EMAIL"] = {
	"SERVER_EMAIL": 'email@email.com.br',
	"EMAIL_FROM": 'email@email.com.br',
	"EMAIL_HOST": 'smtp.gmail.com',
	"EMAIL_HOST_USER": 'email@email.com.br',
	"EMAIL_HOST_PASSWORD": 'my_pass',
	"EMAIL_USE_TLS": True,
	"EMAIL_PORT": 587
}

TENANTS["my_tenant_2"] = {}
TENANTS["my_tenant_2"]["EMAIL"] = {
	"SERVER_EMAIL": 'email@email2.com.br',
	"EMAIL_FROM": 'email@email2.com.br',
	"EMAIL_HOST": 'smtp.gmail.com',
	"EMAIL_HOST_USER": 'email@email2.com.br',
	"EMAIL_HOST_PASSWORD": 'my_pass',
	"EMAIL_USE_TLS": True,
	"EMAIL_PORT": 587
}
```

> file: utils/email.py

```
from django.core.mail import EmailMultiAlternatives
from django.db import connection
from tenants import TENANTS

tenant_email = TENANTS[connection.schema_name]["EMAIL"]
    
email_from = tenant_email["EMAIL_FROM"]
msg = EmailMultiAlternatives("subject","html_content", email_from, "to_email@email.com")

# print connection.schema_name
# print connection.tenant
# print "#####"

# print tenant_email

# get connection to change just below
con = msg.get_connection()
# change defaults by tenant configuration
con.host = tenant_email["EMAIL_HOST"]
con.port = tenant_email["EMAIL_PORT"]
con.username = tenant_email["EMAIL_HOST_USER"]
con.password = tenant_email["EMAIL_HOST_PASSWORD"]
con.use_tls = tenant_email["EMAIL_USE_TLS"] if "EMAIL_USE_TLS" in tenant_email else None
con.use_ssl = tenant_email["EMAIL_USE_SSL"] if "EMAIL_USE_SSL" in tenant_email else None
con.timeout = tenant_email[""] if "EMAIL_TIMEOUT" in tenant_email else None
con.ssl_keyfile = tenant_email[""] if "EMAIL_SSL_KEYFILE" in tenant_email else None
con.ssl_certfile = tenant_email[""] if "EMAIL_SSL_CERTFILE" in tenant_email else None

# print "con.host: {0}".format(con.host)  # settings.EMAIL_HOST
# print "con.port: {0}".format(con.port)  # settings.EMAIL_PORT
# print "con.username: {0}".format(con.username)  # settings.EMAIL_HOST_USER
# print "con.password: {0}".format(con.password)  # settings.EMAIL_HOST_PASSWORD
# print "con.use_tls: {0}".format(con.use_tls)  # settings.EMAIL_USE_TLS
# print "con.use_ssl: {0}".format(con.use_ssl)  # settings.EMAIL_USE_SSL
# print "con.timeout: {0}".format(con.timeout)  # settings.EMAIL_TIMEOUT
# print "con.ssl_keyfile: {0}".format(con.ssl_keyfile)  # settings.EMAIL_SSL_KEYFILE
# print "con.ssl_certfile: {0}".format(con.ssl_certfile)  # settings.EMAIL_SSL_CERTFILE

msg.content_subtype = "html"
msg.send()
```

**Comment by kosz85** [comment]
Yeah, almost ok, pack it into some func like `ensure_email_setup()` and monkeypatch `send` method (wrap it) to call `ensure_email_setup` before real sending and you have nice and not too messy solution :)

**Comment by mateuspadua** [comment]
Yes, this way would be very nice too. It is also possible to get the configuration email from database. :)

**Comment by deven769** [comment]
i am here searching for solution and feel happy here. Thank you @mateuspadua  i will try this one :D
